create table inv_stock_transfer (
    transfer_id bigint not null primary key,
    transfer_no varchar(64) not null,
    idempotency_key varchar(128) not null,
    owner_id bigint not null,
    source_warehouse_id bigint not null,
    target_warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(128) null,
    requested_qty decimal(18,4) not null,
    reserved_qty decimal(18,4) not null,
    outbound_qty decimal(18,4) not null,
    received_qty decimal(18,4) not null,
    difference_qty decimal(18,4) not null,
    transfer_status tinyint not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_transfer_no (transfer_no),
    unique key uk_inv_transfer_idempotency (idempotency_key),
    key idx_inv_transfer_status (transfer_status, updated_at),
    key idx_inv_transfer_source (owner_id, source_warehouse_id, transfer_status),
    key idx_inv_transfer_target (owner_id, target_warehouse_id, transfer_status)
) comment '中央库存调拨单';
