create table inv_return_disposition (
  id bigint primary key auto_increment,
  disposition_no varchar(64) not null,
  source_event_id varchar(128) not null,
  after_sale_no varchar(64) not null,
  owner_id bigint not null,
  warehouse_id bigint not null,
  sku_code varchar(64) not null,
  batch_no varchar(64),
  received_qty decimal(18,4) not null,
  sellable_qty decimal(18,4) not null default 0,
  defective_qty decimal(18,4) not null default 0,
  frozen_qty decimal(18,4) not null default 0,
  scrapped_qty decimal(18,4) not null default 0,
  unmatched_qty decimal(18,4) not null default 0,
  created_at datetime(3) not null,
  unique key uk_inv_return_disposition_no(disposition_no),
  unique key uk_inv_return_source_event(source_event_id),
  key idx_inv_return_after_sale(after_sale_no),
  key idx_inv_return_stock(owner_id,warehouse_id,sku_code)
);
