create table inv_freeze (
    freeze_id bigint not null primary key,
    freeze_no varchar(64) not null,
    stock_id bigint not null,
    owner_id bigint not null,
    warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(128) null,
    freeze_qty decimal(18,4) not null,
    unfrozen_qty decimal(18,4) not null default 0,
    freeze_reason varchar(64) not null,
    source_system varchar(32) not null,
    source_order_no varchar(64) not null,
    freeze_status tinyint not null comment '1草稿 2待审批 3已冻结 4部分解冻 5已解冻 6已取消',
    approval_status tinyint not null comment '1草稿 2待审批 3已批准 4已驳回',
    approval_no varchar(64) null,
    created_by bigint not null,
    approved_by bigint null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_freeze_no(freeze_no),
    key idx_inv_freeze_status_time(freeze_status, updated_at),
    key idx_inv_freeze_source(source_system, source_order_no),
    key idx_inv_freeze_account(stock_id)
) comment '库存冻结单聚合';

create table inv_stock_adjustment (
    stock_adjustment_id bigint not null primary key,
    adjustment_no varchar(64) not null,
    stock_id bigint not null,
    owner_id bigint not null,
    warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(128) null,
    adjust_qty decimal(18,4) not null,
    adjustment_type varchar(32) not null,
    adjustment_reason varchar(512) not null,
    source_system varchar(32) not null,
    source_order_no varchar(64) not null,
    adjustment_status tinyint not null comment '1草稿 2待审批 3已批准 4已执行 5已驳回 6已取消',
    approval_status tinyint not null comment '1草稿 2待审批 3已批准 4已驳回',
    approval_no varchar(64) null,
    created_by bigint not null,
    approved_by bigint null,
    executed_by bigint null,
    executed_at datetime(3) null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_adjustment_no(adjustment_no),
    key idx_inv_adjustment_status_time(adjustment_status, updated_at),
    key idx_inv_adjustment_source(source_system, source_order_no),
    key idx_inv_adjustment_account(stock_id)
) comment '库存调整单聚合';

create table inv_inventory_command_receipt (
    idempotency_key varchar(128) not null primary key,
    command_type varchar(64) not null,
    request_fingerprint varchar(1024) not null,
    aggregate_no varchar(64) not null,
    created_at datetime(3) not null,
    key idx_inv_command_aggregate(aggregate_no)
) comment '冻结调整命令持久化幂等回执';

create table inv_operation_audit_log (
    operation_log_id bigint not null primary key,
    operator_id bigint not null,
    operation_type varchar(64) not null,
    operation_reason varchar(512) null,
    target_type varchar(64) not null,
    target_id bigint not null,
    target_no varchar(64) not null,
    before_snapshot json not null,
    after_snapshot json not null,
    result tinyint not null comment '1成功 2失败',
    request_id varchar(128) null,
    idempotency_key varchar(128) not null,
    operation_at datetime(3) not null,
    created_at datetime(3) not null,
    key idx_inv_audit_target(target_type, target_no, operation_at),
    key idx_inv_audit_operator(operator_id, operation_at),
    key idx_inv_audit_idempotency(idempotency_key)
) comment '库存操作审计日志';
