package com.chaobo.scm.supplier.infrastructure.persistence.integration;
import com.chaobo.scm.supplier.application.integration.IntegrationCommand;import org.apache.ibatis.annotations.*;import java.time.OffsetDateTime;import java.util.List;
@Mapper public interface IntegrationCommandMapper{
 @Insert("INSERT IGNORE INTO sup_integration_command(command_id,command_code,command_type,aggregate_type,aggregate_id,aggregate_version,target_system,payload_json,command_status,retry_count) VALUES(#{c.id},#{c.code},#{c.type},#{c.aggregateType},#{c.aggregateId},#{c.aggregateVersion},#{c.targetSystem},CAST(#{c.payloadJson} AS JSON),1,0)")void insert(@Param("c")IntegrationCommand c);
 @Select("SELECT command_id id,command_code code,command_type type,aggregate_type aggregateType,aggregate_id aggregateId,aggregate_version aggregateVersion,target_system targetSystem,payload_json payloadJson,command_status status,retry_count retryCount,next_retry_at nextRetryAt,remote_reference remoteReference,fail_reason failReason FROM sup_integration_command WHERE command_status IN(1,4) AND (next_retry_at IS NULL OR next_retry_at&lt;=NOW(3)) ORDER BY created_at LIMIT #{size} FOR UPDATE SKIP LOCKED")List<IntegrationCommand> lockDispatchable(int size);
 @Update("UPDATE sup_integration_command SET command_status=2 WHERE command_id=#{id} AND command_status IN(1,4)")int markExecuting(long id);
 @Update("UPDATE sup_integration_command SET command_status=3,remote_reference=#{reference},fail_reason=NULL,completed_at=NOW(3) WHERE command_id=#{id} AND command_status=2")void markSucceeded(@Param("id")long id,@Param("reference")String reference);
 @Update("UPDATE sup_integration_command SET command_status=IF(retry_count+1&gt;=#{maxRetries},5,4),retry_count=retry_count+1,next_retry_at=#{nextRetry},fail_reason=#{reason} WHERE command_id=#{id} AND command_status=2 AND retry_count=#{expectedRetry}")void markRetry(@Param("id")long id,@Param("expectedRetry")int expectedRetry,@Param("nextRetry")OffsetDateTime nextRetry,@Param("reason")String reason,@Param("maxRetries")int maxRetries);
 @Update("UPDATE sup_integration_command SET command_status=1,retry_count=0,next_retry_at=NULL,fail_reason=CONCAT('MANUAL_RETRY:',#{reason}) WHERE command_id=#{id} AND command_status=5")void retryManually(@Param("id")long id,@Param("reason")String reason);
}
