-- TMS service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__tms_transport_task.sql"
-- ============================================================================
create table tms_transport_task (
    id bigint primary key auto_increment,
    task_no varchar(40) not null,
    source_system varchar(40) not null,
    source_order_no varchar(80) not null,
    source_line_no varchar(80) null,
    scenario varchar(40) not null,
    shipper_id bigint not null,
    warehouse_id bigint not null,
    origin_address varchar(800) not null,
    destination_address varchar(800) not null,
    package_payload varchar(1200) not null,
    task_status tinyint not null,
    carrier_code varchar(40) null,
    carrier_name varchar(120) null,
    logistics_product_code varchar(40) not null,
    fee_responsibility varchar(40) not null,
    version bigint not null,
    created_at datetime not null,
    updated_at datetime not null,
    unique key uk_tms_transport_task_no (task_no),
    key idx_tms_transport_source (source_system, source_order_no, scenario),
    key idx_tms_transport_query (warehouse_id, carrier_code, task_status)
);

create table tms_domain_event (
    id bigint primary key auto_increment,
    event_type varchar(80) not null,
    business_no varchar(80) not null,
    payload varchar(2000) not null,
    event_status tinyint not null,
    occurred_at datetime not null,
    created_at datetime not null,
    key idx_tms_event_status (event_status, id),
    key idx_tms_event_business (business_no)
);

create table tms_operation_log (
    id bigint primary key auto_increment,
    operation_type varchar(80) not null,
    business_no varchar(80) not null,
    operator_id bigint null,
    idempotency_key varchar(120) null,
    created_at datetime not null,
    key idx_tms_operation_business (business_no),
    key idx_tms_operation_idempotency (idempotency_key)
);

-- ============================================================================
-- Source: V2__tms_waybill_shipping_label.sql"
-- ============================================================================
create table tms_waybill (
    id bigint primary key auto_increment,
    waybill_no varchar(40) not null,
    task_no varchar(40) not null,
    carrier_code varchar(40) not null,
    carrier_name varchar(120) not null,
    carrier_waybill_no varchar(80) not null,
    logistics_product_code varchar(40) not null,
    receipt_payload varchar(1200) null,
    waybill_status tinyint not null,
    void_reason varchar(300) null,
    approval_no varchar(80) null,
    version bigint not null,
    created_at datetime not null,
    updated_at datetime not null,
    unique key uk_tms_waybill_no (waybill_no),
    key idx_tms_waybill_task (task_no, waybill_status),
    key idx_tms_waybill_carrier (carrier_code, carrier_waybill_no)
);

create table tms_shipping_label (
    id bigint primary key auto_increment,
    label_no varchar(40) not null,
    waybill_no varchar(40) not null,
    package_no varchar(80) not null,
    template_version varchar(40) not null,
    label_url varchar(500) not null,
    label_status tinyint not null,
    print_count int not null,
    last_print_device varchar(80) null,
    void_reason varchar(300) null,
    version bigint not null,
    created_at datetime not null,
    updated_at datetime not null,
    unique key uk_tms_label_no (label_no),
    key idx_tms_label_waybill (waybill_no, package_no, label_status)
);

-- ============================================================================
-- Source: V3__tms_tracking_receipt_inbox.sql"
-- ============================================================================
create table tms_tracking_node (
    id bigint primary key auto_increment,
    track_no varchar(40) not null,
    waybill_no varchar(40) not null,
    node_code varchar(40) not null,
    description varchar(300) not null,
    location varchar(200) null,
    track_at datetime not null,
    source_type varchar(60) not null,
    raw_event_id varchar(120) null,
    manual_reason varchar(300) null,
    created_at datetime not null,
    unique key uk_tms_track_no (track_no),
    key idx_tms_track_waybill (waybill_no, track_at),
    key idx_tms_track_dedupe (waybill_no, node_code, track_at)
);

create table tms_delivery_receipt (
    id bigint primary key auto_increment,
    receipt_no varchar(40) not null,
    waybill_no varchar(40) not null,
    receipt_result tinyint not null,
    signed_by varchar(80) null,
    signed_at datetime not null,
    reject_reason varchar(300) null,
    proof_url varchar(500) null,
    created_at datetime not null,
    unique key uk_tms_receipt_no (receipt_no),
    unique key uk_tms_receipt_waybill (waybill_no)
);

create table tms_event_inbox (
    id bigint primary key auto_increment,
    event_id varchar(160) not null,
    event_type varchar(80) not null,
    business_no varchar(80) not null,
    payload varchar(2000) null,
    event_status tinyint not null,
    error_message varchar(500) null,
    created_at datetime not null,
    updated_at datetime not null,
    unique key uk_tms_inbox_event (event_id),
    key idx_tms_inbox_status (event_status, id)
);

-- ============================================================================
-- Source: V4__tms_exception_fee_source.sql"
-- ============================================================================
create table tms_logistics_exception (
    id bigint primary key auto_increment,
    exception_no varchar(40) not null,
    waybill_no varchar(40) not null,
    exception_type varchar(40) not null,
    exception_level varchar(20) not null,
    description varchar(500) not null,
    responsible_party varchar(40) null,
    exception_status tinyint not null,
    close_result varchar(500) null,
    version bigint not null,
    created_at datetime not null,
    updated_at datetime not null,
    unique key uk_tms_exception_no (exception_no),
    key idx_tms_exception_waybill (waybill_no, exception_status)
);

create table tms_logistics_fee_source (
    id bigint primary key auto_increment,
    fee_source_no varchar(40) not null,
    waybill_no varchar(40) not null,
    carrier_code varchar(40) not null,
    logistics_product_code varchar(40) not null,
    fee_item_code varchar(40) not null,
    amount decimal(18, 6) not null,
    currency varchar(10) not null,
    billing_period varchar(20) not null,
    responsible_party varchar(40) not null,
    push_status tinyint not null,
    bms_receive_no varchar(80) null,
    failure_reason varchar(500) null,
    version bigint not null,
    created_at datetime not null,
    updated_at datetime not null,
    unique key uk_tms_fee_source_no (fee_source_no),
    key idx_tms_fee_source_waybill_item (waybill_no, fee_item_code),
    key idx_tms_fee_source_push (push_status, id)
);

-- ============================================================================
-- Source: V5__tms_rocketmq_delivery.sql"
-- ============================================================================
alter table tms_domain_event
    add column event_code varchar(120) null after id,
    add column retry_count int not null default 0 after event_status,
    add column last_error varchar(1000) null after retry_count,
    add column next_retry_at datetime(3) null after last_error,
    add column published_at datetime(3) null after next_retry_at,
    add column updated_at datetime(3) null after created_at;

update tms_domain_event
   set event_code=concat('TMS-',id),updated_at=created_at
 where event_code is null;

alter table tms_domain_event
    add unique key uk_tms_domain_event_code (event_code),
    add key idx_tms_event_retry (event_status,next_retry_at,id);

-- ============================================================================
-- Source: V6__tms_dubbo_collaboration.sql"
-- ============================================================================
CREATE TABLE tms_dubbo_transport_request (
    request_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    business_type VARCHAR(32) NOT NULL,
    business_id BIGINT NOT NULL,
    business_no VARCHAR(64) NOT NULL,
    shipper_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    carrier_code VARCHAR(64) NULL,
    tracking_no VARCHAR(128) NULL,
    request_payload TEXT NOT NULL,
    request_status TINYINT NOT NULL DEFAULT 1,
    cancel_reason VARCHAR(500) NULL,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (request_id),
    UNIQUE KEY uk_tms_dubbo_idempotency (idempotency_key),
    UNIQUE KEY uk_tms_dubbo_business (business_type, business_id)
);

CREATE TABLE tms_dubbo_command_receipt (
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    reference_no VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (idempotency_key)
);

-- ============================================================================
-- Source: V7__tms_inbound_event_business_projection.sql"
-- ============================================================================
CREATE TABLE tms_inbound_business_projection (
    id BIGINT NOT NULL AUTO_INCREMENT,
    projection_type VARCHAR(64) NOT NULL,
    object_key VARCHAR(192) NOT NULL,
    source_system VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    projection_status VARCHAR(32) NOT NULL,
    payload JSON NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tms_inbound_projection (projection_type, object_key),
    UNIQUE KEY uk_tms_inbound_projection_event (event_id),
    KEY idx_tms_inbound_projection_status (projection_type, projection_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='TMS入站主数据、审批和运输事实投影';

SET FOREIGN_KEY_CHECKS = 1;

