spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:mysql://localhost:3306/scm_iam?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  flyway:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
scm:
  iam:
    jwt:
      hmac-secret: ${IAM_JWT_SECRET:}
