create table oms_reverse_after_sale (
  id bigint primary key auto_increment,
  after_sale_no varchar(64) not null,
  after_sale_type varchar(32) not null,
  sales_order_no varchar(64) not null,
  fulfillment_no varchar(64) not null,
  owner_id bigint not null,
  sku_code varchar(64) not null,
  apply_qty decimal(18,4) not null,
  refund_amount decimal(18,2) not null default 0,
  return_warehouse_id bigint not null default 0,
  reason varchar(512) not null,
  rma_no varchar(64),
  received_qty decimal(18,4) not null default 0,
  accepted_qty decimal(18,4) not null default 0,
  refunded_amount decimal(18,2) not null default 0,
  after_sale_status tinyint not null,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_reverse_after_sale_no(after_sale_no),
  unique key uk_oms_reverse_rma_no(rma_no),
  key idx_oms_reverse_order_sku(sales_order_no,sku_code),
  key idx_oms_reverse_status(after_sale_status,updated_at)
);
