create table oms_fulfillment_metric_export (
  id bigint primary key auto_increment,
  export_no varchar(64) not null,
  period_start datetime not null,
  period_end datetime not null,
  organization_scope varchar(2000) not null,
  owner_scope varchar(2000) not null,
  warehouse_scope varchar(2000) not null,
  requested_by bigint not null,
  idempotency_key varchar(128) not null,
  request_hash varchar(64) not null,
  export_status tinyint not null,
  attempt_count int not null default 0,
  next_retry_at datetime null,
  processing_started_at datetime null,
  object_key varchar(512) null,
  file_name varchar(255) null,
  content_type varchar(128) null,
  file_size bigint null,
  record_count int null,
  last_error varchar(512) null,
  version bigint not null default 1,
  created_at datetime not null,
  updated_at datetime not null,
  completed_at datetime null,
  unique key uk_oms_metric_export_no (export_no),
  unique key uk_oms_metric_export_idempotency (requested_by, idempotency_key),
  key idx_oms_metric_export_dispatch (export_status, next_retry_at, processing_started_at),
  key idx_oms_metric_export_requester (requested_by, created_at)
);
