package com.chaobo.scm.supplier.application.order;
import com.chaobo.scm.common.api.PageResult;import com.chaobo.scm.common.error.*;import com.chaobo.scm.common.integration.WmsCollaborationApi;import com.chaobo.scm.supplier.application.integration.IntegrationCommandEnqueuer;import com.chaobo.scm.supplier.application.shared.*;import com.chaobo.scm.supplier.domain.asn.*;import com.chaobo.scm.supplier.domain.order.*;import com.chaobo.scm.supplier.domain.shared.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.function.Consumer;
@Service public class PoConfirmApplicationService{
 private final PoConfirmRepository repo;private final PoConfirmReadModelPort read;private final OutboxRepository outbox;private final AuditLogRepository audit;private final IdentifierGenerator ids;private final TransactionalCommandExecutor executor;private final AsnRepository asns;private final IntegrationCommandEnqueuer integrations;
 public PoConfirmApplicationService(PoConfirmRepository repo,PoConfirmReadModelPort read,OutboxRepository outbox,AuditLogRepository audit,IdentifierGenerator ids,TransactionalCommandExecutor executor,AsnRepository asns,IntegrationCommandEnqueuer integrations){this.repo=repo;this.read=read;this.outbox=outbox;this.audit=audit;this.ids=ids;this.executor=executor;this.asns=asns;this.integrations=integrations;}
 @Transactional(readOnly=true)public PageResult<PoConfirmView> page(Long supplierId,Long scope,Integer status,String keyword,int pageNo,int pageSize){if(pageNo<1||pageSize<1||pageSize>100)throw new BusinessException(ErrorCode.VALIDATION_FAILED,"分页参数不合法");return read.page(scope==null?supplierId:scope,status,keyword,pageNo,pageSize);}
 @Transactional(readOnly=true)public PoConfirmView detail(long id,Long scope){var v=read.detail(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"采购订单确认不存在"));if(scope!=null&&scope!=v.supplierId())throw new BusinessException(ErrorCode.NOT_FOUND,"采购订单确认不存在");return v;}
 @Transactional(readOnly=true)public CommandResult detailByPurchaseOrder(long purchaseOrderId){var aggregate=repo.findByPurchaseOrderId(purchaseOrderId).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"采购订单确认不存在"));return result(aggregate,null,true);}
 @Transactional public CommandResult receive(long poId,String poNo,long supplierId,OffsetDateTime deadline,List<PoConfirmAggregate.NewLine> lines,int sourceVersion,CommandContext c){c.requirePermission("supplier:openapi:purchase_order:receive");record R(long poId,String poNo,long supplierId,OffsetDateTime deadline,List<PoConfirmAggregate.NewLine> lines,int sourceVersion){}var request=new R(poId,poNo,supplierId,deadline,lines,sourceVersion);return executor.execute("supplier:po",c,request,()->repo.findByPurchaseOrderId(poId).map(aggregate->{if(sourceVersion<=aggregate.sourceVersion())return result(aggregate,null,true);if(aggregate.supplierId()!=supplierId)throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"订单变更不能更换供应商");String before=snapshot(aggregate);aggregate.applyOrderChange(deadline,lines,sourceVersion,c.operatorId(),ids);return persist(aggregate,c,"CHANGE_PURCHASE_ORDER",before);}).orElseGet(()->persist(PoConfirmAggregate.receive(poId,poNo,supplierId,deadline,lines,sourceVersion,c.operatorId(),ids),c,"RECEIVE_PURCHASE_ORDER",null)));}
 @Transactional public CommandResult receive(long poId,String poNo,long supplierId,OffsetDateTime deadline,List<PoConfirmAggregate.NewLine> lines,CommandContext c){return receive(poId,poNo,supplierId,deadline,lines,1,c);}
 @Transactional public CommandResult cancelByPurchase(long poId,int sourceVersion,String reason,CommandContext c){c.requirePermission("supplier:openapi:purchase_order:receive");var aggregate=repo.findByPurchaseOrderId(poId).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"采购订单确认不存在"));if(sourceVersion<=aggregate.sourceVersion())return result(aggregate,null,true);String before=snapshot(aggregate);aggregate.cancel(sourceVersion,reason,c.operatorId(),ids);return persist(aggregate,c,"CANCEL_PURCHASE_ORDER",before);}
 @Transactional public CommandResult closeByPurchase(long poId,int sourceVersion,CommandContext c){c.requirePermission("supplier:openapi:purchase_order:receive");var aggregate=repo.findByPurchaseOrderId(poId).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"采购订单确认不存在"));if(sourceVersion<=aggregate.sourceVersion())return result(aggregate,null,true);String before=snapshot(aggregate);aggregate.close(sourceVersion,c.operatorId(),ids);return persist(aggregate,c,"CLOSE_PURCHASE_ORDER",before);}
 @Transactional public CommandResult confirm(long id,int version,List<PoConfirmAggregate.LineDecision> lines,String remark,CommandContext c){c.requirePermission("supplier:purchase_order:confirm");return change(id,version,new ConfirmR(id,version,lines,remark),c,"CONFIRM_PURCHASE_ORDER",a->a.confirm(lines,remark,c.operatorId(),ids));}
 @Transactional public CommandResult reject(long id,int version,int reason,String remark,CommandContext c){c.requirePermission("supplier:purchase_order:reject");return change(id,version,new RejectR(id,version,reason,remark),c,"REJECT_PURCHASE_ORDER",a->a.reject(reason,remark,c.operatorId(),ids));}
 @Transactional public CommandResult difference(long id,int version,int type,List<PoConfirmAggregate.LineDifference> lines,String remark,CommandContext c){c.requirePermission("supplier:purchase_order:feedback_diff");return change(id,version,new DiffR(id,version,type,lines,remark),c,"FEEDBACK_PURCHASE_ORDER_DIFF",a->a.feedbackDifference(type,lines,remark,c.operatorId(),ids));}
 @Transactional public CommandResult changeDelivery(long id,int version,long lineId,LocalDate date,String reason,CommandContext c){c.requirePermission("supplier:purchase_order:change_delivery");return change(id,version,new DeliveryR(id,version,lineId,date,reason),c,"CHANGE_PROMISED_DELIVERY",a->a.changeDelivery(lineId,date,reason,c.operatorId(),ids));}
 private CommandResult change(long id,int version,Object request,CommandContext c,String op,Consumer<PoConfirmAggregate> action){return executor.execute("supplier:po",c,request,()->{var a=repo.findById(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"采购订单确认不存在"));c.requireSupplierScope(a.supplierId());if(a.version()!=version)throw new BusinessException(ErrorCode.VERSION_CONFLICT,"采购订单确认版本已变化");String before=snapshot(a);action.accept(a);return persist(a,c,op,before);});}
 private CommandResult persist(PoConfirmAggregate a,CommandContext c,String op,String before){repo.save(a,c.operatorId());var events=a.pullEvents();outbox.saveAll(events);if("CHANGE_PURCHASE_ORDER".equals(op)||"CANCEL_PURCHASE_ORDER".equals(op))coordinateAsns(a,c,op);audit.save(c,op,"PO_CONFIRM",a.confirmId(),a.confirmNo(),before,snapshot(a));String event=events.isEmpty()?null:events.get(events.size()-1).eventCode();return result(a,event,false);}
 private void coordinateAsns(PoConfirmAggregate order,CommandContext context,String operation){String reason="CHANGE_PURCHASE_ORDER".equals(operation)?"采购订单变更，原ASN需重建":"采购订单已取消";for(var asn:asns.findByPurchaseOrderId(order.purchaseOrderId())){if(asn.status()==AsnStatus.CANCELLED||asn.status()==AsnStatus.CLOSED)continue;if(asn.status()==AsnStatus.SHIPPED||asn.status()==AsnStatus.ARRIVED||asn.status()==AsnStatus.RECEIVED)throw new BusinessException(ErrorCode.STATE_CONFLICT,"采购订单已有发货或到仓ASN，需人工处理: "+asn.asnNo());var previous=asn.status();String before=snapshotAsn(asn);asn.cancel(reason,context.operatorId(),ids);asns.save(asn,context.operatorId());outbox.saveAll(asn.pullEvents());audit.save(context,"CANCEL_ASN_BY_PURCHASE_ORDER","ASN",asn.asnId(),asn.asnNo(),before,snapshotAsn(asn));if(previous==AsnStatus.SUBMITTED||previous==AsnStatus.APPOINTED)integrations.enqueue("WMS_CANCEL_APPOINTMENT","ASN",asn.asnId(),asn.version(),"WMS",new WmsCollaborationApi.CancelAppointmentCommand("ASN-CANCEL-"+asn.asnId()+"-"+asn.version(),asn.asnId(),reason));}}
 private String snapshotAsn(AsnAggregate a){return "{\"asnNo\":\"%s\",\"status\":%d,\"version\":%d}".formatted(a.asnNo(),a.status().code(),a.version());}
 private CommandResult result(PoConfirmAggregate a,String event,boolean hit){return new CommandResult(a.confirmId(),a.confirmNo(),a.status().code(),a.status().label(),a.version(),event,hit);}private String snapshot(PoConfirmAggregate a){return "{\"confirmNo\":\"%s\",\"status\":%d,\"version\":%d}".formatted(a.confirmNo(),a.status().code(),a.version());}
 private record ConfirmR(long id,int version,List<PoConfirmAggregate.LineDecision> lines,String remark){}private record RejectR(long id,int version,int reason,String remark){}private record DiffR(long id,int version,int type,List<PoConfirmAggregate.LineDifference> lines,String remark){}private record DeliveryR(long id,int version,long lineId,LocalDate date,String reason){}
}
