CREATE TABLE sup_supplier_return (
  return_id BIGINT PRIMARY KEY,
  return_no VARCHAR(32) NOT NULL,
  supplier_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  source_quality_issue_id BIGINT NULL,
  return_reason VARCHAR(500) NOT NULL,
  return_status TINYINT NOT NULL,
  inventory_lock_no VARCHAR(64) NULL,
  supplier_confirmed_at DATETIME(3) NULL,
  outbound_no VARCHAR(64) NULL,
  shipment_id VARCHAR(64) NULL,
  waybill_no VARCHAR(64) NULL,
  carrier_code VARCHAR(32) NULL,
  settlement_completed TINYINT NOT NULL DEFAULT 0,
  settlement_ref VARCHAR(64) NULL,
  offset_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  claim_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  exception_reason VARCHAR(500) NULL,
  created_by BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_supplier_return_no(return_no),
  KEY idx_supplier_return_supplier_status(supplier_id, return_status),
  KEY idx_supplier_return_quality(source_quality_issue_id)
);

CREATE TABLE sup_supplier_return_line (
  return_line_id BIGINT PRIMARY KEY,
  return_id BIGINT NOT NULL,
  sku_code VARCHAR(64) NOT NULL,
  batch_no VARCHAR(64) NULL,
  inventory_status VARCHAR(32) NOT NULL,
  requested_qty DECIMAL(18,4) NOT NULL,
  locked_qty DECIMAL(18,4) NOT NULL DEFAULT 0,
  outbound_qty DECIMAL(18,4) NOT NULL DEFAULT 0,
  signed_qty DECIMAL(18,4) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_supplier_return_line(return_id, sku_code, batch_no, inventory_status),
  KEY idx_supplier_return_line_return(return_id)
);
