CREATE TABLE IF NOT EXISTS `sup_asn` (
  `asn_id` bigint NOT NULL COMMENT 'ASN聚合根ID',
  `asn_no` varchar(64) NOT NULL COMMENT 'ASN单号',
  `purchase_order_id` bigint NOT NULL COMMENT '采购订单事实快照ID',
  `supplier_id` bigint NOT NULL COMMENT '发货供应商ID',
  `warehouse_id` bigint NOT NULL COMMENT '目的仓ID',
  `eta` datetime(3) NOT NULL COMMENT '预计到仓时间',
  `ship_at` datetime(3) NULL COMMENT '发货时间',
  `carrier_name` varchar(128) NULL COMMENT '承运商快照',
  `tracking_no` varchar(128) NULL COMMENT '运单号快照',
  `asn_status` smallint NOT NULL COMMENT '1草稿 2已提交 3已预约 4已发货 5已到仓 6已收货 7已取消 8已关闭',
  `cancel_reason` varchar(512) NULL COMMENT '取消原因',
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`asn_id`),
  UNIQUE KEY `uk_sup_asn_no` (`asn_no`),
  KEY `idx_sup_asn_supplier_status` (`supplier_id`, `asn_status`, `updated_at`),
  KEY `idx_sup_asn_purchase_order` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ASN聚合根';

CREATE TABLE IF NOT EXISTS `sup_asn_line` (
  `asn_line_id` bigint NOT NULL,
  `asn_id` bigint NOT NULL COMMENT '所属ASN聚合根ID',
  `sku_code` varchar(64) NOT NULL,
  `planned_qty` decimal(18,4) NOT NULL,
  `received_qty` decimal(18,4) NOT NULL DEFAULT 0,
  `batch_no` varchar(128) NULL,
  `production_date` date NULL,
  `expire_date` date NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`asn_line_id`),
  KEY `idx_sup_asn_line_asn` (`asn_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ASN聚合内部行';

CREATE TABLE IF NOT EXISTS `sup_domain_event` (
  `event_id` bigint NOT NULL,
  `event_code` varchar(128) NOT NULL,
  `event_name` varchar(128) NOT NULL,
  `event_type` varchar(128) NOT NULL,
  `aggregate_type` varchar(128) NOT NULL,
  `aggregate_id` bigint NOT NULL,
  `aggregate_no` varchar(128) NULL,
  `source_system` varchar(64) NOT NULL,
  `payload_json` json NOT NULL,
  `event_status` smallint NOT NULL DEFAULT 1 COMMENT '1待发布 2发布中 3已发布 4发布失败 5已取消',
  `retry_count` int NOT NULL DEFAULT 0,
  `fail_reason` varchar(1024) NULL,
  `occurred_at` datetime(3) NOT NULL,
  `published_at` datetime(3) NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `uk_sup_domain_event_code` (`event_code`),
  KEY `idx_sup_domain_event_status` (`event_status`, `created_at`),
  KEY `idx_sup_domain_event_aggregate` (`aggregate_type`, `aggregate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='领域事件发布表';

CREATE TABLE IF NOT EXISTS `sup_operation_audit_log` (
  `operation_log_id` bigint NOT NULL,
  `operator_id` bigint NOT NULL,
  `operator_name` varchar(128) NULL,
  `operation_type` varchar(64) NOT NULL,
  `target_type` varchar(128) NOT NULL,
  `target_id` bigint NULL,
  `target_no` varchar(128) NULL,
  `before_snapshot` json NULL,
  `after_snapshot` json NULL,
  `result` smallint NOT NULL DEFAULT 1,
  `fail_reason` varchar(1024) NULL,
  `request_id` varchar(128) NULL,
  `operation_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`operation_log_id`),
  KEY `idx_sup_operation_audit_target` (`target_type`, `target_id`),
  KEY `idx_sup_operation_audit_operator` (`operator_id`, `operation_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作审计日志';
