CREATE TABLE IF NOT EXISTS sup_supplier_qualification (
 qualification_id bigint NOT NULL,supplier_id bigint NOT NULL,qualification_type varchar(32) NOT NULL,qualification_no varchar(128) NOT NULL,valid_from date NOT NULL,valid_to date NOT NULL,attachment_url varchar(512) NOT NULL,qualification_status smallint NOT NULL COMMENT '1待审核 2有效 3已驳回 4已失效',review_remark varchar(512) NULL,created_by bigint NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_by bigint NULL,updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,deleted tinyint NOT NULL DEFAULT 0,PRIMARY KEY(qualification_id),UNIQUE KEY uk_sup_qualification(supplier_id,qualification_type,qualification_no),KEY idx_sup_qualification_expiry(supplier_id,qualification_status,valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商资质';
CREATE TABLE IF NOT EXISTS sup_supplier_contact (
 contact_id bigint NOT NULL,supplier_id bigint NOT NULL,contact_name varchar(128) NOT NULL,mobile varchar(32) NOT NULL,email varchar(128) NULL,contact_role varchar(32) NOT NULL,is_primary tinyint NOT NULL DEFAULT 0,status smallint NOT NULL DEFAULT 1,created_by bigint NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_by bigint NULL,updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,deleted tinyint NOT NULL DEFAULT 0,PRIMARY KEY(contact_id),KEY idx_sup_contact_supplier(supplier_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商联系人';
CREATE TABLE IF NOT EXISTS sup_supplier_user_binding (
 supplier_user_id bigint NOT NULL,supplier_id bigint NOT NULL,user_id bigint NOT NULL,binding_role varchar(32) NOT NULL,is_primary tinyint NOT NULL DEFAULT 0,status smallint NOT NULL DEFAULT 1,bound_by bigint NOT NULL,bound_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),unbound_at datetime(3) NULL,version int NOT NULL DEFAULT 0,PRIMARY KEY(supplier_user_id),UNIQUE KEY uk_sup_user_binding(supplier_id,user_id),KEY idx_sup_user_lookup(user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商用户绑定';
