-- OMS service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__oms_channel_order_sales_order.sql"
-- ============================================================================
create table oms_sales_order (
  id bigint primary key auto_increment,
  order_no varchar(64) not null,
  channel_code varchar(64) not null,
  channel_order_no varchar(128) not null,
  customer_id bigint not null,
  receiver_address varchar(512) not null,
  line_payload text not null,
  total_amount decimal(18,2) not null,
  order_status tinyint not null,
  review_remark varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_order_no (order_no),
  unique key uk_oms_channel_order (channel_code, channel_order_no)
);

create table oms_channel_order (
  id bigint primary key auto_increment,
  channel_code varchar(64) not null,
  channel_order_no varchar(128) not null,
  order_no varchar(64) not null,
  raw_payload text,
  created_at datetime not null,
  unique key uk_oms_channel_mapping (channel_code, channel_order_no)
);

create table oms_outbox_event (
  id bigint primary key auto_increment,
  event_type varchar(128) not null,
  business_no varchar(128) not null,
  payload text not null,
  event_status tinyint not null,
  occurred_at datetime not null,
  created_at datetime not null,
  key idx_oms_outbox_status (event_status, id)
);

create table oms_operation_log (
  id bigint primary key auto_increment,
  operation_type varchar(64) not null,
  business_no varchar(128) not null,
  operator_id bigint,
  idempotency_key varchar(128),
  created_at datetime not null,
  key idx_oms_operation_business (business_no)
);

-- ============================================================================
-- Source: V2__oms_fulfillment_reservation_outbound.sql"
-- ============================================================================
create table oms_fulfillment (
  id bigint primary key auto_increment,
  fulfillment_no varchar(64) not null,
  sales_order_no varchar(64) not null,
  channel_code varchar(64) not null,
  customer_id bigint not null,
  warehouse_id bigint not null,
  warehouse_code varchar(64) not null,
  logistics_product_code varchar(64),
  line_payload text not null,
  fulfillment_status tinyint not null,
  reservation_ref_no varchar(64),
  reservation_no varchar(64),
  outbound_order_no varchar(64),
  failure_reason varchar(512),
  split_reason varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_fulfillment_no (fulfillment_no),
  unique key uk_oms_fulfillment_sales_order (sales_order_no, fulfillment_no),
  key idx_oms_fulfillment_status (fulfillment_status, updated_at),
  key idx_oms_fulfillment_order (sales_order_no)
);

create table oms_stock_reservation (
  id bigint primary key auto_increment,
  reservation_ref_no varchar(64) not null,
  fulfillment_no varchar(64) not null,
  reservation_no varchar(64),
  reserve_qty decimal(18,4) not null,
  reserved_qty decimal(18,4) not null default 0,
  reservation_status tinyint not null,
  fail_reason varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_reservation_ref (reservation_ref_no),
  key idx_oms_reservation_fulfillment (fulfillment_no),
  key idx_oms_reservation_status (reservation_status, updated_at)
);

create table oms_outbound (
  id bigint primary key auto_increment,
  outbound_order_no varchar(64) not null,
  fulfillment_no varchar(64) not null,
  sales_order_no varchar(64) not null,
  warehouse_id bigint not null,
  warehouse_code varchar(64) not null,
  wms_order_no varchar(64),
  outbound_status tinyint not null,
  cancel_reason varchar(512),
  retry_count int not null default 0,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_outbound_no (outbound_order_no),
  unique key uk_oms_outbound_fulfillment (fulfillment_no),
  key idx_oms_outbound_status (outbound_status, updated_at)
);

create table oms_integration_command (
  id bigint primary key auto_increment,
  command_type varchar(128) not null,
  target_system varchar(32) not null,
  business_no varchar(128) not null,
  idempotency_key varchar(128) not null,
  payload text not null,
  command_status tinyint not null,
  retry_count int not null default 0,
  last_error varchar(512),
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_integration_command (target_system, command_type, idempotency_key),
  key idx_oms_integration_command_status (command_status, updated_at)
);

create table oms_event_inbox (
  id bigint primary key auto_increment,
  event_id varchar(128) not null,
  event_type varchar(128) not null,
  business_no varchar(128) not null,
  payload text not null,
  event_status tinyint not null,
  fail_reason varchar(512),
  created_at datetime not null,
  processed_at datetime,
  unique key uk_oms_event_inbox_event (event_id),
  key idx_oms_event_inbox_status (event_status, created_at)
);

-- ============================================================================
-- Source: V3__oms_cancel_after_sale.sql"
-- ============================================================================
create table oms_cancel_request (
  id bigint primary key auto_increment,
  cancellation_no varchar(64) not null,
  sales_order_no varchar(64) not null,
  fulfillment_no varchar(64) not null,
  outbound_no varchar(64),
  reservation_ref_no varchar(64),
  reason varchar(512) not null,
  cancel_status tinyint not null,
  wms_cancelled tinyint not null default 0,
  stock_released tinyint not null default 0,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_cancellation_no (cancellation_no),
  key idx_oms_cancel_order (sales_order_no),
  key idx_oms_cancel_status (cancel_status, updated_at)
);

create table oms_after_sale (
  id bigint primary key auto_increment,
  after_sale_no varchar(64) not null,
  sales_order_no varchar(64) not null,
  fulfillment_no varchar(64) not null,
  refund_amount decimal(18,2) not null,
  refunded_amount decimal(18,2) not null default 0,
  reason varchar(512) not null,
  after_sale_status tinyint not null,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_after_sale_no (after_sale_no),
  key idx_oms_after_sale_order (sales_order_no),
  key idx_oms_after_sale_status (after_sale_status, updated_at)
);

-- ============================================================================
-- Source: V4__oms_reverse_after_sale.sql"
-- ============================================================================
create table oms_reverse_after_sale (
  id bigint primary key auto_increment,
  after_sale_no varchar(64) not null,
  after_sale_type varchar(32) not null,
  sales_order_no varchar(64) not null,
  fulfillment_no varchar(64) not null,
  owner_id bigint not null,
  sku_code varchar(64) not null,
  apply_qty decimal(18,4) not null,
  refund_amount decimal(18,2) not null default 0,
  return_warehouse_id bigint not null default 0,
  reason varchar(512) not null,
  rma_no varchar(64),
  received_qty decimal(18,4) not null default 0,
  accepted_qty decimal(18,4) not null default 0,
  refunded_amount decimal(18,2) not null default 0,
  after_sale_status tinyint not null,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_oms_reverse_after_sale_no(after_sale_no),
  unique key uk_oms_reverse_rma_no(rma_no),
  key idx_oms_reverse_order_sku(sales_order_no,sku_code),
  key idx_oms_reverse_status(after_sale_status,updated_at)
);

-- ============================================================================
-- Source: V5__oms_read_scope_and_reliable_outbox.sql"
-- ============================================================================
alter table oms_sales_order
  add column organization_id bigint null after id,
  add column owner_id bigint null after organization_id,
  add key idx_oms_order_scope (organization_id, owner_id, updated_at);

alter table oms_outbox_event
  add column event_code varchar(128) null after id,
  add column retry_count int not null default 0 after event_status,
  add column last_error varchar(512) null after retry_count,
  add column last_attempt_at datetime null after last_error,
  add column published_at datetime null after occurred_at,
  add unique key uk_oms_outbox_event_code (event_code);

update oms_outbox_event
set event_code = concat('OMS-', id)
where event_code is null;

alter table oms_outbox_event
  modify column event_code varchar(128) not null;

-- ============================================================================
-- Source: V6__oms_fulfillment_metric_exports.sql"
-- ============================================================================
create table oms_fulfillment_metric_export (
  id bigint primary key auto_increment,
  export_no varchar(64) not null,
  period_start datetime not null,
  period_end datetime not null,
  organization_scope varchar(2000) not null,
  owner_scope varchar(2000) not null,
  warehouse_scope varchar(2000) not null,
  requested_by bigint not null,
  idempotency_key varchar(128) not null,
  request_hash varchar(64) not null,
  export_status tinyint not null,
  attempt_count int not null default 0,
  next_retry_at datetime null,
  processing_started_at datetime null,
  object_key varchar(512) null,
  file_name varchar(255) null,
  content_type varchar(128) null,
  file_size bigint null,
  record_count int null,
  last_error varchar(512) null,
  version bigint not null default 1,
  created_at datetime not null,
  updated_at datetime not null,
  completed_at datetime null,
  unique key uk_oms_metric_export_no (export_no),
  unique key uk_oms_metric_export_idempotency (requested_by, idempotency_key),
  key idx_oms_metric_export_dispatch (export_status, next_retry_at, processing_started_at),
  key idx_oms_metric_export_requester (requested_by, created_at)
);

SET FOREIGN_KEY_CHECKS = 1;

