package com.chaobo.scm.supplier.infrastructure.persistence.order;
import com.chaobo.scm.common.api.PageResult;import com.chaobo.scm.common.error.*;import com.chaobo.scm.supplier.application.order.*;import com.chaobo.scm.supplier.domain.order.*;import org.springframework.stereotype.Repository;import java.util.*;
@Repository public class MyBatisPoConfirmAdapter implements PoConfirmRepository,PoConfirmReadModelPort{
 private final PoConfirmMapper mapper;public MyBatisPoConfirmAdapter(PoConfirmMapper mapper){this.mapper=mapper;}
 public Optional<PoConfirmAggregate> findById(long id){var head=mapper.find(id);return head==null?Optional.empty():Optional.of(aggregate(head));}public Optional<PoConfirmAggregate> findByPurchaseOrderId(long id){var head=mapper.findByPo(id);return head==null?Optional.empty():Optional.of(aggregate(head));}
 public void save(PoConfirmAggregate aggregate,long operator){var head=head(aggregate);if(mapper.find(aggregate.confirmId())==null){mapper.insert(head,operator);aggregate.lines().forEach(value->mapper.insertLine(line(aggregate.confirmId(),value),operator));return;}if(mapper.update(head,aggregate.version()-1,operator)!=1)throw new BusinessException(ErrorCode.VERSION_CONFLICT,"采购订单确认已被更新");for(var value:aggregate.lines()){var row=line(aggregate.confirmId(),value);if(mapper.updateLine(row,operator)==0)mapper.insertLine(row,operator);}mapper.deleteMissingLines(aggregate.confirmId(),aggregate.lines().stream().map(PoConfirmLine::lineId).toList(),operator);}
 public Optional<PoConfirmView> detail(long id){var head=mapper.find(id);return head==null?Optional.empty():Optional.of(view(head,true));}public PageResult<PoConfirmView> page(Long supplierId,Integer status,String keyword,int pageNo,int pageSize){long total=mapper.count(supplierId,status,keyword);var records=mapper.page(supplierId,status,keyword,(pageNo-1)*pageSize,pageSize).stream().map(head->view(head,false)).toList();return new PageResult<>(pageNo,pageSize,total,records);}
 private PoConfirmAggregate aggregate(PoConfirmMapper.Head head){var lines=mapper.lines(head.orderId()).stream().map(value->new PoConfirmLine(value.orderLineId(),value.skuCode(),value.orderQty(),value.requestedDeliveryDate(),value.confirmedQty(),value.confirmedDeliveryDate(),value.lineStatus(),value.diffReason())).toList();return PoConfirmAggregate.rehydrate(head.orderId(),head.confirmNo(),head.purchaseOrderId(),head.purchaseOrderNo(),head.supplierId(),head.confirmDeadline(),lines,PoConfirmStatus.fromCode(head.confirmStatus()),head.confirmedAt(),head.diffType(),head.reasonCode(),head.remark(),head.sourceVersion(),head.version());}
 private PoConfirmMapper.Head head(PoConfirmAggregate aggregate){return new PoConfirmMapper.Head(aggregate.confirmId(),aggregate.confirmNo(),aggregate.purchaseOrderId(),aggregate.purchaseOrderNo(),aggregate.supplierId(),aggregate.status().code(),aggregate.deadline(),aggregate.confirmedAt(),aggregate.diffType(),aggregate.reasonCode(),aggregate.remark(),aggregate.sourceVersion(),aggregate.version(),null);}private PoConfirmMapper.Line line(long orderId,PoConfirmLine value){return new PoConfirmMapper.Line(value.lineId(),orderId,value.skuCode(),value.orderQty(),value.confirmedQty(),value.requestedDate(),value.confirmedDate(),value.status(),value.diffReason());}
 private PoConfirmView view(PoConfirmMapper.Head head,boolean withLines){var status=PoConfirmStatus.fromCode(head.confirmStatus());var lines=withLines?mapper.lines(head.orderId()).stream().map(value->new PoConfirmView.Line(value.orderLineId(),value.skuCode(),value.orderQty(),value.confirmedQty(),value.requestedDeliveryDate(),value.confirmedDeliveryDate(),value.lineStatus(),value.diffReason())).toList():List.<PoConfirmView.Line>of();return new PoConfirmView(head.orderId(),head.confirmNo(),head.purchaseOrderId(),head.purchaseOrderNo(),head.supplierId(),status.code(),status.label(),head.confirmDeadline(),head.confirmedAt(),head.diffType(),head.reasonCode(),head.remark(),head.version(),head.updatedAt(),lines);}
}
