package com.chaobo.scm.supplier.infrastructure.persistence.order;
import org.apache.ibatis.annotations.*;import java.math.BigDecimal;import java.time.*;import java.util.List;
@Mapper public interface PoConfirmMapper{
 record Head(long orderId,String confirmNo,long purchaseOrderId,String purchaseOrderNo,long supplierId,int confirmStatus,OffsetDateTime confirmDeadline,OffsetDateTime confirmedAt,Integer diffType,Integer reasonCode,String remark,int sourceVersion,int version,OffsetDateTime updatedAt){}
 record Line(long orderLineId,long orderId,String skuCode,BigDecimal orderQty,BigDecimal confirmedQty,LocalDate requestedDeliveryDate,LocalDate confirmedDeliveryDate,int lineStatus,String diffReason){}
 String HEAD="SELECT order_id,confirm_no,purchase_order_id,purchase_order_no,supplier_id,confirm_status,confirm_deadline,confirmed_at,diff_type,reason_code,remark,source_version,version,updated_at FROM sup_order ";
 @Select(HEAD+"WHERE order_id=#{id} AND deleted=0")Head find(long id);@Select(HEAD+"WHERE purchase_order_id=#{id} AND deleted=0")Head findByPo(long id);
 @Select("SELECT order_line_id,order_id,sku_code,order_qty,confirmed_qty,requested_delivery_date,confirmed_delivery_date,line_status,diff_reason FROM sup_order_line WHERE order_id=#{id} AND deleted=0 ORDER BY order_line_id")List<Line> lines(long id);
 @Insert("INSERT INTO sup_order(order_id,confirm_no,purchase_order_id,purchase_order_no,supplier_id,confirm_status,confirm_deadline,confirmed_at,diff_type,reason_code,remark,source_version,created_by,updated_by,version,deleted)VALUES(#{r.orderId},#{r.confirmNo},#{r.purchaseOrderId},#{r.purchaseOrderNo},#{r.supplierId},#{r.confirmStatus},#{r.confirmDeadline},#{r.confirmedAt},#{r.diffType},#{r.reasonCode},#{r.remark},#{r.sourceVersion},#{op},#{op},#{r.version},0)")void insert(@Param("r")Head r,@Param("op")long op);
 @Insert("INSERT INTO sup_order_line(order_line_id,order_id,sku_code,order_qty,confirmed_qty,requested_delivery_date,confirmed_delivery_date,line_status,diff_reason,created_by,updated_by,version,deleted)VALUES(#{r.orderLineId},#{r.orderId},#{r.skuCode},#{r.orderQty},#{r.confirmedQty},#{r.requestedDeliveryDate},#{r.confirmedDeliveryDate},#{r.lineStatus},#{r.diffReason},#{op},#{op},0,0)")void insertLine(@Param("r")Line r,@Param("op")long op);
 @Update("UPDATE sup_order SET confirm_status=#{r.confirmStatus},confirm_deadline=#{r.confirmDeadline},confirmed_at=#{r.confirmedAt},diff_type=#{r.diffType},reason_code=#{r.reasonCode},remark=#{r.remark},source_version=#{r.sourceVersion},updated_by=#{op},version=#{r.version} WHERE order_id=#{r.orderId} AND version=#{expected} AND deleted=0")int update(@Param("r")Head r,@Param("expected")int expected,@Param("op")long op);
 @Update("UPDATE sup_order_line SET order_qty=#{r.orderQty},confirmed_qty=#{r.confirmedQty},requested_delivery_date=#{r.requestedDeliveryDate},confirmed_delivery_date=#{r.confirmedDeliveryDate},line_status=#{r.lineStatus},diff_reason=#{r.diffReason},updated_by=#{op},version=version+1,deleted=0 WHERE order_line_id=#{r.orderLineId} AND order_id=#{r.orderId}")int updateLine(@Param("r")Line r,@Param("op")long op);
 @Update("<script>UPDATE sup_order_line SET deleted=1,updated_by=#{op},version=version+1 WHERE order_id=#{orderId} AND deleted=0 <if test='ids!=null and !ids.isEmpty()'>AND order_line_id NOT IN <foreach collection='ids' item='id' open='(' separator=',' close=')'>#{id}</foreach></if></script>")void deleteMissingLines(@Param("orderId")long orderId,@Param("ids")List<Long> ids,@Param("op")long op);
 @Select("<script>SELECT COUNT(*) FROM sup_order WHERE deleted=0 <if test='supplierId != null'>AND supplier_id=#{supplierId}</if><if test='status != null'>AND confirm_status=#{status}</if><if test='keyword != null and keyword != \"\"'>AND purchase_order_no LIKE CONCAT('%',#{keyword},'%')</if></script>")long count(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("keyword")String keyword);
 @Select("<script>"+HEAD+"WHERE deleted=0 <if test='supplierId != null'>AND supplier_id=#{supplierId}</if><if test='status != null'>AND confirm_status=#{status}</if><if test='keyword != null and keyword != \"\"'>AND purchase_order_no LIKE CONCAT('%',#{keyword},'%')</if> ORDER BY updated_at DESC LIMIT #{offset},#{size}</script>")List<Head> page(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("keyword")String keyword,@Param("offset")int offset,@Param("size")int size);
}
