package com.chaobo.scm.supplier.domain.returning;

import com.chaobo.scm.common.error.*;
import com.chaobo.scm.supplier.domain.shared.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.*;

public final class SupplierReturnAggregate {
    private final long id; private final String no; private final long supplierId,warehouseId; private final Long qualityIssueId; private final String reason;
    private final List<SupplierReturnLine> lines; private SupplierReturnStatus status; private String inventoryLockNo,outboundNo,shipmentId,waybillNo,carrierCode,settlementRef,exceptionReason;
    private OffsetDateTime supplierConfirmedAt; private boolean settlementCompleted; private BigDecimal offsetAmount,claimAmount; private int version;
    private final List<DomainEvent> events=new ArrayList<>();
    private SupplierReturnAggregate(long id,String no,long supplierId,long warehouseId,Long qualityIssueId,String reason,List<SupplierReturnLine> lines,SupplierReturnStatus status,String inventoryLockNo,OffsetDateTime supplierConfirmedAt,String outboundNo,String shipmentId,String waybillNo,String carrierCode,boolean settlementCompleted,String settlementRef,BigDecimal offsetAmount,BigDecimal claimAmount,String exceptionReason,int version){this.id=id;this.no=no;this.supplierId=supplierId;this.warehouseId=warehouseId;this.qualityIssueId=qualityIssueId;this.reason=reason;this.lines=new ArrayList<>(lines);this.status=status;this.inventoryLockNo=inventoryLockNo;this.supplierConfirmedAt=supplierConfirmedAt;this.outboundNo=outboundNo;this.shipmentId=shipmentId;this.waybillNo=waybillNo;this.carrierCode=carrierCode;this.settlementCompleted=settlementCompleted;this.settlementRef=settlementRef;this.offsetAmount=nvl(offsetAmount);this.claimAmount=nvl(claimAmount);this.exceptionReason=exceptionReason;this.version=version;validate();}
    public static SupplierReturnAggregate create(long supplierId,long warehouseId,Long qualityIssueId,String reason,List<NewLine> lines,long operator,IdentifierGenerator ids){if(lines==null||lines.isEmpty())throw rule("退供明细不能为空");var entities=lines.stream().map(l->new SupplierReturnLine(ids.nextId(),l.skuCode(),l.batchNo(),l.inventoryStatus(),l.requestedQty(),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO)).toList();var a=new SupplierReturnAggregate(ids.nextId(),ids.nextBusinessNo("SR"),supplierId,warehouseId,qualityIssueId,reason,entities,SupplierReturnStatus.DRAFT,null,null,null,null,null,null,false,null,BigDecimal.ZERO,BigDecimal.ZERO,null,0);a.raise(ids,"SupplierReturnCreated","退供单已创建",operator);return a;}
    public static SupplierReturnAggregate rehydrate(long id,String no,long supplierId,long warehouseId,Long qualityIssueId,String reason,List<SupplierReturnLine> lines,int status,String inventoryLockNo,OffsetDateTime supplierConfirmedAt,String outboundNo,String shipmentId,String waybillNo,String carrierCode,boolean settlementCompleted,String settlementRef,BigDecimal offsetAmount,BigDecimal claimAmount,String exceptionReason,int version){return new SupplierReturnAggregate(id,no,supplierId,warehouseId,qualityIssueId,reason,lines,SupplierReturnStatus.fromCode(status),inventoryLockNo,supplierConfirmedAt,outboundNo,shipmentId,waybillNo,carrierCode,settlementCompleted,settlementRef,offsetAmount,claimAmount,exceptionReason,version);}
    public void submit(long operator,IdentifierGenerator ids){require(SupplierReturnStatus.DRAFT);move(SupplierReturnStatus.PENDING_REVIEW,ids,"SupplierReturnSubmitted","退供单已提交",operator);}
    public void review(boolean approved,String comment,long operator,IdentifierGenerator ids){require(SupplierReturnStatus.PENDING_REVIEW);if(!approved){exceptionReason=required(comment,"驳回原因");move(SupplierReturnStatus.DRAFT,ids,"SupplierReturnRejected","退供单已驳回",operator);return;}move(SupplierReturnStatus.APPROVED,ids,"SupplierReturnApproved","退供单已审核",operator);}
    public void requestInventoryLock(long operator,IdentifierGenerator ids){require(SupplierReturnStatus.APPROVED);move(SupplierReturnStatus.INVENTORY_LOCKING,ids,"SupplierReturnInventoryLockRequested","退供库存锁定已请求",operator);}
    public void recordInventoryLock(boolean success,String lockNo,Map<Long,BigDecimal> quantities,String failureReason,long operator,IdentifierGenerator ids){require(SupplierReturnStatus.INVENTORY_LOCKING);if(!success){exceptionReason=required(failureReason,"锁定失败原因");move(SupplierReturnStatus.APPROVED,ids,"SupplierReturnInventoryLockFailed","退供库存锁定失败",operator);return;}inventoryLockNo=required(lockNo,"库存锁定号");for(var line:lines)line.lock(requiredQty(quantities,line.id(),"锁定"));exceptionReason=null;move(SupplierReturnStatus.PENDING_SUPPLIER_CONFIRMATION,ids,"SupplierReturnInventoryLocked","退供库存已锁定",operator);}
    public void supplierConfirm(boolean hasDifference,String differenceReason,long operator,IdentifierGenerator ids){require(SupplierReturnStatus.PENDING_SUPPLIER_CONFIRMATION);supplierConfirmedAt=OffsetDateTime.now();if(hasDifference){exceptionReason=required(differenceReason,"差异原因");move(SupplierReturnStatus.SUPPLIER_DIFFERENCE,ids,"SupplierReturnDifferenceReported","供应商已反馈退供差异",operator);}else{exceptionReason=null;move(SupplierReturnStatus.PENDING_OUTBOUND,ids,"SupplierReturnConfirmed","供应商已确认退供",operator);}}
    public void resolveDifference(long operator,IdentifierGenerator ids){require(SupplierReturnStatus.SUPPLIER_DIFFERENCE);exceptionReason=null;move(SupplierReturnStatus.PENDING_OUTBOUND,ids,"SupplierReturnDifferenceResolved","退供差异已解决",operator);}
    public void recordOutbound(String outboundNo,Map<Long,BigDecimal> quantities,long operator,IdentifierGenerator ids){require(SupplierReturnStatus.PENDING_OUTBOUND);this.outboundNo=required(outboundNo,"出库单号");for(var line:lines)line.outbound(requiredQty(quantities,line.id(),"出库"));move(SupplierReturnStatus.OUTBOUNDED,ids,"SupplierReturnOutboundCompleted","退供已出库",operator);}
    public void recordWaybill(String shipmentId,String waybillNo,String carrierCode,long operator,IdentifierGenerator ids){if(status!=SupplierReturnStatus.OUTBOUNDED&&status!=SupplierReturnStatus.IN_TRANSIT)throw state("当前状态不能记录运单");this.shipmentId=required(shipmentId,"运输任务号");this.waybillNo=required(waybillNo,"运单号");this.carrierCode=required(carrierCode,"物流商编码");move(SupplierReturnStatus.IN_TRANSIT,ids,"SupplierReturnTransportRecorded","退供运单已记录",operator);}
    public void recordSigned(Map<Long,BigDecimal> quantities,String differenceReason,long operator,IdentifierGenerator ids){require(SupplierReturnStatus.IN_TRANSIT);boolean different=false;for(var line:lines){var qty=requiredQty(quantities,line.id(),"签收");line.sign(qty);different|=qty.compareTo(line.outboundQty())!=0;}if(different){exceptionReason=required(differenceReason,"签收差异原因");move(SupplierReturnStatus.SUPPLIER_DIFFERENCE,ids,"SupplierReturnReceiptDifferenceReported","退供签收存在差异",operator);}else move(SupplierReturnStatus.SIGNED,ids,"SupplierReturnSigned","退供已签收",operator);}
    public void recordTransportException(String reason,long operator,IdentifierGenerator ids){if(status!=SupplierReturnStatus.OUTBOUNDED&&status!=SupplierReturnStatus.IN_TRANSIT)throw state("当前状态不能记录运输异常");exceptionReason=required(reason,"运输异常原因");move(SupplierReturnStatus.SUPPLIER_DIFFERENCE,ids,"SupplierReturnTransportExceptionRecorded","退供运输异常已记录",operator);}
    public void recordSettlement(String ref,BigDecimal offset,BigDecimal claim,long operator,IdentifierGenerator ids){if(status!=SupplierReturnStatus.SIGNED&&status!=SupplierReturnStatus.SUPPLIER_DIFFERENCE)throw state("只有签收后才能记录结算");settlementRef=required(ref,"结算引用号");offsetAmount=nonNegative(offset);claimAmount=nonNegative(claim);settlementCompleted=true;version++;raise(ids,"SupplierReturnSettlementCompleted","退供结算已完成",operator);}
    public void close(long operator,IdentifierGenerator ids){require(SupplierReturnStatus.SIGNED);if(!settlementCompleted)throw rule("退供结算未完成，不能关闭");move(SupplierReturnStatus.CLOSED,ids,"SupplierReturnClosed","退供单已关闭",operator);}
    private void move(SupplierReturnStatus target,IdentifierGenerator ids,String type,String name,long operator){status=target;version++;raise(ids,type,name,operator);} private void require(SupplierReturnStatus expected){if(status!=expected)throw state("当前状态不允许该操作");}
    private void validate(){if(id<=0||supplierId<=0||warehouseId<=0||reason==null||reason.isBlank()||lines.isEmpty())throw rule("退供单信息不完整");if(lines.stream().map(SupplierReturnLine::id).distinct().count()!=lines.size())throw rule("退供明细重复");}
    private void raise(IdentifierGenerator ids,String type,String name,long operator){long eventId=ids.nextId();events.add(new DomainEvent(eventId,"SUP-"+eventId,type,name,"SUPPLIER_RETURN",id,no,version,operator,OffsetDateTime.now(),Map.of("supplierId",supplierId,"warehouseId",warehouseId,"status",status.code())));}
    private static String required(String v,String n){if(v==null||v.isBlank())throw rule(n+"不能为空");return v.trim();} private static BigDecimal requiredQty(Map<Long,BigDecimal> values,long id,String n){if(values==null||!values.containsKey(id))throw rule(n+"数量缺少明细: "+id);return values.get(id);} private static BigDecimal nvl(BigDecimal v){return v==null?BigDecimal.ZERO:v;} private static BigDecimal nonNegative(BigDecimal v){v=nvl(v);if(v.signum()<0)throw rule("金额不能小于0");return v;} private static BusinessException rule(String m){return new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,m);} private static BusinessException state(String m){return new BusinessException(ErrorCode.STATE_CONFLICT,m);}
    public List<DomainEvent> pullEvents(){var copy=List.copyOf(events);events.clear();return copy;} public long id(){return id;} public String no(){return no;} public long supplierId(){return supplierId;} public long warehouseId(){return warehouseId;} public Long qualityIssueId(){return qualityIssueId;} public String reason(){return reason;} public List<SupplierReturnLine> lines(){return List.copyOf(lines);} public SupplierReturnStatus status(){return status;} public String inventoryLockNo(){return inventoryLockNo;} public OffsetDateTime supplierConfirmedAt(){return supplierConfirmedAt;} public String outboundNo(){return outboundNo;} public String shipmentId(){return shipmentId;} public String waybillNo(){return waybillNo;} public String carrierCode(){return carrierCode;} public boolean settlementCompleted(){return settlementCompleted;} public String settlementRef(){return settlementRef;} public BigDecimal offsetAmount(){return offsetAmount;} public BigDecimal claimAmount(){return claimAmount;} public String exceptionReason(){return exceptionReason;} public int version(){return version;}
    public record NewLine(String skuCode,String batchNo,String inventoryStatus,BigDecimal requestedQty){}
}
