package com.chaobo.scm.supplier.interfaces.web;import com.chaobo.scm.common.api.*;import com.chaobo.scm.supplier.application.order.*;import com.chaobo.scm.supplier.application.shared.CommandResult;import com.chaobo.scm.supplier.domain.order.PoConfirmAggregate;import com.chaobo.scm.supplier.infrastructure.security.CommandContextFactory;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.time.*;import java.util.List;
@RestController @RequestMapping("/api/supplier/v1/po-confirms")public class PoConfirmController{
 private final PoConfirmApplicationService service;private final CommandContextFactory contexts;public PoConfirmController(PoConfirmApplicationService s,CommandContextFactory c){service=s;contexts=c;}
 @GetMapping @PreAuthorize("hasAuthority('supplier:po_confirm:read')")public ApiResponse<PageResult<PoConfirmView>>page(@RequestParam(required=false)Long supplierId,@RequestParam(required=false)Integer status,@RequestParam(required=false)String keyword,@RequestParam(defaultValue="1")int pageNo,@RequestParam(defaultValue="20")int pageSize,@AuthenticationPrincipal Jwt jwt,HttpServletRequest r){return ApiResponse.success(service.page(supplierId,scope(jwt),status,keyword,pageNo,pageSize),r.getHeader("X-Request-Id"),r.getHeader("X-Trace-Id"));}
 @GetMapping("/{id}")@PreAuthorize("hasAuthority('supplier:po_confirm:read')")public ApiResponse<PoConfirmView>detail(@PathVariable long id,@AuthenticationPrincipal Jwt jwt,HttpServletRequest r){return ApiResponse.success(service.detail(id,scope(jwt)),r.getHeader("X-Request-Id"),r.getHeader("X-Trace-Id"));}
 @PostMapping("/{id}/confirm")public ApiResponse<CommandResult>confirm(@PathVariable long id,@Valid @RequestBody ConfirmRequest b,HttpServletRequest r,Authentication a){var lines=b.lines().stream().map(v->new PoConfirmAggregate.LineDecision(v.orderLineId(),v.confirmedQty(),v.confirmedDeliveryDate())).toList();return ok(service.confirm(id,b.version(),lines,b.remark(),contexts.create(r,a)),r);}
 @PostMapping("/{id}/reject")public ApiResponse<CommandResult>reject(@PathVariable long id,@Valid @RequestBody RejectRequest b,HttpServletRequest r,Authentication a){return ok(service.reject(id,b.version(),b.reasonCode(),b.remark(),contexts.create(r,a)),r);}
 @PostMapping("/{id}/feedback-diff")public ApiResponse<CommandResult>diff(@PathVariable long id,@Valid @RequestBody DiffRequest b,HttpServletRequest r,Authentication a){var lines=b.lines().stream().map(v->new PoConfirmAggregate.LineDifference(v.orderLineId(),v.confirmedQty(),v.confirmedDeliveryDate(),v.reason())).toList();return ok(service.difference(id,b.version(),b.diffType(),lines,b.remark(),contexts.create(r,a)),r);}
 @PostMapping("/{id}/change-delivery-date")public ApiResponse<CommandResult>date(@PathVariable long id,@Valid @RequestBody DeliveryRequest b,HttpServletRequest r,Authentication a){return ok(service.changeDelivery(id,b.version(),b.orderLineId(),b.newDeliveryDate(),b.reason(),contexts.create(r,a)),r);}
 private ApiResponse<CommandResult>ok(CommandResult x,HttpServletRequest r){return ApiResponse.success(x,r.getHeader("X-Request-Id"),r.getHeader("X-Trace-Id"));}private Long scope(Jwt j){Number n=j.hasClaim("supplier_id")?j.getClaim("supplier_id"):null;return n==null?null:n.longValue();}
 public record ConfirmRequest(@NotEmpty List<@Valid ConfirmLine>lines,String remark,@PositiveOrZero int version){}public record ConfirmLine(@Positive long orderLineId,@NotNull @Positive BigDecimal confirmedQty,@NotNull LocalDate confirmedDeliveryDate){}public record RejectRequest(@Positive int reasonCode,String remark,@PositiveOrZero int version){}public record DiffRequest(@Min(1)@Max(4)int diffType,@NotEmpty List<@Valid DiffLine>lines,String remark,@PositiveOrZero int version){}public record DiffLine(@Positive long orderLineId,BigDecimal confirmedQty,LocalDate confirmedDeliveryDate,@NotBlank String reason){}public record DeliveryRequest(@Positive long orderLineId,@NotNull LocalDate newDeliveryDate,@NotBlank String reason,@PositiveOrZero int version){}
}
