package com.chaobo.scm.supplier.interfaces.web;
import com.chaobo.scm.common.api.*;import com.chaobo.scm.supplier.application.item.*;import com.chaobo.scm.supplier.application.shared.CommandResult;import com.chaobo.scm.supplier.domain.item.SupplyCondition;import com.chaobo.scm.supplier.infrastructure.security.CommandContextFactory;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.security.oauth2.jwt.Jwt;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.time.LocalDate;
@RestController @RequestMapping("/api/supplier/v1/items") public class SupplierItemController{
 private final SupplierItemApplicationService service;private final CommandContextFactory contexts;public SupplierItemController(SupplierItemApplicationService service,CommandContextFactory contexts){this.service=service;this.contexts=contexts;}
 @GetMapping @PreAuthorize("hasAuthority('supplier:sku:read')") public ApiResponse<PageResult<SupplierItemView>> page(@RequestParam(required=false)Long supplierId,@RequestParam(required=false)Integer status,@RequestParam(required=false)String keyword,@RequestParam(defaultValue="1")int pageNo,@RequestParam(defaultValue="20")int pageSize,@AuthenticationPrincipal Jwt jwt,HttpServletRequest req){return ApiResponse.success(service.page(supplierId,scope(jwt),status,keyword,pageNo,pageSize),req.getHeader("X-Request-Id"),req.getHeader("X-Trace-Id"));}
 @GetMapping("/{id}") @PreAuthorize("hasAuthority('supplier:sku:read')") public ApiResponse<SupplierItemView> detail(@PathVariable long id,@AuthenticationPrincipal Jwt jwt,HttpServletRequest req){return ApiResponse.success(service.detail(id,scope(jwt)),req.getHeader("X-Request-Id"),req.getHeader("X-Trace-Id"));}
 @PostMapping public ApiResponse<CommandResult> enable(@Valid @RequestBody EnableRequest b,HttpServletRequest req,Authentication a){return ok(service.enable(b.supplierId(),b.skuCode(),b.supplierSkuCode(),b.condition(),contexts.create(req,a)),req);}
 @PutMapping("/{id}") public ApiResponse<CommandResult> change(@PathVariable long id,@Valid @RequestBody ChangeRequest b,HttpServletRequest req,Authentication a){return ok(service.change(id,b.version(),b.supplierSkuCode(),b.condition(),contexts.create(req,a)),req);}
 @PostMapping("/{id}/pause") public ApiResponse<CommandResult> pause(@PathVariable long id,@Valid @RequestBody StateRequest b,HttpServletRequest req,Authentication a){return ok(service.pause(id,b.version(),b.reason(),contexts.create(req,a)),req);}
 @PostMapping("/{id}/resume") public ApiResponse<CommandResult> resume(@PathVariable long id,@Valid @RequestBody VersionRequest b,HttpServletRequest req,Authentication a){return ok(service.resume(id,b.version(),contexts.create(req,a)),req);}
 @PostMapping("/{id}/discontinue") public ApiResponse<CommandResult> discontinue(@PathVariable long id,@Valid @RequestBody StateRequest b,HttpServletRequest req,Authentication a){return ok(service.discontinue(id,b.version(),b.reason(),contexts.create(req,a)),req);}
 private ApiResponse<CommandResult> ok(CommandResult r,HttpServletRequest q){return ApiResponse.success(r,q.getHeader("X-Request-Id"),q.getHeader("X-Trace-Id"));}private Long scope(Jwt j){Number n=j.hasClaim("supplier_id")?j.getClaim("supplier_id"):null;return n==null?null:n.longValue();}
 public record EnableRequest(@Positive long supplierId,@NotBlank String skuCode,String supplierSkuCode,@NotNull BigDecimal moq,@NotNull BigDecimal mpq,@PositiveOrZero int leadTimeDays,@NotBlank String purchaseUnit,LocalDate effectiveFrom,LocalDate effectiveTo){SupplyCondition condition(){return new SupplyCondition(moq,mpq,leadTimeDays,purchaseUnit,effectiveFrom,effectiveTo);}}
 public record ChangeRequest(String supplierSkuCode,@NotNull BigDecimal moq,@NotNull BigDecimal mpq,@PositiveOrZero int leadTimeDays,@NotBlank String purchaseUnit,LocalDate effectiveFrom,LocalDate effectiveTo,@PositiveOrZero int version){SupplyCondition condition(){return new SupplyCondition(moq,mpq,leadTimeDays,purchaseUnit,effectiveFrom,effectiveTo);}}
 public record StateRequest(@PositiveOrZero int version,@NotBlank String reason){}public record VersionRequest(@PositiveOrZero int version){}
}
