-- WMS service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__wms_inbound_order.sql"
-- ============================================================================
create table wms_inbound (
    inbound_id bigint not null primary key,
    inbound_order_no varchar(64) not null,
    source_type varchar(32) not null,
    source_order_no varchar(64) not null,
    warehouse_id bigint not null,
    inbound_status tinyint not null comment '1待到货 2已到货 3收货中 4待质检 9已取消',
    expected_arrival_at datetime(3) null,
    cancel_reason varchar(512) null,
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_wms_inbound_no (inbound_order_no),
    unique key uk_wms_inbound_source (source_type, source_order_no, warehouse_id),
    key idx_wms_inbound_warehouse_status (warehouse_id, inbound_status, updated_at)
) comment 'WMS入库单';

-- ============================================================================
-- Source: V2__wms_operation_tables.sql"
-- ============================================================================
create table wms_receipt (
    receipt_id bigint not null primary key,
    receipt_no varchar(64) not null,
    inbound_id bigint not null,
    sku_code varchar(64) not null,
    expected_qty decimal(18,6) not null,
    received_qty decimal(18,6) not null default 0,
    rejected_qty decimal(18,6) not null default 0,
    receipt_status tinyint not null comment '1收货中 2已收货 3异常',
    version int not null, created_by bigint not null, updated_by bigint not null,
    created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_receipt_no(receipt_no), key idx_wms_receipt_inbound(inbound_id, receipt_status)
) comment 'WMS收货单';

create table wms_inspection (
    inspection_id bigint not null primary key, inspection_no varchar(64) not null, receipt_id bigint not null,
    inspect_qty decimal(18,6) not null, qualified_qty decimal(18,6) not null default 0,
    unqualified_qty decimal(18,6) not null default 0, inspection_status tinyint not null comment '1待检 2已完成',
    version int not null, created_by bigint not null, updated_by bigint not null, created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_inspection_no(inspection_no), key idx_wms_inspection_receipt(receipt_id, inspection_status)
) comment 'WMS质检单';

create table wms_putaway_task (
    task_id bigint not null primary key, task_no varchar(64) not null, inspection_id bigint not null,
    required_qty decimal(18,6) not null, putaway_qty decimal(18,6) not null default 0,
    task_status tinyint not null comment '1待上架 2已完成', version int not null,
    created_by bigint not null, updated_by bigint not null, created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_putaway_no(task_no), key idx_wms_putaway_inspection(inspection_id, task_status)
) comment 'WMS上架任务';

create table wms_stock_ledger (
    ledger_id bigint not null primary key, warehouse_id bigint not null, location_code varchar(64) not null,
    sku_code varchar(64) not null, batch_no varchar(64) null, transaction_type varchar(32) not null,
    quantity decimal(18,6) not null, source_type varchar(32) not null, source_no varchar(64) not null,
    occurred_at datetime(3) not null, created_at datetime(3) not null,
    key idx_wms_ledger_stock(warehouse_id, location_code, sku_code, occurred_at), key idx_wms_ledger_source(source_type, source_no)
) comment 'WMS仓内库存流水';

create table wms_outbound (
    outbound_id bigint not null primary key, outbound_no varchar(64) not null, source_type varchar(32) not null,
    source_no varchar(64) not null, warehouse_id bigint not null, outbound_status tinyint not null,
    version int not null, created_by bigint not null, updated_by bigint not null, created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_outbound_no(outbound_no), unique key uk_wms_outbound_source(source_type, source_no, warehouse_id)
) comment 'WMS出库单';

create table wms_wave (wave_id bigint not null primary key, wave_no varchar(64) not null, warehouse_id bigint not null,
    wave_status tinyint not null, version int not null, created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_wave_no(wave_no)) comment 'WMS波次单';

create table wms_pick_task (task_id bigint not null primary key, task_no varchar(64) not null, wave_id bigint not null,
    outbound_id bigint not null, sku_code varchar(64) not null, required_qty decimal(18,6) not null, picked_qty decimal(18,6) not null default 0,
    task_status tinyint not null, version int not null, created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_pick_task_no(task_no), key idx_wms_pick_wave(wave_id, task_status)) comment 'WMS拣货任务';

create table wms_operation_event (event_id bigint not null primary key, event_code varchar(128) not null, event_type varchar(128) not null,
    aggregate_type varchar(64) not null, aggregate_id varchar(64) not null, aggregate_version int not null, payload_json json not null,
    status tinyint not null default 1, retry_count int not null default 0, created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_event_code(event_code), key idx_wms_event_status(status, created_at)) comment 'WMS Outbox事件';

-- ============================================================================
-- Source: V3__wms_inbox_and_audit.sql"
-- ============================================================================
create table wms_inbox_event (
    inbox_id bigint not null auto_increment primary key, source_system varchar(64) not null, event_code varchar(128) not null,
    event_type varchar(128) not null, payload_json json not null, status tinyint not null comment '1处理中 2成功 3失败',
    retry_count int not null default 0, last_error varchar(1024) null, created_at datetime(3) not null, updated_at datetime(3) not null,
    unique key uk_wms_inbox(source_system,event_code), key idx_wms_inbox_status(status,updated_at)
) comment 'WMS入站事件收件箱';
create table wms_operation_log (
    log_id bigint not null auto_increment primary key, request_id varchar(128) null, trace_id varchar(128) null,
    operator_id bigint not null, operation varchar(128) not null, target_type varchar(64) not null, target_no varchar(64) not null,
    before_snapshot json null, after_snapshot json null, created_at datetime(3) not null,
    key idx_wms_operation_target(target_type,target_no,created_at)
) comment 'WMS操作审计日志';

-- ============================================================================
-- Source: V4__wms_receipt_scan.sql"
-- ============================================================================
create table wms_receipt_scan (
    scan_id bigint not null primary key, receipt_id bigint not null, idempotency_key varchar(128) not null,
    received_qty decimal(18,6) not null, rejected_qty decimal(18,6) not null, reject_reason varchar(512) null,
    operator_id bigint not null, scanned_at datetime(3) not null,
    unique key uk_wms_receipt_scan_key(receipt_id,idempotency_key), key idx_wms_receipt_scan_receipt(receipt_id,scanned_at)
) comment 'WMS收货PDA扫码流水';

-- ============================================================================
-- Source: V5__wms_container_and_packing.sql"
-- ============================================================================
create table wms_container (
    container_id bigint not null primary key,
    container_no varchar(64) not null,
    outbound_id bigint not null,
    pick_task_id bigint not null,
    container_status tinyint not null comment '1已绑定 2已封箱',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_wms_container_no(container_no),
    key idx_wms_container_outbound(outbound_id, container_status)
) comment 'WMS周转容器';

create table wms_packing (
    packing_id bigint not null primary key,
    packing_no varchar(64) not null,
    outbound_id bigint not null,
    container_no varchar(64) not null,
    packing_status tinyint not null comment '1待复核 2已复核',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_wms_packing_no(packing_no),
    key idx_wms_packing_outbound(outbound_id, packing_status)
) comment 'WMS复核包装单';

-- ============================================================================
-- Source: V6__wms_handover_stocktake_exception.sql"
-- ============================================================================
create table wms_shipment_handover (
    handover_id bigint not null primary key,
    handover_no varchar(64) not null,
    outbound_id bigint not null,
    handover_status tinyint not null comment '1待交接 2已交接',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_wms_handover_no(handover_no)
) comment 'WMS发货交接单';

create table wms_stocktake (
    stocktake_id bigint not null primary key,
    stocktake_no varchar(64) not null,
    warehouse_id bigint not null,
    sku_code varchar(64) not null,
    difference_qty decimal(18,6) not null,
    stocktake_status tinyint not null comment '1待确认 2已确认',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_wms_stocktake_no(stocktake_no)
) comment 'WMS盘点差异';

create table wms_warehouse_exception (
    exception_id bigint not null primary key,
    exception_no varchar(64) not null,
    reason varchar(512) not null,
    exception_status tinyint not null comment '1处理中 2已关闭',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_wms_exception_no(exception_no)
) comment 'WMS仓内异常';

-- ============================================================================
-- Source: V7__wms_transfer_operation.sql"
-- ============================================================================
create table wms_transfer_operation (
    operation_id bigint not null primary key,
    transfer_no varchar(64) not null,
    owner_id bigint not null,
    source_warehouse_id bigint not null,
    target_warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(64) null,
    requested_qty decimal(18,6) not null,
    outbound_qty decimal(18,6) not null default 0,
    received_qty decimal(18,6) not null default 0,
    operation_status tinyint not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_wms_transfer_no(transfer_no),
    key idx_wms_transfer_warehouse(source_warehouse_id,target_warehouse_id,operation_status)
) comment 'WMS调拨执行任务';

-- ============================================================================
-- Source: V8__wms_return_operation.sql"
-- ============================================================================
create table wms_return_operation (
 operation_id bigint primary key, after_sale_no varchar(64) not null, rma_no varchar(64) not null,
 owner_id bigint not null, warehouse_id bigint not null, sku_code varchar(64) not null, batch_no varchar(64),
 expected_qty decimal(18,4) not null, received_qty decimal(18,4) not null default 0,
 sellable_qty decimal(18,4) not null default 0, defective_qty decimal(18,4) not null default 0,
 frozen_qty decimal(18,4) not null default 0, scrapped_qty decimal(18,4) not null default 0,
 unmatched_qty decimal(18,4) not null default 0, operation_status tinyint not null, version int not null,
 created_at datetime(3) not null, updated_at datetime(3) not null,
 unique key uk_wms_return_after_sale(after_sale_no), unique key uk_wms_return_rma(rma_no),
 key idx_wms_return_work(warehouse_id,operation_status,updated_at)
);

-- ============================================================================
-- Source: V9__wms_inbound_read_model_owner.sql"
-- ============================================================================
-- 入库工作台按仓库和货主双维度隔离数据。
-- 历史数据无法可靠推断货主，因此保留 NULL；仅拥有 OWNER=* 的管理员可查看这些遗留记录。
ALTER TABLE wms_inbound
    ADD COLUMN owner_id BIGINT NULL COMMENT '货主ID' AFTER warehouse_id,
    ADD KEY idx_wms_inbound_owner_warehouse_status
        (owner_id, warehouse_id, inbound_status, updated_at);

-- ============================================================================
-- Source: V10__wms_outbound_read_model_owner.sql"
-- ============================================================================
-- 出库作业链以出库单的货主作为统一数据隔离维度。
-- 历史记录不做猜测性回填，仅 OWNER=* 管理员能够查看 owner_id 为空的遗留数据。
ALTER TABLE wms_outbound
    ADD COLUMN owner_id BIGINT NULL COMMENT '货主ID' AFTER warehouse_id,
    ADD KEY idx_wms_outbound_owner_warehouse_status
        (owner_id, warehouse_id, outbound_status, updated_at);

-- ============================================================================
-- Source: V11__wms_operation_scope.sql"
-- ============================================================================
-- 盘点和异常作业必须具备仓库/货主双维度，才能安全暴露列表、详情和处置入口。
ALTER TABLE wms_stocktake
    ADD COLUMN owner_id BIGINT NULL COMMENT '货主ID' AFTER warehouse_id,
    ADD KEY idx_wms_stocktake_scope_status
        (owner_id, warehouse_id, stocktake_status, updated_at);

ALTER TABLE wms_warehouse_exception
    ADD COLUMN warehouse_id BIGINT NULL COMMENT '仓库ID' AFTER exception_no,
    ADD COLUMN owner_id BIGINT NULL COMMENT '货主ID' AFTER warehouse_id,
    ADD KEY idx_wms_exception_scope_status
        (owner_id, warehouse_id, exception_status, updated_at);

-- ============================================================================
-- Source: V12__wms_multitype_inbound.sql"
-- ============================================================================
alter table wms_inbound
    add column source_system varchar(32) null after source_type,
    add column inbound_type varchar(32) null after source_system,
    add column source_line_no varchar(64) null after source_order_no,
    add column allowed_qty decimal(18,6) null after owner_id;

update wms_inbound
set inbound_type = case
        when source_type in ('INVENTORY_TRANSFER', 'STOCK_TRANSFER', 'TRANSFER') then 'TRANSFER'
        when source_type in ('AFTERSALE_RETURN', 'AFTER_SALE_RETURN', 'SALES_RETURN', 'RETURN') then 'SALES_RETURN'
        else 'PURCHASE'
    end,
    source_system = case
        when source_type in ('INVENTORY_TRANSFER', 'STOCK_TRANSFER', 'TRANSFER') then 'INVENTORY'
        when source_type in ('AFTERSALE_RETURN', 'AFTER_SALE_RETURN', 'SALES_RETURN', 'RETURN') then 'OMS'
        when source_type = 'SUPPLIER' then 'SUPPLIER'
        else 'PURCHASE'
    end,
    source_line_no = '0',
    allowed_qty = 1
where source_system is null;

alter table wms_inbound
    modify source_system varchar(32) not null,
    modify inbound_type varchar(32) not null,
    modify source_line_no varchar(64) not null,
    modify allowed_qty decimal(18,6) not null,
    drop index uk_wms_inbound_source,
    add unique key uk_wms_inbound_source(source_system, source_order_no, source_line_no, inbound_type);

-- ============================================================================
-- Source: V13__wms_dubbo_collaboration.sql"
-- ============================================================================
CREATE TABLE wms_dubbo_receipt (
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    reference_no VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (idempotency_key)
);

CREATE TABLE wms_supplier_appointment (
    asn_id BIGINT NOT NULL,
    appointment_no VARCHAR(64) NOT NULL,
    asn_no VARCHAR(64) NOT NULL,
    supplier_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    appointment_status TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (asn_id),
    UNIQUE KEY uk_wms_supplier_appointment_no (appointment_no)
);

CREATE TABLE wms_supplier_appointment_line (
    asn_id BIGINT NOT NULL,
    source_line_no VARCHAR(64) NOT NULL,
    inbound_order_id BIGINT NOT NULL,
    inbound_order_version INT NOT NULL,
    PRIMARY KEY (asn_id, source_line_no),
    UNIQUE KEY uk_wms_supplier_appointment_inbound (inbound_order_id)
);

SET FOREIGN_KEY_CHECKS = 1;

