-- BMS service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__bms_core.sql"
-- ============================================================================
create table bms_billing_object (
    id bigint primary key auto_increment,
    object_code varchar(64) not null,
    object_name varchar(128) not null,
    object_type varchar(32) not null,
    direction varchar(16) not null,
    currency varchar(16) not null,
    status int not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_billing_object_code (object_code)
);

create table bms_billing_rule (
    id bigint primary key auto_increment,
    rule_no varchar(64) not null,
    object_code varchar(64) not null,
    fee_type varchar(64) not null,
    unit_price decimal(18,4) not null,
    tax_rate decimal(8,4) not null,
    effective_from date not null,
    effective_to date not null,
    status int not null,
    rule_version int not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_billing_rule_no (rule_no),
    key idx_bms_billing_rule_object_fee (object_code, fee_type, status)
);

create table bms_charge_source (
    id bigint primary key auto_increment,
    source_no varchar(64) not null,
    source_system varchar(64) not null,
    source_event_id varchar(128) not null,
    idempotency_key varchar(128) not null,
    billing_object_code varchar(64) not null,
    fee_type varchar(64) not null,
    quantity decimal(18,4) not null,
    billing_period varchar(16) not null,
    payload text not null,
    status int not null,
    failure_reason varchar(512),
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_charge_source_no (source_no),
    unique key uk_bms_charge_source_idem (source_system, idempotency_key),
    key idx_bms_charge_source_event (source_system, source_event_id)
);

create table bms_charge_detail (
    id bigint primary key auto_increment,
    charge_no varchar(64) not null,
    source_no varchar(64) not null,
    billing_object_code varchar(64) not null,
    fee_type varchar(64) not null,
    rule_no varchar(64) not null,
    quantity decimal(18,4) not null,
    unit_price decimal(18,4) not null,
    amount decimal(18,2) not null,
    tax_amount decimal(18,2) not null,
    total_amount decimal(18,2) not null,
    billing_period varchar(16) not null,
    status int not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_charge_detail_no (charge_no),
    key idx_bms_charge_detail_source (source_no),
    key idx_bms_charge_detail_period (billing_object_code, billing_period, status)
);

create table bms_adjustment (
    id bigint primary key auto_increment,
    adjustment_no varchar(64) not null,
    original_charge_no varchar(64) not null,
    adjust_amount decimal(18,2) not null,
    reason varchar(512) not null,
    status int not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_adjustment_no (adjustment_no)
);

create table bms_reconciliation (
    id bigint primary key auto_increment,
    reconciliation_no varchar(64) not null,
    billing_object_code varchar(64) not null,
    billing_period varchar(16) not null,
    total_amount decimal(18,2) not null,
    status int not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_reconciliation_no (reconciliation_no),
    key idx_bms_reconciliation_object_period (billing_object_code, billing_period)
);

create table bms_bill (
    id bigint primary key auto_increment,
    bill_no varchar(64) not null,
    reconciliation_no varchar(64) not null,
    billing_object_code varchar(64) not null,
    total_amount decimal(18,2) not null,
    status int not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_bill_no (bill_no),
    key idx_bms_bill_reconciliation (reconciliation_no)
);

create table bms_invoice (
    id bigint primary key auto_increment,
    invoice_no varchar(64) not null,
    bill_no varchar(64) not null,
    invoice_amount decimal(18,2) not null,
    status int not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_invoice_no (invoice_no),
    key idx_bms_invoice_bill (bill_no)
);

create table bms_finance_handover (
    id bigint primary key auto_increment,
    handover_no varchar(64) not null,
    bill_no varchar(64) not null,
    status int not null,
    voucher_no varchar(128),
    failure_reason varchar(512),
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_finance_handover_no (handover_no),
    key idx_bms_finance_handover_bill (bill_no)
);

create table bms_refund_settlement (
    id bigint primary key auto_increment,
    refund_no varchar(64) not null,
    bill_no varchar(64) not null,
    refund_amount decimal(18,2) not null,
    status int not null,
    failure_reason varchar(512),
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_refund_no (refund_no),
    key idx_bms_refund_bill (bill_no)
);

create table bms_domain_event (
    id bigint primary key auto_increment,
    event_no varchar(64) not null,
    event_type varchar(128) not null,
    aggregate_no varchar(64) not null,
    business_no varchar(64) not null,
    payload text not null,
    status int not null,
    created_at datetime(3) not null,
    unique key uk_bms_event_no (event_no),
    key idx_bms_event_status (status, id)
);

create table bms_event_consume_log (
    id bigint primary key auto_increment,
    inbox_no varchar(64) not null,
    source_system varchar(64) not null,
    source_event_id varchar(128) not null,
    event_type varchar(128) not null,
    business_no varchar(64) not null,
    payload text not null,
    status int not null,
    failure_reason varchar(512),
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_inbox_source_event (source_system, source_event_id),
    unique key uk_bms_inbox_no (inbox_no)
);

create table bms_operation_audit_log (
    id bigint primary key auto_increment,
    operation_type varchar(128) not null,
    business_no varchar(64) not null,
    operator_id bigint,
    idempotency_key varchar(128),
    created_at datetime(3) not null,
    key idx_bms_operation_business (business_no)
);

-- ============================================================================
-- Source: V2__bms_refund_receipt.sql"
-- ============================================================================
create table bms_refund_receipt (
  id bigint primary key auto_increment,
  receipt_no varchar(128) not null,
  refund_no varchar(64) not null,
  receipt_status varchar(32) not null,
  payload text,
  created_at datetime(3) not null,
  unique key uk_bms_refund_receipt_no(receipt_no),
  key idx_bms_refund_receipt_refund(refund_no,created_at)
);

-- ============================================================================
-- Source: V3__bms_external_financial_tasks.sql"
-- ============================================================================
create table bms_external_task (
    id bigint primary key auto_increment,
    task_no varchar(64) not null,
    task_type varchar(32) not null,
    business_no varchar(64) not null,
    idempotency_key varchar(128) not null,
    status tinyint not null,
    attempt_count int not null default 0,
    max_attempts int not null,
    next_retry_at datetime(3) null,
    last_error varchar(500) null,
    external_ref varchar(128) null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_external_task_no (task_no),
    unique key uk_bms_external_task_idem (idempotency_key),
    key idx_bms_external_task_dispatch (status,next_retry_at,id),
    key idx_bms_external_task_business (task_type,business_no)
);

-- ============================================================================
-- Source: V4__bms_rocketmq_delivery.sql"
-- ============================================================================
alter table bms_domain_event
    add column retry_count int not null default 0 after status,
    add column last_error varchar(1000) null after retry_count,
    add column next_retry_at datetime(3) null after last_error,
    add column published_at datetime(3) null after next_retry_at,
    add column updated_at datetime(3) null after created_at,
    add key idx_bms_event_retry (status,next_retry_at,id);

update bms_domain_event set updated_at=created_at where updated_at is null;

-- ============================================================================
-- Source: V5__bms_report_export.sql"
-- ============================================================================
create table bms_report_export (
    id bigint primary key auto_increment,
    export_no varchar(64) not null,
    billing_object_code varchar(64) not null,
    billing_period varchar(16) not null,
    idempotency_key varchar(128) not null,
    export_status tinyint not null,
    attempt_count int not null default 0,
    max_attempts int not null,
    next_retry_at datetime(3) null,
    object_reference varchar(500) null,
    record_count bigint not null default 0,
    last_error varchar(500) null,
    operator_id bigint not null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_report_export_no (export_no),
    unique key uk_bms_report_export_idem (idempotency_key),
    key idx_bms_report_export_dispatch (export_status,next_retry_at,id),
    key idx_bms_report_export_scope (billing_object_code,billing_period,created_at)
);

-- ============================================================================
-- Source: V6__bms_refund_settlement_hardening.sql"
-- ============================================================================
alter table bms_refund_settlement
  add column after_sale_no varchar(64) null after bill_no,
  add column payment_no varchar(64) null after after_sale_no,
  add column currency varchar(8) not null default 'CNY' after refund_amount,
  add column merchant_no varchar(64) not null default 'DEFAULT' after currency,
  add column request_idempotency_key varchar(128) null after merchant_no,
  add column request_digest varchar(256) null after request_idempotency_key,
  add column attempt_no int not null default 1 after request_digest,
  add column evidence_ref varchar(256) null after failure_reason,
  add column reviewer_id bigint null after evidence_ref;

update bms_refund_settlement
set request_idempotency_key = concat('legacy:', refund_no),
    request_digest = concat(bill_no, '|', refund_amount)
where request_idempotency_key is null;

alter table bms_refund_settlement
  modify request_idempotency_key varchar(128) not null,
  modify request_digest varchar(256) not null,
  add unique key uk_bms_refund_request_idempotency (request_idempotency_key),
  add key idx_bms_refund_occupation (bill_no, status);

alter table bms_refund_receipt
  add column refund_amount decimal(18,2) null after receipt_status,
  add column currency varchar(8) null after refund_amount,
  add column merchant_no varchar(64) null after currency,
  add column payment_txn_no varchar(128) null after merchant_no,
  add column failure_reason varchar(512) null after payment_txn_no;

create table bms_refund_exception (
  id bigint primary key auto_increment,
  refund_no varchar(64) not null,
  receipt_no varchar(128),
  exception_type varchar(64) not null,
  detail varchar(512) not null,
  payload text,
  status int not null,
  created_at datetime(3) not null,
  key idx_bms_refund_exception_status (status, created_at),
  key idx_bms_refund_exception_refund (refund_no, created_at)
);

-- ============================================================================
-- Source: V7__bms_dubbo_supplier_return_settlement.sql"
-- ============================================================================
CREATE TABLE bms_supplier_return_settlement (
    settlement_ref VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    return_id BIGINT NOT NULL,
    return_no VARCHAR(64) NOT NULL,
    supplier_id BIGINT NOT NULL,
    offset_amount DECIMAL(18,2) NOT NULL,
    claim_amount DECIMAL(18,2) NOT NULL,
    settlement_reason VARCHAR(500) NOT NULL,
    settlement_status TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (settlement_ref),
    UNIQUE KEY uk_bms_return_settlement_idempotency (idempotency_key),
    UNIQUE KEY uk_bms_return_settlement_return (return_id)
);

SET FOREIGN_KEY_CHECKS = 1;

