-- TMS系统 数据库 DDL
-- 口径：MySQL 8.0 / InnoDB / utf8mb4

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `tms_enum_type` (
  `enum_type_id` bigint NOT NULL COMMENT '枚举类型ID',
  `enum_type_code` varchar(64) NOT NULL COMMENT '枚举类型编码',
  `enum_type_name` varchar(128) NOT NULL COMMENT '枚举类型名称',
  `configurable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否允许页面配置显示名、排序、颜色和启停用',
  `status` smallint NOT NULL DEFAULT 1 COMMENT '状态：1启用 2停用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`enum_type_id`),
  UNIQUE KEY `uk_tms_enum_type_code` (`enum_type_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='TMS枚举类型';

CREATE TABLE `tms_enum_item` (
  `enum_item_id` bigint NOT NULL COMMENT '枚举项ID',
  `enum_type_code` varchar(64) NOT NULL COMMENT '枚举类型编码',
  `enum_value` smallint NOT NULL COMMENT '枚举数值，从1开始',
  `enum_label` varchar(128) NOT NULL COMMENT '枚举显示名',
  `sort_no` int NOT NULL DEFAULT 0 COMMENT '排序',
  `status` smallint NOT NULL DEFAULT 1 COMMENT '状态：1启用 2停用',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`enum_item_id`),
  UNIQUE KEY `uk_tms_enum_item` (`enum_type_code`, `enum_value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='TMS枚举项';

CREATE TABLE `tms_transport_task` (
  `transport_task_id` bigint NOT NULL COMMENT '运输任务ID',
  `transport_task_no` varchar(64) NOT NULL COMMENT '运输任务号',
  `source_system` smallint NOT NULL COMMENT '来源系统：1 OMS 2 WMS 3 采购 4 供应商 5 中央库存 6 人工',
  `source_order_no` varchar(64) NOT NULL COMMENT '来源单号',
  `source_order_type` smallint NOT NULL COMMENT '来源单类型：1销售出库 2销售退货 3采购到货 4退供应商 5调拨',
  `transport_scenario` smallint NOT NULL COMMENT '运输场景：1采购到货 2销售发货 3销售退货 4退供应商 5调拨运输',
  `task_status` smallint NOT NULL COMMENT '任务状态：1待接单 2已接单 3已创建运单 4运输中 5已签收 6已拒收 7已取消 8异常中',
  `carrier_id` bigint NULL COMMENT '物流商ID',
  `carrier_code` varchar(64) NULL COMMENT '物流商编码',
  `logistics_product_code` varchar(64) NULL COMMENT '物流产品编码',
  `shipper_name` varchar(128) NOT NULL COMMENT '发货方名称',
  `shipper_phone` varchar(64) NULL COMMENT '发货方电话',
  `shipper_address` varchar(512) NOT NULL COMMENT '发货地址',
  `receiver_name` varchar(128) NOT NULL COMMENT '收货方名称',
  `receiver_phone` varchar(64) NULL COMMENT '收货方电话',
  `receiver_address` varchar(512) NOT NULL COMMENT '收货地址',
  `package_count` int NOT NULL DEFAULT 0 COMMENT '包裹数',
  `total_weight` decimal(18,4) NULL COMMENT '总重量',
  `total_volume` decimal(18,4) NULL COMMENT '总体积',
  `expected_ship_at` datetime NULL COMMENT '预计发货时间',
  `expected_arrive_at` datetime NULL COMMENT '预计到达时间',
  `accepted_at` datetime NULL COMMENT '接单时间',
  `cancel_reason` varchar(512) NULL COMMENT '取消原因',
  `remark` varchar(512) NULL COMMENT '备注',
  `tenant_id` bigint NULL COMMENT '租户ID',
  `org_id` bigint NULL COMMENT '组织ID',
  `owner_id` bigint NULL COMMENT '货主ID',
  `warehouse_id` bigint NULL COMMENT '仓库ID',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '数据版本',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`transport_task_id`),
  UNIQUE KEY `uk_tms_transport_task_no` (`transport_task_no`),
  UNIQUE KEY `uk_tms_transport_task_source` (`source_system`, `source_order_no`, `transport_scenario`),
  KEY `idx_tms_transport_task_status_time` (`task_status`, `updated_at`),
  KEY `idx_tms_transport_task_scope` (`org_id`, `warehouse_id`, `owner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='运输任务';

CREATE TABLE `tms_waybill` (
  `waybill_id` bigint NOT NULL COMMENT '运单ID',
  `waybill_no` varchar(64) NOT NULL COMMENT 'TMS运单号',
  `transport_task_id` bigint NULL COMMENT '运输任务ID',
  `transport_task_no` varchar(64) NULL COMMENT '运输任务号',
  `carrier_id` bigint NOT NULL COMMENT '物流商ID',
  `carrier_code` varchar(64) NOT NULL COMMENT '物流商编码',
  `carrier_waybill_no` varchar(128) NULL COMMENT '承运商单号',
  `logistics_product_code` varchar(64) NULL COMMENT '物流产品编码',
  `source_system` smallint NOT NULL COMMENT '来源系统',
  `source_order_no` varchar(64) NOT NULL COMMENT '来源单号',
  `transport_scenario` smallint NOT NULL COMMENT '运输场景',
  `waybill_status` smallint NOT NULL COMMENT '运单状态：1待下单 2已下单 3已揽收 4运输中 5已到达 6已签收 7已拒收 8已取消 9异常中',
  `latest_track_desc` varchar(512) NULL COMMENT '最新轨迹描述',
  `latest_track_at` datetime NULL COMMENT '最新轨迹时间',
  `shipper_address` varchar(512) NOT NULL COMMENT '发货地址快照',
  `receiver_address` varchar(512) NOT NULL COMMENT '收货地址快照',
  `package_count` int NOT NULL DEFAULT 0 COMMENT '包裹数',
  `charge_weight` decimal(18,4) NULL COMMENT '计费重量',
  `total_weight` decimal(18,4) NULL COMMENT '总重量',
  `total_volume` decimal(18,4) NULL COMMENT '总体积',
  `ordered_at` datetime NULL COMMENT '承运商下单时间',
  `pickup_at` datetime NULL COMMENT '揽收时间',
  `shipped_at` datetime NULL COMMENT '发货时间',
  `arrived_at` datetime NULL COMMENT '到达时间',
  `signed_at` datetime NULL COMMENT '签收时间',
  `cancelled_at` datetime NULL COMMENT '取消时间',
  `cancel_reason` varchar(512) NULL COMMENT '取消原因',
  `exception_flag` tinyint NOT NULL DEFAULT 0 COMMENT '是否存在未关闭异常',
  `fee_source_status` smallint NOT NULL DEFAULT 1 COMMENT '费用来源状态：1待生成 2已生成 3已推送 4推送失败 5已作废 6已采集 7对账差异 8已修正',
  `tenant_id` bigint NULL COMMENT '租户ID',
  `org_id` bigint NULL COMMENT '组织ID',
  `owner_id` bigint NULL COMMENT '货主ID',
  `warehouse_id` bigint NULL COMMENT '仓库ID',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '数据版本',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`waybill_id`),
  UNIQUE KEY `uk_tms_waybill_no` (`waybill_no`),
  UNIQUE KEY `uk_tms_waybill_carrier_no` (`carrier_code`, `carrier_waybill_no`),
  KEY `idx_tms_waybill_source` (`source_system`, `source_order_no`),
  KEY `idx_tms_waybill_status_time` (`waybill_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='运单';

CREATE TABLE `tms_waybill_package` (
  `package_id` bigint NOT NULL COMMENT '包裹ID',
  `package_no` varchar(64) NOT NULL COMMENT 'TMS包裹号',
  `waybill_id` bigint NOT NULL COMMENT '运单ID',
  `waybill_no` varchar(64) NOT NULL COMMENT '运单号',
  `external_package_no` varchar(128) NULL COMMENT '来源系统包裹号',
  `package_status` smallint NOT NULL COMMENT '包裹状态：1待面单 2已生成面单 3已打印 4已交接 5已取消',
  `weight` decimal(18,4) NULL COMMENT '实重',
  `volume` decimal(18,4) NULL COMMENT '体积',
  `length_cm` decimal(18,4) NULL COMMENT '长',
  `width_cm` decimal(18,4) NULL COMMENT '宽',
  `height_cm` decimal(18,4) NULL COMMENT '高',
  `label_id` bigint NULL COMMENT '面单ID',
  `label_no` varchar(64) NULL COMMENT '面单号',
  `handover_batch_no` varchar(64) NULL COMMENT '交接批次',
  `handover_at` datetime NULL COMMENT '交接时间',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '数据版本',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`package_id`),
  UNIQUE KEY `uk_tms_waybill_package_no` (`package_no`),
  KEY `idx_tms_waybill_package_waybill` (`waybill_id`),
  KEY `idx_tms_waybill_package_status_time` (`package_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='运单包裹';

CREATE TABLE `tms_shipping_label` (
  `label_id` bigint NOT NULL COMMENT '面单ID',
  `label_no` varchar(64) NOT NULL COMMENT 'TMS面单号',
  `waybill_id` bigint NOT NULL COMMENT '运单ID',
  `waybill_no` varchar(64) NOT NULL COMMENT '运单号',
  `package_no` varchar(64) NULL COMMENT '包裹号',
  `carrier_code` varchar(64) NOT NULL COMMENT '物流商编码',
  `carrier_waybill_no` varchar(128) NULL COMMENT '承运商单号',
  `label_status` smallint NOT NULL COMMENT '面单状态：1待生成 2已生成 3已打印 4已作废 5生成失败',
  `label_url` varchar(512) NULL COMMENT '面单文件地址',
  `label_data_json` json NULL COMMENT '面单原始数据',
  `print_count` int NOT NULL DEFAULT 0 COMMENT '打印次数',
  `last_printed_by` bigint NULL COMMENT '最后打印人',
  `last_printed_at` datetime NULL COMMENT '最后打印时间',
  `void_reason` varchar(512) NULL COMMENT '作废原因',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '数据版本',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`label_id`),
  UNIQUE KEY `uk_tms_shipping_label_no` (`label_no`),
  KEY `idx_tms_shipping_label_waybill` (`waybill_id`),
  KEY `idx_tms_shipping_label_status_time` (`label_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='面单';

CREATE TABLE `tms_tracking_event` (
  `tracking_event_id` bigint NOT NULL COMMENT '轨迹ID',
  `waybill_id` bigint NOT NULL COMMENT '运单ID',
  `waybill_no` varchar(64) NOT NULL COMMENT '运单号',
  `carrier_code` varchar(64) NOT NULL COMMENT '物流商编码',
  `carrier_waybill_no` varchar(128) NULL COMMENT '承运商单号',
  `track_node` smallint NOT NULL COMMENT '轨迹节点：1下单 2揽收 3发出 4到达 5派送 6签收 7拒收 8异常',
  `track_desc` varchar(512) NOT NULL COMMENT '轨迹描述',
  `track_location` varchar(256) NULL COMMENT '轨迹地点',
  `track_at` datetime NOT NULL COMMENT '轨迹发生时间',
  `sync_source` smallint NOT NULL COMMENT '同步来源：1承运商回调 2主动拉取 3人工补录',
  `raw_payload_json` json NULL COMMENT '原始报文',
  `idempotent_key` varchar(256) NOT NULL COMMENT '幂等键',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`tracking_event_id`),
  UNIQUE KEY `uk_tms_tracking_event_idem` (`idempotent_key`),
  KEY `idx_tms_tracking_event_waybill_time` (`waybill_id`, `track_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='物流轨迹';

CREATE TABLE `tms_delivery_receipt` (
  `receipt_id` bigint NOT NULL COMMENT '签收回单ID',
  `receipt_no` varchar(64) NOT NULL COMMENT '签收回单号',
  `waybill_id` bigint NOT NULL COMMENT '运单ID',
  `waybill_no` varchar(64) NOT NULL COMMENT '运单号',
  `receipt_result` smallint NOT NULL COMMENT '签收结果：1已签收 2已拒收 3部分签收 4签收冲突',
  `signed_by` varchar(128) NULL COMMENT '签收人',
  `signed_at` datetime NULL COMMENT '签收时间',
  `reject_reason` varchar(512) NULL COMMENT '拒收原因',
  `proof_url` varchar(512) NULL COMMENT '签收证明',
  `corrected_flag` tinyint NOT NULL DEFAULT 0 COMMENT '是否修正过',
  `correct_reason` varchar(512) NULL COMMENT '修正原因',
  `notified_source_status` smallint NOT NULL DEFAULT 1 COMMENT '通知来源系统状态：1待通知 2已通知 3通知失败',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '数据版本',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`receipt_id`),
  UNIQUE KEY `uk_tms_delivery_receipt_no` (`receipt_no`),
  KEY `idx_tms_delivery_receipt_waybill` (`waybill_id`),
  KEY `idx_tms_delivery_receipt_result_time` (`receipt_result`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='签收回单';

CREATE TABLE `tms_logistics_exception` (
  `exception_id` bigint NOT NULL COMMENT '异常ID',
  `exception_no` varchar(64) NOT NULL COMMENT '异常单号',
  `waybill_id` bigint NOT NULL COMMENT '运单ID',
  `waybill_no` varchar(64) NOT NULL COMMENT '运单号',
  `source_order_no` varchar(64) NULL COMMENT '来源单号',
  `exception_type` smallint NOT NULL COMMENT '异常类型：1延误 2破损 3丢失 4拒收 5接口失败 6费用异常',
  `exception_level` smallint NOT NULL COMMENT '异常等级：1一般 2严重 3紧急',
  `responsible_party` smallint NULL COMMENT '责任方：1物流商 2仓库 3客户 4供应商 5系统',
  `exception_status` smallint NOT NULL COMMENT '异常状态：1已创建 2处理中 3已升级 4已关闭',
  `description` varchar(1024) NULL COMMENT '异常说明',
  `handler_id` bigint NULL COMMENT '当前处理人',
  `handle_result` varchar(1024) NULL COMMENT '处理结果',
  `fee_impact_flag` tinyint NOT NULL DEFAULT 0 COMMENT '是否影响费用',
  `closed_at` datetime NULL COMMENT '关闭时间',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '数据版本',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`exception_id`),
  UNIQUE KEY `uk_tms_logistics_exception_no` (`exception_no`),
  KEY `idx_tms_logistics_exception_waybill` (`waybill_id`),
  KEY `idx_tms_logistics_exception_status_time` (`exception_status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='物流异常';

CREATE TABLE `tms_fee_source` (
  `fee_source_id` bigint NOT NULL COMMENT '费用来源ID',
  `fee_source_no` varchar(64) NOT NULL COMMENT '费用来源号',
  `waybill_id` bigint NOT NULL COMMENT '运单ID',
  `waybill_no` varchar(64) NOT NULL COMMENT '运单号',
  `carrier_id` bigint NOT NULL COMMENT '物流商ID',
  `carrier_code` varchar(64) NOT NULL COMMENT '物流商编码',
  `source_order_no` varchar(64) NULL COMMENT '来源单号',
  `transport_scenario` smallint NOT NULL COMMENT '运输场景',
  `fee_source_status` smallint NOT NULL COMMENT '费用来源状态：1待生成 2已生成 3已推送 4推送失败 5已作废',
  `settlement_direction` smallint NOT NULL COMMENT '结算方向：1应付 2应收',
  `charge_weight` decimal(18,4) NULL COMMENT '计费重量',
  `base_fee` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '基础运费',
  `extra_fee` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '附加费',
  `deduction_fee` decimal(18,2) NOT NULL DEFAULT 0 COMMENT '扣罚金额',
  `total_amount` decimal(18,2) NOT NULL COMMENT '总金额',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `fee_items_json` json NULL COMMENT '费用项明细',
  `generated_at` datetime NULL COMMENT '生成时间',
  `pushed_at` datetime NULL COMMENT '推送BMS时间',
  `bms_receive_no` varchar(64) NULL COMMENT 'BMS接收编号',
  `bms_collected_at` datetime NULL COMMENT 'BMS采集时间',
  `bms_billing_item_no` varchar(64) NULL COMMENT 'BMS费用明细号',
  `reconciliation_status` smallint NULL COMMENT '对账状态：1未对账 2对账中 3已确认 4对账差异',
  `correction_version` int NOT NULL DEFAULT 0 COMMENT '修正版本',
  `correction_reason` varchar(512) NULL COMMENT '修正原因',
  `approval_id` bigint NULL COMMENT '权限审批实例ID',
  `push_fail_reason` varchar(1024) NULL COMMENT '推送失败原因',
  `created_by` bigint NOT NULL COMMENT '创建人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` bigint NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '数据版本',
  `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`fee_source_id`),
  UNIQUE KEY `uk_tms_fee_source_no` (`fee_source_no`),
  UNIQUE KEY `uk_tms_fee_source_waybill` (`waybill_id`),
  KEY `idx_tms_fee_source_status_time` (`fee_source_status`, `updated_at`),
  KEY `idx_tms_fee_source_carrier` (`carrier_id`, `generated_at`),
  KEY `idx_tms_fee_source_bms` (`bms_receive_no`, `bms_billing_item_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='物流费用来源';

CREATE TABLE `tms_carrier_integration_log` (
  `integration_log_id` bigint NOT NULL COMMENT '承运商接口日志ID',
  `carrier_code` varchar(64) NOT NULL COMMENT '物流商编码',
  `interface_type` smallint NOT NULL COMMENT '接口类型：1下单 2取消 3面单 4轨迹同步 5回调 6费用',
  `biz_no` varchar(128) NULL COMMENT '业务单号',
  `request_id` varchar(128) NULL COMMENT '请求ID',
  `request_payload` json NULL COMMENT '请求报文',
  `response_payload` json NULL COMMENT '响应报文',
  `call_status` smallint NOT NULL COMMENT '调用状态：1成功 2失败',
  `http_status` int NULL COMMENT 'HTTP状态码',
  `fail_reason` varchar(1024) NULL COMMENT '失败原因',
  `called_at` datetime NOT NULL COMMENT '调用时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`integration_log_id`),
  KEY `idx_tms_carrier_integration_biz` (`biz_no`, `interface_type`),
  KEY `idx_tms_carrier_integration_time` (`carrier_code`, `called_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='承运商接口日志';

CREATE TABLE `tms_domain_event` (
  `event_id` bigint NOT NULL COMMENT '事件ID',
  `event_code` varchar(128) NOT NULL COMMENT '事件编码',
  `event_name` varchar(128) NOT NULL COMMENT '事件名称',
  `event_type` varchar(128) NOT NULL COMMENT '事件类型',
  `aggregate_type` varchar(128) NOT NULL COMMENT '聚合类型',
  `aggregate_id` bigint NOT NULL COMMENT '聚合ID',
  `aggregate_no` varchar(128) NULL COMMENT '业务单号或编码',
  `source_system` varchar(64) NOT NULL COMMENT '来源系统',
  `payload_json` json NOT NULL COMMENT '事件载荷',
  `event_status` smallint NOT NULL DEFAULT 1 COMMENT '事件状态：1待发布 2发布中 3已发布 4发布失败 5已取消',
  `retry_count` int NOT NULL DEFAULT 0 COMMENT '重试次数',
  `fail_reason` varchar(1024) NULL COMMENT '失败原因',
  `occurred_at` datetime NOT NULL COMMENT '业务发生时间',
  `published_at` datetime NULL COMMENT '发布时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `uk_tms_domain_event_code` (`event_code`),
  KEY `idx_tms_domain_event_status` (`event_status`, `created_at`),
  KEY `idx_tms_domain_event_aggregate` (`aggregate_type`, `aggregate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='TMS领域事件发布表';

CREATE TABLE `tms_event_consume_log` (
  `consume_log_id` bigint NOT NULL COMMENT '消费日志ID',
  `event_code` varchar(128) NOT NULL COMMENT '事件编码',
  `source_system` varchar(64) NOT NULL COMMENT '来源系统',
  `consumer_name` varchar(128) NOT NULL COMMENT '消费者名称',
  `idempotent_key` varchar(256) NOT NULL COMMENT '幂等键',
  `consume_status` smallint NOT NULL DEFAULT 1 COMMENT '消费状态：1待消费 2处理中 3消费成功 4消费失败 5已忽略',
  `retry_count` int NOT NULL DEFAULT 0 COMMENT '重试次数',
  `fail_reason` varchar(1024) NULL COMMENT '失败原因',
  `consumed_at` datetime NULL COMMENT '消费完成时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`consume_log_id`),
  UNIQUE KEY `uk_tms_event_consume` (`source_system`, `event_code`, `consumer_name`),
  UNIQUE KEY `uk_tms_event_consume_idem` (`idempotent_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='TMS事件消费日志';

CREATE TABLE `tms_operation_audit_log` (
  `operation_log_id` bigint NOT NULL COMMENT '操作日志ID',
  `operator_id` bigint NOT NULL COMMENT '操作人ID',
  `operator_name` varchar(128) NULL COMMENT '操作人名称',
  `operation_type` varchar(64) NOT NULL COMMENT '操作类型',
  `target_type` varchar(128) NOT NULL COMMENT '操作对象类型',
  `target_id` bigint NULL COMMENT '操作对象ID',
  `target_no` varchar(128) NULL COMMENT '操作对象单号或编码',
  `approval_id` bigint NULL COMMENT '权限审批实例ID',
  `reason` varchar(512) NULL COMMENT '操作原因',
  `before_snapshot` json NULL COMMENT '操作前快照',
  `after_snapshot` json NULL COMMENT '操作后快照',
  `result` smallint NOT NULL COMMENT '结果：1成功 2失败',
  `fail_reason` varchar(1024) NULL COMMENT '失败原因',
  `request_id` varchar(128) NULL COMMENT '请求ID',
  `operation_at` datetime NOT NULL COMMENT '操作时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`operation_log_id`),
  KEY `idx_tms_operation_audit_target` (`target_type`, `target_no`),
  KEY `idx_tms_operation_audit_operator` (`operator_id`, `operation_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='TMS操作审计日志';

INSERT INTO `tms_enum_type` (`enum_type_id`, `enum_type_code`, `enum_type_name`, `configurable`, `status`) VALUES
(9001, 'TMS_SOURCE_SYSTEM', 'TMS来源系统', 1, 1),
(9002, 'TMS_SOURCE_ORDER_TYPE', 'TMS来源单类型', 1, 1),
(9003, 'TRANSPORT_SCENARIO', '运输场景', 1, 1),
(9004, 'TRANSPORT_TASK_STATUS', '运输任务状态', 0, 1),
(9005, 'WAYBILL_STATUS', '运单状态', 0, 1),
(9006, 'PACKAGE_STATUS', '包裹状态', 0, 1),
(9007, 'LABEL_STATUS', '面单状态', 0, 1),
(9008, 'TRACK_NODE', '轨迹节点', 1, 1),
(9009, 'TRACK_SYNC_SOURCE', '轨迹同步来源', 1, 1),
(9010, 'RECEIPT_RESULT', '签收结果', 0, 1),
(9011, 'LOGISTICS_EXCEPTION_TYPE', '物流异常类型', 1, 1),
(9012, 'EXCEPTION_LEVEL', '异常等级', 1, 1),
(9013, 'EXCEPTION_STATUS', '异常状态', 0, 1),
(9014, 'RESPONSIBLE_PARTY', '责任方', 1, 1),
(9015, 'FEE_SOURCE_STATUS', '费用来源状态', 0, 1),
(9016, 'SETTLEMENT_DIRECTION', '结算方向', 1, 1),
(9017, 'NOTIFY_STATUS', '通知状态', 0, 1),
(9018, 'EVENT_STATUS', '事件状态', 0, 1),
(9019, 'CONSUME_STATUS', '消费状态', 0, 1),
(9020, 'RECONCILIATION_STATUS', '对账状态', 0, 1);

INSERT INTO `tms_enum_item` (`enum_item_id`, `enum_type_code`, `enum_value`, `enum_label`, `sort_no`, `status`) VALUES
(900101, 'TMS_SOURCE_SYSTEM', 1, 'OMS', 1, 1),
(900102, 'TMS_SOURCE_SYSTEM', 2, 'WMS', 2, 1),
(900103, 'TMS_SOURCE_SYSTEM', 3, '采购系统', 3, 1),
(900104, 'TMS_SOURCE_SYSTEM', 4, '供应商系统', 4, 1),
(900105, 'TMS_SOURCE_SYSTEM', 5, '中央库存系统', 5, 1),
(900106, 'TMS_SOURCE_SYSTEM', 6, '人工创建', 6, 1),
(900201, 'TMS_SOURCE_ORDER_TYPE', 1, '销售出库', 1, 1),
(900202, 'TMS_SOURCE_ORDER_TYPE', 2, '销售退货', 2, 1),
(900203, 'TMS_SOURCE_ORDER_TYPE', 3, '采购到货', 3, 1),
(900204, 'TMS_SOURCE_ORDER_TYPE', 4, '退供应商', 4, 1),
(900205, 'TMS_SOURCE_ORDER_TYPE', 5, '调拨', 5, 1),
(900301, 'TRANSPORT_SCENARIO', 1, '采购到货', 1, 1),
(900302, 'TRANSPORT_SCENARIO', 2, '销售发货', 2, 1),
(900303, 'TRANSPORT_SCENARIO', 3, '销售退货', 3, 1),
(900304, 'TRANSPORT_SCENARIO', 4, '退供应商', 4, 1),
(900305, 'TRANSPORT_SCENARIO', 5, '调拨运输', 5, 1),
(900401, 'TRANSPORT_TASK_STATUS', 1, '待接单', 1, 1),
(900402, 'TRANSPORT_TASK_STATUS', 2, '已接单', 2, 1),
(900403, 'TRANSPORT_TASK_STATUS', 3, '已创建运单', 3, 1),
(900404, 'TRANSPORT_TASK_STATUS', 4, '运输中', 4, 1),
(900405, 'TRANSPORT_TASK_STATUS', 5, '已签收', 5, 1),
(900406, 'TRANSPORT_TASK_STATUS', 6, '已拒收', 6, 1),
(900407, 'TRANSPORT_TASK_STATUS', 7, '已取消', 7, 1),
(900408, 'TRANSPORT_TASK_STATUS', 8, '异常中', 8, 1),
(900501, 'WAYBILL_STATUS', 1, '待下单', 1, 1),
(900502, 'WAYBILL_STATUS', 2, '已下单', 2, 1),
(900503, 'WAYBILL_STATUS', 3, '已揽收', 3, 1),
(900504, 'WAYBILL_STATUS', 4, '运输中', 4, 1),
(900505, 'WAYBILL_STATUS', 5, '已到达', 5, 1),
(900506, 'WAYBILL_STATUS', 6, '已签收', 6, 1),
(900507, 'WAYBILL_STATUS', 7, '已拒收', 7, 1),
(900508, 'WAYBILL_STATUS', 8, '已取消', 8, 1),
(900509, 'WAYBILL_STATUS', 9, '异常中', 9, 1),
(900601, 'PACKAGE_STATUS', 1, '待面单', 1, 1),
(900602, 'PACKAGE_STATUS', 2, '已生成面单', 2, 1),
(900603, 'PACKAGE_STATUS', 3, '已打印', 3, 1),
(900604, 'PACKAGE_STATUS', 4, '已交接', 4, 1),
(900605, 'PACKAGE_STATUS', 5, '已取消', 5, 1),
(900701, 'LABEL_STATUS', 1, '待生成', 1, 1),
(900702, 'LABEL_STATUS', 2, '已生成', 2, 1),
(900703, 'LABEL_STATUS', 3, '已打印', 3, 1),
(900704, 'LABEL_STATUS', 4, '已作废', 4, 1),
(900705, 'LABEL_STATUS', 5, '生成失败', 5, 1),
(900801, 'TRACK_NODE', 1, '下单', 1, 1),
(900802, 'TRACK_NODE', 2, '揽收', 2, 1),
(900803, 'TRACK_NODE', 3, '发出', 3, 1),
(900804, 'TRACK_NODE', 4, '到达', 4, 1),
(900805, 'TRACK_NODE', 5, '派送', 5, 1),
(900806, 'TRACK_NODE', 6, '签收', 6, 1),
(900807, 'TRACK_NODE', 7, '拒收', 7, 1),
(900808, 'TRACK_NODE', 8, '异常', 8, 1),
(900901, 'TRACK_SYNC_SOURCE', 1, '承运商回调', 1, 1),
(900902, 'TRACK_SYNC_SOURCE', 2, '主动拉取', 2, 1),
(900903, 'TRACK_SYNC_SOURCE', 3, '人工补录', 3, 1),
(901001, 'RECEIPT_RESULT', 1, '已签收', 1, 1),
(901002, 'RECEIPT_RESULT', 2, '已拒收', 2, 1),
(901003, 'RECEIPT_RESULT', 3, '部分签收', 3, 1),
(901004, 'RECEIPT_RESULT', 4, '签收冲突', 4, 1),
(901101, 'LOGISTICS_EXCEPTION_TYPE', 1, '延误', 1, 1),
(901102, 'LOGISTICS_EXCEPTION_TYPE', 2, '破损', 2, 1),
(901103, 'LOGISTICS_EXCEPTION_TYPE', 3, '丢失', 3, 1),
(901104, 'LOGISTICS_EXCEPTION_TYPE', 4, '拒收', 4, 1),
(901105, 'LOGISTICS_EXCEPTION_TYPE', 5, '接口失败', 5, 1),
(901106, 'LOGISTICS_EXCEPTION_TYPE', 6, '费用异常', 6, 1),
(901201, 'EXCEPTION_LEVEL', 1, '一般', 1, 1),
(901202, 'EXCEPTION_LEVEL', 2, '严重', 2, 1),
(901203, 'EXCEPTION_LEVEL', 3, '紧急', 3, 1),
(901301, 'EXCEPTION_STATUS', 1, '已创建', 1, 1),
(901302, 'EXCEPTION_STATUS', 2, '处理中', 2, 1),
(901303, 'EXCEPTION_STATUS', 3, '已升级', 3, 1),
(901304, 'EXCEPTION_STATUS', 4, '已关闭', 4, 1),
(901401, 'RESPONSIBLE_PARTY', 1, '物流商', 1, 1),
(901402, 'RESPONSIBLE_PARTY', 2, '仓库', 2, 1),
(901403, 'RESPONSIBLE_PARTY', 3, '客户', 3, 1),
(901404, 'RESPONSIBLE_PARTY', 4, '供应商', 4, 1),
(901405, 'RESPONSIBLE_PARTY', 5, '系统', 5, 1),
(901501, 'FEE_SOURCE_STATUS', 1, '待生成', 1, 1),
(901502, 'FEE_SOURCE_STATUS', 2, '已生成', 2, 1),
(901503, 'FEE_SOURCE_STATUS', 3, '已推送', 3, 1),
(901504, 'FEE_SOURCE_STATUS', 4, '推送失败', 4, 1),
(901505, 'FEE_SOURCE_STATUS', 5, '已作废', 5, 1),
(901506, 'FEE_SOURCE_STATUS', 6, '已采集', 6, 1),
(901507, 'FEE_SOURCE_STATUS', 7, '对账差异', 7, 1),
(901508, 'FEE_SOURCE_STATUS', 8, '已修正', 8, 1),
(901601, 'SETTLEMENT_DIRECTION', 1, '应付', 1, 1),
(901602, 'SETTLEMENT_DIRECTION', 2, '应收', 2, 1),
(901701, 'NOTIFY_STATUS', 1, '待通知', 1, 1),
(901702, 'NOTIFY_STATUS', 2, '已通知', 2, 1),
(901703, 'NOTIFY_STATUS', 3, '通知失败', 3, 1),
(901801, 'EVENT_STATUS', 1, '待发布', 1, 1),
(901802, 'EVENT_STATUS', 2, '发布中', 2, 1),
(901803, 'EVENT_STATUS', 3, '已发布', 3, 1),
(901804, 'EVENT_STATUS', 4, '发布失败', 4, 1),
(901805, 'EVENT_STATUS', 5, '已取消', 5, 1),
(901901, 'CONSUME_STATUS', 1, '待消费', 1, 1),
(901902, 'CONSUME_STATUS', 2, '处理中', 2, 1),
(901903, 'CONSUME_STATUS', 3, '消费成功', 3, 1),
(901904, 'CONSUME_STATUS', 4, '消费失败', 4, 1),
(901905, 'CONSUME_STATUS', 5, '已忽略', 5, 1),
(902001, 'RECONCILIATION_STATUS', 1, '未对账', 1, 1),
(902002, 'RECONCILIATION_STATUS', 2, '对账中', 2, 1),
(902003, 'RECONCILIATION_STATUS', 3, '已确认', 3, 1),
(902004, 'RECONCILIATION_STATUS', 4, '对账差异', 4, 1);

SET FOREIGN_KEY_CHECKS = 1;
