package com.chaobo.scm.supplier.domain.order;
import com.chaobo.scm.common.error.*;import java.math.BigDecimal;import java.time.LocalDate;
public final class PoConfirmLine{private final long lineId;private final String skuCode;private final BigDecimal orderQty;private final LocalDate requestedDate;private BigDecimal confirmedQty;private LocalDate confirmedDate;private int status;private String diffReason;
 public PoConfirmLine(long id,String sku,BigDecimal orderQty,LocalDate requestedDate,BigDecimal confirmedQty,LocalDate confirmedDate,int status,String diffReason){if(sku==null||sku.isBlank()||orderQty==null||orderQty.signum()<=0)throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"采购订单行不合法");this.lineId=id;this.skuCode=sku;this.orderQty=orderQty;this.requestedDate=requestedDate;this.confirmedQty=confirmedQty;this.confirmedDate=confirmedDate;this.status=status;this.diffReason=diffReason;}
 public void confirm(BigDecimal qty,LocalDate date){if(qty==null||qty.signum()<=0||qty.compareTo(orderQty)>0)throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"确认数量必须大于0且不能超过采购数量");if(date==null)throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"确认交期不能为空");confirmedQty=qty;confirmedDate=date;status=2;diffReason=null;}
 public void difference(BigDecimal qty,LocalDate date,String reason){if(reason==null||reason.isBlank())throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"差异原因不能为空");if(qty!=null&&(qty.signum()<=0||qty.compareTo(orderQty)>0))throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"差异确认数量不合法");confirmedQty=qty;confirmedDate=date;status=3;diffReason=reason;}
 public void changeDelivery(LocalDate date){if(status!=2)throw new BusinessException(ErrorCode.STATE_CONFLICT,"只有已确认订单行可以修改承诺交期");if(date==null)throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"新承诺交期不能为空");confirmedDate=date;}
 public long lineId(){return lineId;}public String skuCode(){return skuCode;}public BigDecimal orderQty(){return orderQty;}public LocalDate requestedDate(){return requestedDate;}public BigDecimal confirmedQty(){return confirmedQty;}public LocalDate confirmedDate(){return confirmedDate;}public int status(){return status;}public String diffReason(){return diffReason;}
}
