package com.chaobo.scm.supplier.domain.order;
import com.chaobo.scm.common.error.*;import com.chaobo.scm.supplier.domain.shared.*;import java.math.BigDecimal;import java.time.*;import java.util.*;
public final class PoConfirmAggregate{
 private final long confirmId,purchaseOrderId,supplierId;private final String confirmNo,purchaseOrderNo;private OffsetDateTime deadline;private final List<PoConfirmLine> lines;private PoConfirmStatus status;private OffsetDateTime confirmedAt;private Integer diffType,reasonCode;private String remark;private int sourceVersion,version;private final List<DomainEvent> events=new ArrayList<>();
 private PoConfirmAggregate(long id,String no,long poId,String poNo,long supplierId,OffsetDateTime deadline,List<PoConfirmLine> lines,PoConfirmStatus status,OffsetDateTime confirmedAt,Integer diffType,Integer reasonCode,String remark,int sourceVersion,int version){this.confirmId=id;this.confirmNo=no;this.purchaseOrderId=poId;this.purchaseOrderNo=poNo;this.supplierId=supplierId;this.deadline=deadline;this.lines=new ArrayList<>(lines);this.status=status;this.confirmedAt=confirmedAt;this.diffType=diffType;this.reasonCode=reasonCode;this.remark=remark;this.sourceVersion=sourceVersion;this.version=version;}
 public static PoConfirmAggregate receive(long poId,String poNo,long supplierId,OffsetDateTime deadline,List<NewLine> source,int sourceVersion,long operator,IdentifierGenerator ids){validateSource(poId,poNo,supplierId,source,sourceVersion);long id=ids.nextId();var aggregate=new PoConfirmAggregate(id,ids.nextBusinessNo("POC"),poId,poNo,supplierId,deadline,newLines(source,ids),PoConfirmStatus.PENDING,null,null,null,null,sourceVersion,0);aggregate.raise(ids,"PurchaseOrderConfirmTodoCreated","采购订单确认待办已创建",operator,Map.of("purchaseOrderId",poId,"supplierId",supplierId,"sourceVersion",sourceVersion));return aggregate;}
 public static PoConfirmAggregate receive(long poId,String poNo,long supplierId,OffsetDateTime deadline,List<NewLine> source,long operator,IdentifierGenerator ids){return receive(poId,poNo,supplierId,deadline,source,1,operator,ids);}
 public static PoConfirmAggregate rehydrate(long id,String no,long poId,String poNo,long supplierId,OffsetDateTime deadline,List<PoConfirmLine> lines,PoConfirmStatus status,OffsetDateTime confirmedAt,Integer diffType,Integer reasonCode,String remark,int sourceVersion,int version){return new PoConfirmAggregate(id,no,poId,poNo,supplierId,deadline,lines,status,confirmedAt,diffType,reasonCode,remark,sourceVersion,version);}
 public void applyOrderChange(OffsetDateTime newDeadline,List<NewLine> source,int newSourceVersion,long operator,IdentifierGenerator ids){ensureNewVersion(newSourceVersion);if(status==PoConfirmStatus.CLOSED||status==PoConfirmStatus.CANCELLED)throw state("终态订单不能变更");if(source==null||source.isEmpty())throw rule("变更后订单行不能为空");lines.clear();lines.addAll(newLines(source,ids));deadline=newDeadline;sourceVersion=newSourceVersion;status=PoConfirmStatus.PENDING;confirmedAt=null;diffType=null;reasonCode=null;remark="采购订单已变更，需重新确认";version++;raise(ids,"PurchaseOrderChangeReceived","采购订单变更已接收",operator,Map.of("purchaseOrderId",purchaseOrderId,"sourceVersion",sourceVersion));}
 public void cancel(int newSourceVersion,String reason,long operator,IdentifierGenerator ids){ensureNewVersion(newSourceVersion);if(status==PoConfirmStatus.CLOSED)throw state("已关闭订单不能取消");if(reason==null||reason.isBlank())throw rule("取消原因不能为空");sourceVersion=newSourceVersion;status=PoConfirmStatus.CANCELLED;remark=reason.trim();version++;raise(ids,"PurchaseOrderCancellationReceived","采购订单取消已接收",operator,Map.of("purchaseOrderId",purchaseOrderId,"reason",remark,"sourceVersion",sourceVersion));}
 public void close(int newSourceVersion,long operator,IdentifierGenerator ids){ensureNewVersion(newSourceVersion);if(status==PoConfirmStatus.CANCELLED)throw state("已取消订单不能关闭");sourceVersion=newSourceVersion;status=PoConfirmStatus.CLOSED;version++;raise(ids,"PurchaseOrderClosureReceived","采购订单关闭已接收",operator,Map.of("purchaseOrderId",purchaseOrderId,"sourceVersion",sourceVersion));}
 public void confirm(List<LineDecision> decisions,String remark,long operator,IdentifierGenerator ids){pending();if(decisions==null||decisions.size()!=lines.size())throw rule("确认必须覆盖全部采购订单行");Map<Long,LineDecision> map=new HashMap<>();decisions.forEach(value->map.put(value.lineId(),value));for(var line:lines){var decision=map.get(line.lineId());if(decision==null)throw rule("存在未确认订单行");line.confirm(decision.quantity(),decision.deliveryDate());}status=PoConfirmStatus.CONFIRMED;confirmedAt=OffsetDateTime.now();this.remark=remark;version++;raise(ids,"PurchaseOrderConfirmedBySupplier","供应商订单已确认",operator,Map.of("purchaseOrderId",purchaseOrderId,"supplierId",supplierId,"sourceVersion",sourceVersion));}
 public void reject(int reason,String remark,long operator,IdentifierGenerator ids){pending();if(reason<=0)throw rule("拒绝原因不能为空");status=PoConfirmStatus.REJECTED;reasonCode=reason;this.remark=remark;version++;raise(ids,"PurchaseOrderRejectedBySupplier","供应商订单已拒绝",operator,Map.of("purchaseOrderId",purchaseOrderId,"reasonCode",reason));}
 public void feedbackDifference(int type,List<LineDifference> differences,String remark,long operator,IdentifierGenerator ids){pending();if(type<1||type>4||differences==null||differences.isEmpty())throw rule("差异类型和差异行不能为空");for(var difference:differences)line(difference.lineId()).difference(difference.quantity(),difference.deliveryDate(),difference.reason());status=PoConfirmStatus.DIFFERENCE_PENDING;diffType=type;this.remark=remark;version++;raise(ids,"PurchaseOrderDifferenceReportedBySupplier","供应商订单差异已反馈",operator,Map.of("purchaseOrderId",purchaseOrderId,"diffType",type));}
 public void changeDelivery(long lineId,LocalDate date,String reason,long operator,IdentifierGenerator ids){if(status!=PoConfirmStatus.CONFIRMED)throw state("只有已确认订单可以修改承诺交期");if(reason==null||reason.isBlank())throw rule("修改交期原因不能为空");line(lineId).changeDelivery(date);version++;raise(ids,"SupplierPromisedDeliveryDateChanged","供应商承诺交期已变更",operator,Map.of("purchaseOrderId",purchaseOrderId,"orderLineId",lineId,"newDeliveryDate",date.toString(),"reason",reason));}
 private static List<PoConfirmLine> newLines(List<NewLine> source,IdentifierGenerator ids){var skuSet=new HashSet<String>();return source.stream().map(value->{if(!skuSet.add(value.skuCode()))throw rule("采购订单SKU重复: "+value.skuCode());return new PoConfirmLine(ids.nextId(),value.skuCode(),value.orderQty(),value.requestedDate(),null,null,1,null);}).toList();}
 private static void validateSource(long poId,String poNo,long supplierId,List<NewLine> source,int sourceVersion){if(poId<=0||supplierId<=0||poNo==null||poNo.isBlank()||source==null||source.isEmpty()||sourceVersion<=0)throw rule("采购订单确认数据不完整");}
 private void ensureNewVersion(int incoming){if(incoming<=sourceVersion)throw new BusinessException(ErrorCode.IDEMPOTENCY_CONFLICT,"采购订单事件版本已处理");}private void pending(){if(status!=PoConfirmStatus.PENDING)throw state("当前采购订单协同状态不允许该操作");if(deadline!=null&&OffsetDateTime.now().isAfter(deadline))throw rule("采购订单确认已超过截止时间");}private PoConfirmLine line(long id){return lines.stream().filter(value->value.lineId()==id).findFirst().orElseThrow(()->rule("采购订单行不存在"));}
 private void raise(IdentifierGenerator ids,String type,String name,long operator,Map<String,Object> payload){long eventId=ids.nextId();events.add(new DomainEvent(eventId,"SUP-"+eventId,type,name,"PO_CONFIRM",confirmId,confirmNo,version,operator,OffsetDateTime.now(),payload));}private static BusinessException rule(String message){return new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,message);}private static BusinessException state(String message){return new BusinessException(ErrorCode.STATE_CONFLICT,message);}
 public List<DomainEvent> pullEvents(){var copy=List.copyOf(events);events.clear();return copy;}public long confirmId(){return confirmId;}public String confirmNo(){return confirmNo;}public long purchaseOrderId(){return purchaseOrderId;}public String purchaseOrderNo(){return purchaseOrderNo;}public long supplierId(){return supplierId;}public OffsetDateTime deadline(){return deadline;}public List<PoConfirmLine> lines(){return List.copyOf(lines);}public PoConfirmStatus status(){return status;}public OffsetDateTime confirmedAt(){return confirmedAt;}public Integer diffType(){return diffType;}public Integer reasonCode(){return reasonCode;}public String remark(){return remark;}public int sourceVersion(){return sourceVersion;}public int version(){return version;}
 public record NewLine(String skuCode,BigDecimal orderQty,LocalDate requestedDate){}public record LineDecision(long lineId,BigDecimal quantity,LocalDate deliveryDate){}public record LineDifference(long lineId,BigDecimal quantity,LocalDate deliveryDate,String reason){}
}
