-- PURCHASE service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__purchase_requisition.sql"
-- ============================================================================
create table purchase_requisition (
    id bigint not null primary key,
    requisition_no varchar(64) not null,
    applicant_id bigint not null,
    purchase_org_id bigint not null,
    demand_department_id bigint not null,
    status tinyint not null comment '1草稿 2审批中 3已批准 4已驳回 5部分转采购 6已转采购 7已关闭',
    reason varchar(512) null,
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_requisition_no (requisition_no),
    key idx_purchase_requisition_org_status (purchase_org_id, status, updated_at),
    key idx_purchase_requisition_applicant (applicant_id, updated_at)
) comment '采购请购单';

create table purchase_requisition_line (
    line_id bigint not null primary key,
    requisition_id bigint not null,
    sku_code varchar(64) not null,
    requested_qty decimal(18, 6) not null,
    approved_qty decimal(18, 6) not null default 0,
    converted_qty decimal(18, 6) not null default 0,
    purchase_unit varchar(32) null,
    required_date date not null,
    remark varchar(512) null,
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_requisition_line_sku_date (requisition_id, sku_code, required_date),
    key idx_purchase_requisition_line_sku (sku_code, required_date)
) comment '采购请购单行';

create table purchase_outbox_event (
    event_id bigint not null auto_increment primary key,
    event_code varchar(128) not null,
    event_type varchar(128) not null,
    aggregate_type varchar(64) not null,
    aggregate_id varchar(64) not null,
    aggregate_version int not null,
    payload_json json not null,
    status tinyint not null comment '1待发布 2发布中 3已发布 4失败',
    retry_count int not null default 0,
    last_error varchar(1024) null,
    occurred_at datetime(3) not null,
    published_at datetime(3) null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_outbox_event_code (event_code),
    key idx_purchase_outbox_dispatch (status, retry_count, created_at)
) comment '采购系统领域事件Outbox';

create table purchase_operation_log (
    log_id bigint not null auto_increment primary key,
    request_id varchar(128) null,
    trace_id varchar(128) null,
    operator_id bigint not null,
    operator_name varchar(128) null,
    operation varchar(64) not null,
    target_type varchar(64) not null,
    target_id bigint not null,
    target_no varchar(64) not null,
    before_snapshot json null,
    after_snapshot json null,
    created_at datetime(3) not null,
    key idx_purchase_operation_target (target_type, target_id, created_at),
    key idx_purchase_operation_trace (trace_id)
) comment '采购系统操作日志';

-- ============================================================================
-- Source: V2__purchase_rfq.sql"
-- ============================================================================
create table purchase_rfq (
    id bigint not null primary key,
    rfq_no varchar(64) not null,
    rfq_type tinyint not null comment '1公开询价 2定向询价 3议价',
    purchase_org_id bigint not null,
    category_code varchar(64) null,
    source_requisition_no varchar(64) null,
    quote_deadline datetime(3) not null,
    status tinyint not null comment '1草稿 2已发布 3报价中 4已截标 5已定标 6已取消 7已关闭',
    published_at datetime(3) null,
    close_reason varchar(512) null,
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_rfq_no (rfq_no),
    key idx_purchase_rfq_org_status (purchase_org_id, status, updated_at),
    key idx_purchase_rfq_deadline (quote_deadline),
    key idx_purchase_rfq_category (category_code, status)
) comment '采购询价单';

create table purchase_rfq_line (
    line_id bigint not null primary key,
    rfq_id bigint not null,
    sku_code varchar(64) not null,
    target_qty decimal(18, 6) not null,
    uom varchar(32) not null,
    required_delivery_date date null,
    quality_requirement varchar(512) null,
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_rfq_line_sku (rfq_id, sku_code),
    key idx_purchase_rfq_line_sku (sku_code)
) comment '采购询价行';

create table purchase_rfq_invitation (
    invitation_id bigint not null primary key,
    rfq_id bigint not null,
    supplier_id bigint not null,
    quote_status tinyint not null comment '1待报价 2已报价 3已确认 4已关闭',
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_rfq_invitation_supplier (rfq_id, supplier_id),
    key idx_purchase_rfq_invitation_supplier (supplier_id, quote_status)
) comment '采购询价邀请供应商';

-- ============================================================================
-- Source: V3__comparison_and_price.sql"
-- ============================================================================
create table purchase_bid_comparison (
    id bigint not null primary key,
    compare_no varchar(64) not null,
    rfq_no varchar(64) not null,
    purchase_org_id bigint not null,
    currency varchar(16) not null,
    status tinyint not null comment '1已生成 2已定标 3已驳回',
    awarded_candidate_id bigint null,
    decision_reason varchar(512) null,
    decided_by bigint null,
    decided_at datetime(3) null,
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_bid_comparison_no (compare_no),
    key idx_purchase_bid_comparison_rfq (rfq_no),
    key idx_purchase_bid_comparison_org_status (purchase_org_id, status, updated_at)
) comment '采购比价结果';

create table purchase_bid_candidate (
    candidate_id bigint not null primary key,
    comparison_id bigint not null,
    supplier_id bigint not null,
    supplier_name varchar(128) null,
    quote_no varchar(64) not null,
    sku_code varchar(64) not null,
    quote_qty decimal(18, 6) not null,
    unit_price decimal(18, 6) not null,
    tax_rate decimal(8, 6) not null,
    delivery_days int not null,
    supplier_score decimal(10, 4) not null,
    transport_score decimal(10, 4) not null,
    estimated_freight_cost decimal(18, 6) not null,
    total_cost decimal(18, 6) not null,
    composite_score decimal(18, 6) not null,
    awarded tinyint not null default 0,
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    key idx_purchase_bid_candidate_comparison (comparison_id, composite_score),
    key idx_purchase_bid_candidate_supplier (supplier_id, sku_code)
) comment '采购比价候选报价快照';

create table purchase_price (
    id bigint not null primary key,
    price_no varchar(64) not null,
    supplier_id bigint not null,
    sku_code varchar(64) not null,
    purchase_org_id bigint not null,
    price_type tinyint not null comment '1标准价 2协议价 3临时价',
    currency varchar(16) not null,
    unit_price decimal(18, 6) not null,
    tax_rate decimal(8, 6) not null,
    tax_included_price decimal(18, 6) not null,
    effective_from date not null,
    effective_to date null,
    source_type varchar(64) null,
    source_no varchar(64) null,
    status tinyint not null comment '1启用 2停用',
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_price_no (price_no),
    key idx_purchase_price_scope (purchase_org_id, supplier_id, sku_code, currency, status),
    key idx_purchase_price_effective (effective_from, effective_to)
) comment '采购价格';

-- ============================================================================
-- Source: V4__purchase_order.sql"
-- ============================================================================
create table purchase_order (
    id bigint not null primary key,
    order_no varchar(64) not null,
    purchase_type tinyint not null,
    supplier_id bigint not null,
    supplier_code varchar(64) not null,
    supplier_name varchar(256) not null,
    purchase_org_id bigint not null,
    warehouse_code varchar(64) null,
    currency varchar(16) not null,
    total_amount decimal(18, 6) not null,
    tax_amount decimal(18, 6) not null,
    tax_included_amount decimal(18, 6) not null,
    status tinyint not null comment '1草稿 2待审批 3已审批 4待供应商确认 5供应商已确认 6供应商差异 7部分入库 8已完成 9已取消 10已关闭 11已驳回',
    version_no int not null,
    version int not null,
    released_at datetime(3) null,
    cancel_reason varchar(512) null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_order_no (order_no),
    key idx_purchase_order_org_status (purchase_org_id, status, updated_at),
    key idx_purchase_order_supplier (supplier_id, status)
) comment '采购订单';

create table purchase_order_line (
    line_id bigint not null primary key,
    order_id bigint not null,
    sku_code varchar(64) not null,
    sku_name varchar(256) null,
    order_qty decimal(18, 6) not null,
    unit_price decimal(18, 6) not null,
    tax_rate decimal(8, 6) not null,
    tax_included_price decimal(18, 6) not null,
    required_delivery_date date null,
    received_qty decimal(18, 6) not null default 0,
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_order_line_sku (order_id, sku_code),
    key idx_purchase_order_line_sku (sku_code)
) comment '采购订单行';

create table purchase_order_change (
    id bigint not null primary key,
    change_no varchar(64) not null,
    order_no varchar(64) not null,
    change_type tinyint not null comment '1数量 2价格 3交期 4取消 5关闭',
    before_snapshot json not null,
    after_snapshot json not null,
    change_reason varchar(512) not null,
    status tinyint not null comment '1待审批 2已生效 3已驳回',
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_order_change_no (change_no),
    key idx_purchase_order_change_order (order_no, status)
) comment '采购订单变更单';

-- ============================================================================
-- Source: V5__inbound_and_supplier_return.sql"
-- ============================================================================
create table purchase_inbound_tracking (
    id bigint not null primary key,
    inbound_no varchar(64) not null,
    order_no varchar(64) not null,
    asn_no varchar(64) not null,
    supplier_id bigint not null,
    purchase_org_id bigint not null,
    warehouse_code varchar(64) null,
    sku_code varchar(64) null,
    notified_qty decimal(18, 6) not null,
    received_qty decimal(18, 6) not null default 0,
    qualified_qty decimal(18, 6) not null default 0,
    unqualified_qty decimal(18, 6) not null default 0,
    putaway_qty decimal(18, 6) not null default 0,
    status tinyint not null comment '1 ASN已记录 2在途 3已到仓 4已收货 5已质检 6已上架 7异常',
    exception_reason varchar(512) null,
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_inbound_no (inbound_no),
    unique key uk_purchase_inbound_asn (asn_no),
    key idx_purchase_inbound_order (order_no, status),
    key idx_purchase_inbound_org (purchase_org_id, status)
) comment '采购到货跟踪';

create table purchase_supplier_return (
    id bigint not null primary key,
    return_no varchar(64) not null,
    source_order_no varchar(64) not null,
    supplier_id bigint not null,
    purchase_org_id bigint not null,
    warehouse_code varchar(64) null,
    status tinyint not null comment '1已创建 2待审批 3已批准 4已通知执行 5已关闭 6已驳回',
    reject_reason varchar(512) null,
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_supplier_return_no (return_no),
    key idx_purchase_supplier_return_order (source_order_no),
    key idx_purchase_supplier_return_org_status (purchase_org_id, status),
    key idx_purchase_supplier_return_supplier (supplier_id, status)
) comment '采购退供应商申请';

create table purchase_supplier_return_line (
    line_id bigint not null primary key,
    return_id bigint not null,
    sku_code varchar(64) not null,
    return_qty decimal(18, 6) not null,
    returnable_qty decimal(18, 6) not null,
    reason varchar(512) null,
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    key idx_purchase_supplier_return_line_return (return_id),
    key idx_purchase_supplier_return_line_sku (sku_code)
) comment '采购退供应商申请行';

-- ============================================================================
-- Source: V6__purchase_inbox_and_integration.sql"
-- ============================================================================
create table purchase_inbox_event (
    inbox_id bigint not null auto_increment primary key,
    source_system varchar(64) not null,
    event_code varchar(128) not null,
    event_type varchar(128) not null,
    consumer_name varchar(128) not null,
    idempotent_key varchar(256) not null,
    payload_json json not null,
    status tinyint not null comment '1处理中 2成功 3失败 4忽略',
    retry_count int not null default 0,
    last_error varchar(1024) null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_inbox_event (source_system, event_code, consumer_name),
    key idx_purchase_inbox_status (status, updated_at),
    key idx_purchase_inbox_consumer (consumer_name, status, updated_at)
) comment '采购系统入站事件收件箱';

create table purchase_integration_command (
    command_id bigint not null auto_increment primary key,
    command_type varchar(128) not null,
    target_system varchar(64) not null,
    business_type varchar(64) not null,
    business_id varchar(64) not null,
    business_no varchar(64) null,
    payload_json json not null,
    status tinyint not null comment '1待发送 2发送中 3已发送 4失败 5已取消',
    retry_count int not null default 0,
    last_error varchar(1024) null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    key idx_purchase_integration_dispatch (status, retry_count, created_at),
    key idx_purchase_integration_business (business_type, business_id)
) comment '采购系统跨系统主动命令';

-- ============================================================================
-- Source: V7__purchase_external_facts.sql"
-- ============================================================================
create table purchase_supplier_quote_fact (
    fact_id bigint not null auto_increment primary key,
    event_code varchar(128) not null,
    quote_no varchar(64) null,
    rfq_no varchar(64) null,
    supplier_id bigint not null,
    sku_code varchar(64) null,
    quote_qty decimal(18, 6) not null default 0,
    quote_amount decimal(18, 2) not null default 0,
    currency varchar(16) null,
    quote_status varchar(64) not null,
    payload_json json not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_quote_fact_event (event_code),
    key idx_purchase_quote_fact_rfq (rfq_no, supplier_id),
    key idx_purchase_quote_fact_supplier (supplier_id, quote_status)
) comment '采购系统供应商报价事实投影';

create table purchase_supplier_confirm_fact (
    fact_id bigint not null auto_increment primary key,
    event_code varchar(128) not null,
    order_no varchar(64) null,
    supplier_id bigint not null,
    confirm_status varchar(64) not null,
    reason varchar(512) null,
    source_version int not null default 0,
    occurred_at datetime(3) not null,
    payload_json json not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_confirm_fact_event (event_code),
    key idx_purchase_confirm_fact_order (order_no, supplier_id)
) comment '采购系统供应商订单确认事实投影';

create table purchase_wms_inbound_fact (
    fact_id bigint not null auto_increment primary key,
    event_code varchar(128) not null,
    inbound_no varchar(64) null,
    order_no varchar(64) null,
    asn_no varchar(64) null,
    warehouse_code varchar(64) null,
    event_type varchar(128) not null,
    received_qty decimal(18, 6) not null default 0,
    qualified_qty decimal(18, 6) not null default 0,
    unqualified_qty decimal(18, 6) not null default 0,
    putaway_qty decimal(18, 6) not null default 0,
    reason varchar(512) null,
    occurred_at datetime(3) not null,
    payload_json json not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_wms_fact_event (event_code),
    key idx_purchase_wms_fact_inbound (inbound_no, event_type),
    key idx_purchase_wms_fact_order (order_no, asn_no)
) comment '采购系统WMS入库执行事实投影';

create table purchase_transport_fact (
    fact_id bigint not null auto_increment primary key,
    event_code varchar(128) not null,
    order_no varchar(64) null,
    inbound_no varchar(64) null,
    asn_no varchar(64) null,
    shipment_id varchar(64) null,
    waybill_no varchar(64) null,
    carrier_code varchar(64) null,
    transport_status varchar(64) not null,
    transport_node varchar(256) null,
    exception_reason varchar(512) null,
    occurred_at datetime(3) not null,
    payload_json json not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_transport_fact_event (event_code),
    key idx_purchase_transport_fact_order (order_no, inbound_no),
    key idx_purchase_transport_fact_waybill (waybill_no, transport_status)
) comment '采购系统TMS运输事实投影';

create table purchase_bms_fact (
    fact_id bigint not null auto_increment primary key,
    event_code varchar(128) not null,
    order_no varchar(64) null,
    supplier_id bigint not null,
    event_type varchar(128) not null,
    currency varchar(16) null,
    amount decimal(18, 2) not null default 0,
    source_version int not null default 0,
    payload_json json not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_bms_fact_event (event_code),
    key idx_purchase_bms_fact_order (order_no, supplier_id)
) comment '采购系统BMS应付结算事实投影';

-- ============================================================================
-- Source: V8__purchase_order_supplier_rejected_status.sql"
-- ============================================================================
alter table purchase_order
    modify column status tinyint not null comment '1草稿 2待审批 3已审批 4待供应商确认 5供应商已确认 6供应商差异 7部分入库 8已完成 9已取消 10已关闭 11已驳回 12供应商已拒绝';

-- ============================================================================
-- Source: V9__purchase_supplier_confirm_processing.sql"
-- ============================================================================
alter table purchase_supplier_confirm_fact
    add column processed_status tinyint not null default 1 comment '1待处理 2已接受差异 3协商中 4已取消订单' after payload_json,
    add column process_comment varchar(512) null after processed_status,
    add column processed_by bigint null after process_comment,
    add column processed_at datetime(3) null after processed_by,
    add column process_version int not null default 0 after processed_at,
    add key idx_purchase_confirm_fact_process (processed_status, occurred_at);

-- ============================================================================
-- Source: V10__purchase_integration_command_retry.sql"
-- ============================================================================
alter table purchase_integration_command add column next_retry_at datetime(3) null after retry_count,
    add column remote_reference varchar(128) null after next_retry_at,
    add column completed_at datetime(3) null after remote_reference;

-- ============================================================================
-- Source: V11__purchase_persistent_idempotency.sql"
-- ============================================================================
create table purchase_idempotency (
    id bigint primary key auto_increment,
    business_type varchar(128) not null,
    idempotency_key varchar(128) not null,
    request_digest char(64) not null,
    process_status tinyint not null comment '1 processing, 2 completed, 3 failed',
    result_id bigint null,
    result_business_no varchar(128) null,
    result_status int null,
    result_status_name varchar(128) null,
    result_version int null,
    result_event_code varchar(128) null,
    failure_reason varchar(500) null,
    completed_at datetime(3) null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_idempotency (business_type, idempotency_key),
    key idx_purchase_idempotency_status (process_status, updated_at)
);

-- ============================================================================
-- Source: V12__purchase_workbench_group_scope.sql"
-- ============================================================================
create table purchase_group_member_scope (
    scope_id bigint not null auto_increment primary key,
    purchase_group_id bigint not null,
    purchase_org_id bigint not null,
    member_id bigint not null comment '采购事实的负责人标识，当前对应各事实表created_by或申请人',
    status tinyint not null default 1 comment '1生效 2失效',
    effective_from date null,
    effective_to date null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_group_member (purchase_group_id, purchase_org_id, member_id),
    key idx_purchase_group_member_effective (
        purchase_group_id, status, effective_from, effective_to
    )
) comment '采购工作台采购组成员数据范围投影';

-- ============================================================================
-- Source: V13__purchase_order_change_base_version.sql"
-- ============================================================================
alter table purchase_order_change
    add column base_order_version int null comment '创建变更单时的采购订单乐观锁版本' after order_no;

update purchase_order_change change_record
join purchase_order purchase_order_record on purchase_order_record.order_no = change_record.order_no
set change_record.base_order_version = purchase_order_record.version
where change_record.base_order_version is null;

alter table purchase_order_change
    modify column base_order_version int not null comment '创建变更单时的采购订单乐观锁版本';

SET FOREIGN_KEY_CHECKS = 1;

