package com.chaobo.scm.supplier.infrastructure.persistence.operations;import com.chaobo.scm.supplier.application.operations.OperationViews;import org.apache.ibatis.annotations.*;import java.math.BigDecimal;import java.time.*;import java.util.List;
@Mapper public interface SupplierOperationsMapper{
 @Insert("INSERT INTO sup_work_item(work_item_id,work_type,supplier_id,business_type,business_id,business_no,title,assignee_type,due_at,status,source_event_code) VALUES(#{id},#{type},#{supplierId},#{businessType},#{businessId},#{businessNo},#{title},#{assigneeType},#{dueAt},1,#{eventCode}) ON DUPLICATE KEY UPDATE source_event_code=source_event_code")int insertWork(@Param("id")long id,@Param("type")String type,@Param("supplierId")long supplierId,@Param("businessType")String businessType,@Param("businessId")long businessId,@Param("businessNo")String businessNo,@Param("title")String title,@Param("assigneeType")int assigneeType,@Param("dueAt")OffsetDateTime dueAt,@Param("eventCode")String eventCode);
 @Select("<script>SELECT work_item_id id,work_type workType,supplier_id supplierId,business_type businessType,business_id businessId,business_no businessNo,title,assignee_type assigneeType,due_at dueAt,status,version FROM sup_work_item WHERE 1=1 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND status=#{status}</if> ORDER BY due_at IS NULL,due_at,created_at DESC LIMIT #{offset},#{size}</script>")List<OperationViews.WorkItem> workItems(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("offset")int offset,@Param("size")int size);
 @Update("UPDATE sup_work_item SET status=#{status},version=version+1 WHERE work_item_id=#{id} AND version=#{version} AND status IN (1,2)")int processWork(@Param("id")long id,@Param("version")int version,@Param("status")int status);
 @Insert("INSERT INTO sup_warning(warning_id,warning_type,supplier_id,business_type,business_id,warning_level,warning_message,occurred_at,status,source_event_code) VALUES(#{id},#{type},#{supplierId},#{businessType},#{businessId},#{level},#{message},#{occurredAt},1,#{eventCode}) ON DUPLICATE KEY UPDATE source_event_code=source_event_code")int insertWarning(@Param("id")long id,@Param("type")String type,@Param("supplierId")long supplierId,@Param("businessType")String businessType,@Param("businessId")long businessId,@Param("level")int level,@Param("message")String message,@Param("occurredAt")OffsetDateTime occurredAt,@Param("eventCode")String eventCode);
 @Select("<script>SELECT warning_id id,warning_type warningType,supplier_id supplierId,business_type businessType,business_id businessId,warning_level level,warning_message message,occurred_at occurredAt,status,version FROM sup_warning WHERE 1=1 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND status=#{status}</if> ORDER BY warning_level DESC,occurred_at DESC LIMIT #{offset},#{size}</script>")List<OperationViews.Warning> warnings(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("offset")int offset,@Param("size")int size);
 @Update("UPDATE sup_warning SET status=#{status},version=version+1 WHERE warning_id=#{id} AND version=#{version} AND status IN (1,2)")int processWarning(@Param("id")long id,@Param("version")int version,@Param("status")int status);
 @Select("SELECT consume_log_id id,source_system sourceSystem,event_code eventCode,event_type eventType,consumer_name consumerName,retry_count retryCount,fail_reason reason,updated_at updatedAt,'INBOUND' direction FROM sup_event_consume_log WHERE consume_status=3 ORDER BY updated_at DESC LIMIT #{limit}")List<OperationViews.FailedEvent> failedInbound(int limit);
 @Select("SELECT event_id id,source_system sourceSystem,event_code eventCode,event_type eventType,NULL consumerName,retry_count retryCount,fail_reason reason,updated_at updatedAt,'OUTBOUND' direction FROM sup_domain_event WHERE event_status=4 ORDER BY updated_at DESC LIMIT #{limit}")List<OperationViews.FailedEvent> failedOutbound(int limit);
 @Update("UPDATE sup_event_consume_log SET consume_status=3,fail_reason=CONCAT('MANUAL_REPLAY:',#{reason}) WHERE consume_log_id=#{id} AND consume_status=3")int replayInbound(@Param("id")long id,@Param("reason")String reason);
 @Update("UPDATE sup_domain_event SET event_status=1,fail_reason=CONCAT('MANUAL_REPLAY:',#{reason}),updated_at=NOW(3) WHERE event_id=#{id} AND event_status=4")int replayOutbound(@Param("id")long id,@Param("reason")String reason);
 @Insert("INSERT INTO sup_data_reconciliation(reconciliation_job_id,reconciliation_type,target_system,business_date,local_count,remote_count,local_amount,remote_amount,difference_detail,status,created_by,version) VALUES(#{id},#{type},#{target},#{date},#{localCount},#{remoteCount},#{localAmount},#{remoteAmount},#{detail},#{status},#{operator},0) ON DUPLICATE KEY UPDATE local_count=VALUES(local_count),remote_count=VALUES(remote_count),local_amount=VALUES(local_amount),remote_amount=VALUES(remote_amount),difference_detail=VALUES(difference_detail),status=VALUES(status),version=version+1")void upsertReconciliation(@Param("id")long id,@Param("type")String type,@Param("target")String target,@Param("date")LocalDate date,@Param("localCount")long localCount,@Param("remoteCount")long remoteCount,@Param("localAmount")BigDecimal localAmount,@Param("remoteAmount")BigDecimal remoteAmount,@Param("detail")String detail,@Param("status")int status,@Param("operator")long operator);
 @Select("SELECT reconciliation_job_id id,reconciliation_type type,target_system targetSystem,business_date businessDate,local_count localCount,remote_count remoteCount,local_amount localAmount,remote_amount remoteAmount,difference_detail differenceDetail,status,version FROM sup_data_reconciliation ORDER BY business_date DESC,reconciliation_type")List<OperationViews.Reconciliation> reconciliations();
 @Select("SELECT COUNT(*) FROM sup_asn WHERE DATE(updated_at)=#{date} AND deleted=0")long localAsnCount(LocalDate date);
 @Select("SELECT COUNT(*) FROM sup_supplier_return WHERE DATE(updated_at)=#{date} AND deleted=0")long localReturnCount(LocalDate date);
 @Select("SELECT COUNT(*) FROM sup_reconciliation WHERE DATE(updated_at)=#{date} AND deleted=0")long localStatementCount(LocalDate date);
 @Select("SELECT COALESCE(SUM(statement_amount),0) FROM sup_reconciliation WHERE DATE(updated_at)=#{date} AND deleted=0")BigDecimal localStatementAmount(LocalDate date);
 @Select("SELECT (SELECT COUNT(*) FROM sup_work_item WHERE status IN(1,2)) pendingWork,(SELECT COUNT(*) FROM sup_warning WHERE status IN(1,2)) openWarnings,(SELECT COUNT(*) FROM sup_event_consume_log WHERE consume_status=3) failedInboundEvents,(SELECT COUNT(*) FROM sup_domain_event WHERE event_status=4) failedOutboundEvents,(SELECT COUNT(*) FROM sup_quality_issue WHERE issue_status&lt;&gt;4 AND deleted=0) activeQualityIssues,(SELECT COUNT(*) FROM sup_supplier_return WHERE return_status NOT IN(10,11) AND deleted=0) openReturns,(SELECT COUNT(*) FROM sup_reconciliation WHERE status IN(1,3) AND deleted=0) pendingReconciliations,(SELECT COALESCE(AVG(total_score),0) FROM sup_score_result WHERE status=2) latestAverageScore")OperationViews.Dashboard dashboard();
}
