package com.chaobo.scm.supplier.infrastructure.persistence.item;
import com.chaobo.scm.common.api.PageResult;import com.chaobo.scm.common.error.*;import com.chaobo.scm.supplier.application.item.*;import com.chaobo.scm.supplier.domain.item.*;import org.springframework.stereotype.Repository;import java.util.*;
@Repository public class MyBatisSupplierItemAdapter implements SupplierItemRepository,SupplierItemReadModelPort{
 private final SupplierItemMapper m;public MyBatisSupplierItemAdapter(SupplierItemMapper m){this.m=m;}
 public Optional<SupplierItemAggregate> findById(long id){var r=m.find(id);return r==null?Optional.empty():Optional.of(SupplierItemAggregate.rehydrate(r.supplierItemId(),r.supplierId(),r.skuCode(),r.supplierSkuCode(),condition(r),SupplyStatus.fromCode(r.supplyStatus()),r.pauseReason(),r.version()));}
 public List<SupplierItemAggregate> findAvailableBySupplier(long supplierId){return m.availableBySupplier(supplierId).stream().map(this::aggregate).toList();}public List<SupplierItemAggregate> findAvailableBySku(String skuCode){return m.availableBySku(skuCode).stream().map(this::aggregate).toList();}
 public boolean exists(long supplierId,String sku){return m.exists(supplierId,sku);}public void save(SupplierItemAggregate a,long operator){var r=row(a);if(m.find(a.itemId())==null)m.insert(r,operator);else if(m.update(r,a.version()-1,operator)!=1)throw new BusinessException(ErrorCode.VERSION_CONFLICT,"供应商商品已被更新");}
 public Optional<SupplierItemView> detail(long id){var r=m.find(id);return r==null?Optional.empty():Optional.of(view(r));}
 public PageResult<SupplierItemView> page(Long supplierId,Integer status,String keyword,int pageNo,int pageSize){long total=m.count(supplierId,status,keyword);var records=m.page(supplierId,status,keyword,(pageNo-1)*pageSize,pageSize).stream().map(this::view).toList();return new PageResult<>(pageNo,pageSize,total,records);}
 private SupplyCondition condition(SupplierItemMapper.Row r){return new SupplyCondition(r.moq(),r.mpq(),r.leadTimeDays(),r.purchaseUnit(),r.effectiveFrom(),r.effectiveTo());}
 private SupplierItemAggregate aggregate(SupplierItemMapper.Row r){return SupplierItemAggregate.rehydrate(r.supplierItemId(),r.supplierId(),r.skuCode(),r.supplierSkuCode(),condition(r),SupplyStatus.fromCode(r.supplyStatus()),r.pauseReason(),r.version());}
 private SupplierItemMapper.Row row(SupplierItemAggregate a){var c=a.condition();return new SupplierItemMapper.Row(a.itemId(),a.supplierId(),a.skuCode(),a.supplierSkuCode(),c.moq(),c.mpq(),c.leadTimeDays(),c.purchaseUnit(),c.effectiveFrom(),c.effectiveTo(),a.status().code(),a.pauseReason(),a.version(),null);}
 private SupplierItemView view(SupplierItemMapper.Row r){var s=SupplyStatus.fromCode(r.supplyStatus());return new SupplierItemView(r.supplierItemId(),r.supplierId(),r.skuCode(),r.supplierSkuCode(),r.moq(),r.mpq(),r.leadTimeDays(),r.purchaseUnit(),r.effectiveFrom(),r.effectiveTo(),s.code(),s.label(),r.pauseReason(),r.version(),r.updatedAt());}
}
