package com.chaobo.scm.supplier.infrastructure.persistence.item;
import org.apache.ibatis.annotations.*;import java.math.BigDecimal;import java.time.*;import java.util.List;
@Mapper public interface SupplierItemMapper {
 record Row(long supplierItemId,long supplierId,String skuCode,String supplierSkuCode,BigDecimal moq,BigDecimal mpq,int leadTimeDays,String purchaseUnit,LocalDate effectiveFrom,LocalDate effectiveTo,int supplyStatus,String pauseReason,int version,OffsetDateTime updatedAt){}
 @Select("SELECT supplier_item_id,supplier_id,sku_code,supplier_sku_code,moq,mpq,lead_time_days,purchase_unit,effective_from,effective_to,supply_status,pause_reason,version,updated_at FROM sup_supplier_item WHERE supplier_item_id=#{id} AND deleted=0") Row find(long id);
 @Select("SELECT supplier_item_id,supplier_id,sku_code,supplier_sku_code,moq,mpq,lead_time_days,purchase_unit,effective_from,effective_to,supply_status,pause_reason,version,updated_at FROM sup_supplier_item WHERE supplier_id=#{supplierId} AND supply_status=1 AND deleted=0") List<Row> availableBySupplier(long supplierId);
 @Select("SELECT supplier_item_id,supplier_id,sku_code,supplier_sku_code,moq,mpq,lead_time_days,purchase_unit,effective_from,effective_to,supply_status,pause_reason,version,updated_at FROM sup_supplier_item WHERE sku_code=#{skuCode} AND supply_status=1 AND deleted=0") List<Row> availableBySku(String skuCode);
 @Select("SELECT COUNT(*) FROM sup_supplier_item WHERE supplier_id=#{supplierId} AND sku_code=#{sku} AND deleted=0") boolean exists(@Param("supplierId")long supplierId,@Param("sku")String sku);
 @Insert("INSERT INTO sup_supplier_item(supplier_item_id,supplier_id,sku_code,supplier_sku_code,moq,mpq,lead_time_days,purchase_unit,effective_from,effective_to,supply_status,pause_reason,created_by,updated_by,version,deleted) VALUES(#{r.supplierItemId},#{r.supplierId},#{r.skuCode},#{r.supplierSkuCode},#{r.moq},#{r.mpq},#{r.leadTimeDays},#{r.purchaseUnit},#{r.effectiveFrom},#{r.effectiveTo},#{r.supplyStatus},#{r.pauseReason},#{operator},#{operator},#{r.version},0)") void insert(@Param("r")Row r,@Param("operator")long operator);
 @Update("UPDATE sup_supplier_item SET supplier_sku_code=#{r.supplierSkuCode},moq=#{r.moq},mpq=#{r.mpq},lead_time_days=#{r.leadTimeDays},purchase_unit=#{r.purchaseUnit},effective_from=#{r.effectiveFrom},effective_to=#{r.effectiveTo},supply_status=#{r.supplyStatus},pause_reason=#{r.pauseReason},updated_by=#{operator},version=#{r.version} WHERE supplier_item_id=#{r.supplierItemId} AND version=#{expected} AND deleted=0") int update(@Param("r")Row r,@Param("expected")int expected,@Param("operator")long operator);
 @Select("<script>SELECT COUNT(*) FROM sup_supplier_item WHERE deleted=0 <if test='supplierId != null'>AND supplier_id=#{supplierId}</if><if test='status != null'>AND supply_status=#{status}</if><if test='keyword != null and keyword != \"\"'>AND (sku_code LIKE CONCAT('%',#{keyword},'%') OR supplier_sku_code LIKE CONCAT('%',#{keyword},'%'))</if></script>") long count(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("keyword")String keyword);
 @Select("<script>SELECT supplier_item_id,supplier_id,sku_code,supplier_sku_code,moq,mpq,lead_time_days,purchase_unit,effective_from,effective_to,supply_status,pause_reason,version,updated_at FROM sup_supplier_item WHERE deleted=0 <if test='supplierId != null'>AND supplier_id=#{supplierId}</if><if test='status != null'>AND supply_status=#{status}</if><if test='keyword != null and keyword != \"\"'>AND (sku_code LIKE CONCAT('%',#{keyword},'%') OR supplier_sku_code LIKE CONCAT('%',#{keyword},'%'))</if> ORDER BY updated_at DESC LIMIT #{offset},#{size}</script>") List<Row> page(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("keyword")String keyword,@Param("offset")int offset,@Param("size")int size);
}
