package com.chaobo.scm.supplier.infrastructure.persistence.account;
import org.apache.ibatis.annotations.*;import java.time.*;import java.util.*;
@Mapper public interface SupplierAccessMapper{
 record ContactRow(long id,long supplierId,String name,String mobile,String email,String role,boolean primary,int status,int version){}record BindingRow(long id,long supplierId,long userId,String role,boolean primary,int status,OffsetDateTime boundAt,int version){}
 @Select("SELECT contact_id id,supplier_id supplierId,contact_name name,mobile,email,contact_role role,is_primary `primary`,status,version FROM sup_supplier_contact WHERE contact_id=#{id} AND deleted=0")ContactRow contact(long id);
 @Select("SELECT contact_id id,supplier_id supplierId,contact_name name,mobile,email,contact_role role,is_primary `primary`,status,version FROM sup_supplier_contact WHERE supplier_id=#{supplierId} AND deleted=0 ORDER BY is_primary DESC,created_at")List<ContactRow> contacts(long supplierId);
 @Insert("INSERT INTO sup_supplier_contact(contact_id,supplier_id,contact_name,mobile,email,contact_role,is_primary,status,created_by,updated_by,version,deleted) VALUES(#{r.id},#{r.supplierId},#{r.name},#{r.mobile},#{r.email},#{r.role},#{r.primary},1,#{operator},#{operator},0,0)")void insertContact(@Param("r")ContactRow r,@Param("operator")long operator);
 @Update("UPDATE sup_supplier_contact SET contact_name=#{r.name},mobile=#{r.mobile},email=#{r.email},contact_role=#{r.role},is_primary=#{r.primary},updated_by=#{operator},version=version+1 WHERE contact_id=#{r.id} AND version=#{version} AND deleted=0")int updateContact(@Param("r")ContactRow r,@Param("version")int version,@Param("operator")long operator);@Update("UPDATE sup_supplier_contact SET is_primary=0 WHERE supplier_id=#{supplierId} AND deleted=0")void clearPrimaryContact(long supplierId);
 @Select("SELECT supplier_user_id id,supplier_id supplierId,user_id userId,binding_role role,is_primary `primary`,status,bound_at boundAt,version FROM sup_supplier_user_binding WHERE supplier_user_id=#{id}")BindingRow binding(long id);
 @Select("SELECT supplier_user_id id,supplier_id supplierId,user_id userId,binding_role role,is_primary `primary`,status,bound_at boundAt,version FROM sup_supplier_user_binding WHERE supplier_id=#{supplierId} ORDER BY status,bound_at")List<BindingRow> bindings(long supplierId);
 @Insert("INSERT INTO sup_supplier_user_binding(supplier_user_id,supplier_id,user_id,binding_role,is_primary,status,bound_by,version) VALUES(#{r.id},#{r.supplierId},#{r.userId},#{r.role},#{r.primary},1,#{operator},0)")void insertBinding(@Param("r")BindingRow r,@Param("operator")long operator);
 @Update("UPDATE sup_supplier_user_binding SET status=2,unbound_at=NOW(3),version=version+1 WHERE supplier_user_id=#{id} AND version=#{version} AND status=1")int disableBinding(@Param("id")long id,@Param("version")int version);
 @Select("SELECT COUNT(*) FROM sup_supplier_user_binding WHERE supplier_id=#{supplierId} AND user_id=#{userId} AND status=1")boolean activeBinding(@Param("supplierId")long supplierId,@Param("userId")long userId);
 @Select("SELECT supplier_id FROM sup_supplier_user_binding WHERE user_id=#{userId} AND status=1 ORDER BY supplier_id")Set<Long> activeSupplierIds(long userId);
}
