spring:
  application:
    name: bms-service
  profiles:
    active: @spring.profiles.active@
  cloud:
    nacos:
      username: ${NACOS_USERNAME:@nacos.username@}
      password: ${NACOS_PASSWORD:@nacos.password@}
      config:
        server-addr: ${NACOS_SERVER_ADDR:@nacos.server-addr@}
        namespace: ${NACOS_NAMESPACE:@nacos.namespace@}
        group: ${NACOS_GROUP:@nacos.group@}
  flyway:
    enabled: true
  jackson:
    time-zone: Asia/Shanghai
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8110
scm:
  security:
    hmac-secret: ${IAM_JWT_SECRET:}
    permission-namespace: bms
