const page = (id, label, options = {}) => ({ id, label, ...options })

export const systemCatalog = [
  {
    id: 'supplier',
    code: 'SUP',
    shortName: '供应商',
    name: '供应商协同',
    domain: '供应商协同上下文',
    permission: 'supplier:*',
    goal: '管理供应商档案、订单确认、ASN、质量整改、对账与绩效协同。',
    workflow: ['订单待确认', '供应商已确认', 'ASN 已提交', '到仓收货', '对账完成'],
    pages: [
      page('workbench', '供应商工作台'),
      page('profile', '供应商档案'),
      page('user-bindings', '账号绑定'),
      page('skus', '供应商商品'),
      page('po-confirms', '订单协同', { legacy: 'supplier-order' }),
      page('asns', 'ASN 管理', { legacy: 'supplier-asn' }),
      page('returns', '退供协同'),
      page('reconciliations', '对账协同'),
      page('quality-issues', '质量协同', { legacy: 'supplier-quality' }),
      page('scores', '供应商评分'),
      page('rectifications', '整改管理', { legacy: 'supplier-quality' }),
      page('operation-logs', '操作日志'),
    ],
  },
  {
    id: 'purchase',
    code: 'PUR',
    shortName: '采购',
    name: '采购管理',
    domain: '采购执行上下文',
    permission: 'purchase:*',
    goal: '贯通请购、询报价、定标、采购订单、供应商确认、到货与退供。',
    workflow: ['请购已提交', '询价已发布', '供应商已定标', '采购订单已发布', '到货已完成'],
    pages: [
      page('workbench', '采购工作台'),
      page('requisitions', '请购管理', { legacy: 'requisitions' }),
      page('requisition-approvals', '请购审批', { legacy: 'requisitions' }),
      page('rfqs', '询价单', { legacy: 'rfqs' }),
      page('quotations', '报价管理'),
      page('compare-results', '比价定标'),
      page('orders', '采购订单', { legacy: 'orders' }),
      page('supplier-confirms', '供应商确认', { legacy: 'confirms' }),
      page('inbound-tracks', '到货跟踪', { legacy: 'inbounds' }),
      page('supplier-returns', '退供申请'),
      page('prices', '采购价格'),
      page('failed-events', '失败事件', { legacy: 'failedEvents' }),
      page('operation-logs', '操作日志'),
    ],
  },
  {
    id: 'wms',
    code: 'WMS',
    shortName: '仓储',
    name: '仓储执行',
    domain: '仓储作业上下文',
    permission: 'wms:*',
    goal: '以任务驱动入库、质检、上架、拣选、复核、发货、退货和盘点。',
    workflow: ['入库单已接收', '收货已完成', '质检已判定', '上架已完成', '库存事实已上报'],
    pages: [
      page('workbench', 'WMS 工作台'),
      page('inbounds', '入库单'),
      page('receipts', '收货作业'),
      page('qc-orders', '质检作业'),
      page('putaway-tasks', '上架任务'),
      page('stocks', '库内库存'),
      page('outbounds', '出库单'),
      page('waves', '波次管理'),
      page('picking-orders', '拣货单'),
      page('pack-orders', '复核包装'),
      page('shipments', '发货交接'),
      page('return-receipts', '退货入库'),
      page('count-plans', '盘点管理'),
      page('exceptions', '异常处理'),
      page('failed-events', '事件运维', { legacy: 'wms' }),
      page('operation-logs', '操作日志'),
    ],
  },
  {
    id: 'inventory',
    code: 'INV',
    shortName: '库存',
    name: '中央库存',
    domain: '库存可用性上下文',
    permission: 'inventory:*',
    goal: '统一管理余额、可用量、预占、冻结、调整、流水、快照与跨系统对账。',
    workflow: ['库存事实已接收', '余额已更新', '可用量已重算', '流水已登记', '读模型已刷新'],
    pages: [
      page('workbench', '库存工作台'),
      page('balances', '库存余额', { legacy: 'stocks' }),
      page('available', '可用库存', { legacy: 'stocks' }),
      page('reservations', '预占管理'),
      page('freezes', '冻结解冻'),
      page('adjustments', '库存调整'),
      page('ledgers', '库存流水', { legacy: 'ledgers' }),
      page('snapshots', '库存快照', { legacy: 'snapshots' }),
      page('reconciliations', '库存对账', { legacy: 'reconciliations' }),
      page('event-logs', '事件日志', { legacy: 'inventory-events' }),
      page('operation-logs', '操作日志'),
    ],
  },
  {
    id: 'oms',
    code: 'OMS',
    shortName: '订单',
    name: '订单履约',
    domain: '订单履约上下文',
    permission: 'oms:*',
    goal: '把渠道接入、审单、分仓、预占、出库、取消和售后组织为可补偿流程。',
    workflow: ['渠道订单已接收', '订单已审核', '库存已预占', '履约单已下发', '订单已完成'],
    pages: [
      page('workbench', 'OMS 工作台'),
      page('channel-orders', '渠道订单接入', { legacy: 'channelOrders' }),
      page('sales-orders', '销售订单', { legacy: 'salesOrders' }),
      page('audit-results', '订单审单'),
      page('fulfillments', '分仓履约', { legacy: 'fulfillments' }),
      page('reservations', '库存预占'),
      page('outbounds', '出库单', { legacy: 'outbounds' }),
      page('cancel-requests', '取消管理'),
      page('after-sales', '售后管理'),
      page('exceptions', '异常处理'),
      page('operation-logs', '操作日志'),
    ],
  },
  {
    id: 'tms',
    code: 'TMS',
    shortName: '运输',
    name: '运输管理',
    domain: '运输履约上下文',
    permission: 'tms:*',
    goal: '统一承接运输需求，完成运单、面单、轨迹、签收、异常和费用事实。',
    workflow: ['运输任务已创建', '运单已创建', '包裹已揽收', '运输轨迹已更新', '签收已确认'],
    pages: [
      page('workbench', 'TMS 工作台'),
      page('transport-tasks', '运输任务', { legacy: 'transportTasks' }),
      page('waybills', '运单管理', { legacy: 'waybills' }),
      page('labels', '面单管理'),
      page('tracks', '轨迹查询'),
      page('signatures', '签收管理'),
      page('exceptions', '物流异常', { legacy: 'tmsExceptions' }),
      page('fee-sources', '物流费用来源', { legacy: 'feeSources' }),
      page('carriers', '承运商接口'),
      page('operation-logs', '操作日志'),
    ],
  },
  {
    id: 'bms',
    code: 'BMS',
    shortName: '结算',
    name: '计费结算',
    domain: '计费结算上下文',
    permission: 'bms:*',
    goal: '把业务费用事实转化为可对账、可结算、可开票和可追溯的财务事实。',
    workflow: ['费用事实已接收', '计费规则已匹配', '对账单已确认', '账单已生成', '财务已交接'],
    pages: [
      page('workbench', 'BMS 工作台'),
      page('billing-subjects', '计费对象', { legacy: 'billingSubjects' }),
      page('charge-sources', '费用来源', { legacy: 'chargeSources' }),
      page('charge-details', '费用明细'),
      page('billing-rules', '计费规则'),
      page('reconciliations', '对账管理'),
      page('bills', '账单管理'),
      page('invoices', '发票管理'),
      page('finance-handoffs', '财务交接'),
      page('refunds', '退款与冲正'),
      page('settlement-reports', '结算报表', { legacy: 'settlementSummary' }),
      page('operation-logs', '操作日志'),
    ],
  },
  {
    id: 'mdm',
    code: 'MDM',
    shortName: '主数据',
    name: '主数据',
    domain: '主数据上下文',
    permission: 'mdm:*',
    goal: '统一类型、字段、编码、审核、发布、质量和变更追溯。',
    workflow: ['主数据草稿已创建', '主数据已提交审核', '主数据已启用', '发布任务已创建', '下游回执已返回'],
    pages: [
      page('workbench', '主数据工作台'),
      page('types', '主数据类型', { legacy: 'types' }),
      page('field-defs', '字段模板', { legacy: 'templates' }),
      page('code-rules', '编码规则', { legacy: 'codeRules' }),
      page('products', '商品主数据', { legacy: 'records' }),
      page('partners', '合作伙伴', { legacy: 'records' }),
      page('warehouses', '仓储主数据', { legacy: 'records' }),
      page('approvals', '主数据审核'),
      page('publishes', '主数据发布', { legacy: 'publications' }),
      page('imports', '导入导出', { legacy: 'imports' }),
      page('quality-issues', '质量问题', { legacy: 'quality' }),
      page('change-logs', '变更日志'),
    ],
  },
  {
    id: 'iam',
    code: 'IAM',
    shortName: '权限',
    name: '权限中心',
    domain: '身份与访问上下文',
    permission: 'iam:*',
    goal: '统一身份、用户、角色、菜单、权限点、数据范围、会话和安全审计。',
    workflow: ['用户已创建', '用户已激活', '角色已分配', '权限缓存已刷新', '审计日志已记录'],
    pages: [
      page('workbench', '权限工作台'),
      page('users', '用户管理', { legacy: 'users' }),
      page('roles', '角色管理', { legacy: 'roles' }),
      page('menus', '菜单页面'),
      page('permissions', '权限点', { legacy: 'permissions' }),
      page('role-grants', '角色授权'),
      page('user-roles', '用户角色'),
      page('sessions', '会话管理'),
      page('approvals', '审批实例', { legacy: 'approvals' }),
      page('security-policies', '安全策略', { legacy: 'securityPolicies' }),
      page('apps', '应用管理', { legacy: 'apps' }),
      page('sso-clients', 'SSO 客户端', { legacy: 'ssoClients' }),
      page('operation-logs', '操作日志', { legacy: 'operationLogs' }),
    ],
  },
]

export const systemsById = new Map(systemCatalog.map((system) => [system.id, system]))

export function findSystem(systemId) {
  return systemsById.get(systemId) || systemCatalog[0]
}

export function findSystemPage(systemId, pageId) {
  const system = findSystem(systemId)
  return system.pages.find((item) => item.id === pageId) || system.pages[0]
}
