# Nacos standalone dev config
server.servlet.contextPath=/nacos
server.port=8848
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 单机嵌入式存储，资源占用低。
# 如果要切到 MySQL，需要额外导入 Nacos 官方 mysql-schema.sql，并配置 db.url/user/password。
spring.sql.init.platform=

# Auth
nacos.core.auth.enabled=true
nacos.core.auth.system.type=nacos
nacos.core.auth.server.identity.key=serverIdentity
nacos.core.auth.server.identity.value=scm-nacos-server
nacos.core.auth.plugin.nacos.token.secret.key=U2NtTmFjb3NBdXRoVG9rZW5Gb3JEZXZlbG9wbWVudE9ubHkxMjM0NTY3ODkw

# Naming / Config
nacos.naming.empty-service.auto-clean=true
nacos.naming.empty-service.clean.initial-delay-ms=60000
nacos.naming.empty-service.clean.period-time-ms=20000

# 日志
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.rotate=true
server.tomcat.accesslog.max-days=7
server.tomcat.accesslog.directory=/home/nacos/logs

# JVM 由 docker-compose 环境变量控制：JVM_XMS/JVM_XMX/JVM_XMN
