package com.chaobo.scm.supplier.infrastructure.persistence.returning;
import org.apache.ibatis.annotations.*;import java.math.BigDecimal;import java.time.OffsetDateTime;import java.util.*;
@Mapper public interface SupplierReturnMapper{
 record Header(long id,String no,long supplierId,long warehouseId,Long qualityIssueId,String reason,int status,String inventoryLockNo,OffsetDateTime supplierConfirmedAt,String outboundNo,String shipmentId,String waybillNo,String carrierCode,boolean settlementCompleted,String settlementRef,BigDecimal offsetAmount,BigDecimal claimAmount,String exceptionReason,int version){}
 record Line(long id,long returnId,String skuCode,String batchNo,String inventoryStatus,BigDecimal requestedQty,BigDecimal lockedQty,BigDecimal outboundQty,BigDecimal signedQty){}
 @Select("SELECT return_id id,return_no no,supplier_id supplierId,warehouse_id warehouseId,source_quality_issue_id qualityIssueId,return_reason reason,return_status status,inventory_lock_no inventoryLockNo,supplier_confirmed_at supplierConfirmedAt,outbound_no outboundNo,shipment_id shipmentId,waybill_no waybillNo,carrier_code carrierCode,settlement_completed settlementCompleted,settlement_ref settlementRef,offset_amount offsetAmount,claim_amount claimAmount,exception_reason exceptionReason,version FROM sup_supplier_return WHERE return_id=#{id} AND deleted=0") Header find(long id);
 @Select("SELECT return_line_id id,return_id returnId,sku_code skuCode,batch_no batchNo,inventory_status inventoryStatus,requested_qty requestedQty,locked_qty lockedQty,outbound_qty outboundQty,signed_qty signedQty FROM sup_supplier_return_line WHERE return_id=#{id} AND deleted=0 ORDER BY return_line_id") List<Line> lines(long id);
 @Insert("INSERT INTO sup_supplier_return(return_id,return_no,supplier_id,warehouse_id,source_quality_issue_id,return_reason,return_status,inventory_lock_no,supplier_confirmed_at,outbound_no,shipment_id,waybill_no,carrier_code,settlement_completed,settlement_ref,offset_amount,claim_amount,exception_reason,created_by,updated_by,version,deleted) VALUES(#{r.id},#{r.no},#{r.supplierId},#{r.warehouseId},#{r.qualityIssueId},#{r.reason},#{r.status},#{r.inventoryLockNo},#{r.supplierConfirmedAt},#{r.outboundNo},#{r.shipmentId},#{r.waybillNo},#{r.carrierCode},#{r.settlementCompleted},#{r.settlementRef},#{r.offsetAmount},#{r.claimAmount},#{r.exceptionReason},#{operator},#{operator},#{r.version},0)") void insert(@Param("r")Header r,@Param("operator")long operator);
 @Update("UPDATE sup_supplier_return SET return_status=#{r.status},inventory_lock_no=#{r.inventoryLockNo},supplier_confirmed_at=#{r.supplierConfirmedAt},outbound_no=#{r.outboundNo},shipment_id=#{r.shipmentId},waybill_no=#{r.waybillNo},carrier_code=#{r.carrierCode},settlement_completed=#{r.settlementCompleted},settlement_ref=#{r.settlementRef},offset_amount=#{r.offsetAmount},claim_amount=#{r.claimAmount},exception_reason=#{r.exceptionReason},updated_by=#{operator},version=#{r.version} WHERE return_id=#{r.id} AND version=#{expected} AND deleted=0") int update(@Param("r")Header r,@Param("expected")int expected,@Param("operator")long operator);
 @Insert("INSERT INTO sup_supplier_return_line(return_line_id,return_id,sku_code,batch_no,inventory_status,requested_qty,locked_qty,outbound_qty,signed_qty,version,deleted) VALUES(#{r.id},#{r.returnId},#{r.skuCode},#{r.batchNo},#{r.inventoryStatus},#{r.requestedQty},#{r.lockedQty},#{r.outboundQty},#{r.signedQty},0,0)") void insertLine(@Param("r")Line r);
 @Update("UPDATE sup_supplier_return_line SET locked_qty=#{r.lockedQty},outbound_qty=#{r.outboundQty},signed_qty=#{r.signedQty},version=version+1 WHERE return_line_id=#{r.id} AND return_id=#{r.returnId} AND deleted=0") void updateLine(@Param("r")Line r);
 @Select("<script>SELECT COUNT(*) FROM sup_supplier_return WHERE deleted=0 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND return_status=#{status}</if></script>") long count(@Param("supplierId")Long supplierId,@Param("status")Integer status);
 @Select("<script>SELECT return_id id,return_no no,supplier_id supplierId,warehouse_id warehouseId,source_quality_issue_id qualityIssueId,return_reason reason,return_status status,inventory_lock_no inventoryLockNo,supplier_confirmed_at supplierConfirmedAt,outbound_no outboundNo,shipment_id shipmentId,waybill_no waybillNo,carrier_code carrierCode,settlement_completed settlementCompleted,settlement_ref settlementRef,offset_amount offsetAmount,claim_amount claimAmount,exception_reason exceptionReason,version FROM sup_supplier_return WHERE deleted=0 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND return_status=#{status}</if> ORDER BY updated_at DESC LIMIT #{offset},#{size}</script>") List<Header> page(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("offset")int offset,@Param("size")int size);
}
