-- INVENTORY service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__inventory_account_reservation.sql"
-- ============================================================================
create table inv_stock_balance (
    stock_id bigint not null primary key,
    owner_id bigint not null,
    warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(128) null,
    on_hand_qty decimal(18,4) not null,
    available_qty decimal(18,4) not null,
    reserved_qty decimal(18,4) not null,
    frozen_qty decimal(18,4) not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_stock_dim(owner_id, warehouse_id, sku_code, batch_no)
) comment '中央库存账户余额';

create table inv_stock_ledger (
    ledger_id bigint not null primary key,
    ledger_no varchar(64) not null,
    stock_id bigint not null,
    ledger_type varchar(32) not null,
    qty_delta decimal(18,4) not null,
    source_system varchar(32) not null,
    source_order_no varchar(64) not null,
    created_at datetime(3) not null,
    unique key uk_inv_ledger_no(ledger_no),
    key idx_inv_ledger_stock(stock_id, created_at),
    key idx_inv_ledger_source(source_system, source_order_no)
) comment '中央库存流水';

create table inv_reservation (
    reservation_id bigint not null primary key,
    reservation_no varchar(64) not null,
    stock_id bigint not null,
    source_system varchar(32) not null,
    source_order_no varchar(64) not null,
    reserved_qty decimal(18,4) not null,
    released_qty decimal(18,4) not null,
    reservation_status tinyint not null comment '1已预占 2已释放 3已关闭',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_reservation_no(reservation_no),
    unique key uk_inv_reservation_source(source_system, source_order_no)
) comment '中央库存预占单';

-- ============================================================================
-- Source: V2__inventory_outbox_inbox.sql"
-- ============================================================================
create table inv_outbox_event (
    event_id bigint not null primary key,
    event_code varchar(128) not null,
    event_type varchar(128) not null,
    aggregate_type varchar(64) not null,
    aggregate_id varchar(64) not null,
    payload_json json not null,
    status tinyint not null comment '1待投递 2已投递 3失败',
    retry_count int not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_outbox_event_code(event_code),
    key idx_inv_outbox_status(status, created_at)
) comment '中央库存Outbox事件';

create table inv_inbox_event (
    inbox_id bigint not null auto_increment primary key,
    source_system varchar(64) not null,
    event_code varchar(128) not null,
    event_type varchar(128) not null,
    payload_json json not null,
    status tinyint not null comment '1处理中 2成功 3失败',
    retry_count int not null default 0,
    last_error varchar(1024) null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_inbox(source_system, event_code),
    key idx_inv_inbox_status(status, updated_at)
) comment '中央库存Inbox事件';

-- ============================================================================
-- Source: V3__inventory_snapshot_reconcile.sql"
-- ============================================================================
create table inv_stock_snapshot (
    snapshot_id bigint not null primary key,
    snapshot_no varchar(64) not null,
    stock_id bigint not null,
    on_hand_qty decimal(18,4) not null,
    available_qty decimal(18,4) not null,
    created_at datetime(3) not null,
    unique key uk_inv_snapshot_no(snapshot_no),
    key idx_inv_snapshot_stock(stock_id, created_at)
) comment '中央库存快照';

create table inv_stock_reconcile (
    reconcile_id bigint not null primary key,
    reconcile_no varchar(64) not null,
    stock_id bigint not null,
    system_qty decimal(18,4) not null,
    wms_qty decimal(18,4) not null,
    difference_qty decimal(18,4) not null,
    reconcile_status tinyint not null comment '1待确认 2已确认',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_reconcile_no(reconcile_no),
    key idx_inv_reconcile_stock(stock_id, reconcile_status)
) comment '中央库存对账单';

-- ============================================================================
-- Source: V4__stock_transfer.sql"
-- ============================================================================
create table inv_stock_transfer (
    transfer_id bigint not null primary key,
    transfer_no varchar(64) not null,
    idempotency_key varchar(128) not null,
    owner_id bigint not null,
    source_warehouse_id bigint not null,
    target_warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(128) null,
    requested_qty decimal(18,4) not null,
    reserved_qty decimal(18,4) not null,
    outbound_qty decimal(18,4) not null,
    received_qty decimal(18,4) not null,
    difference_qty decimal(18,4) not null,
    transfer_status tinyint not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_transfer_no (transfer_no),
    unique key uk_inv_transfer_idempotency (idempotency_key),
    key idx_inv_transfer_status (transfer_status, updated_at),
    key idx_inv_transfer_source (owner_id, source_warehouse_id, transfer_status),
    key idx_inv_transfer_target (owner_id, target_warehouse_id, transfer_status)
) comment '中央库存调拨单';

-- ============================================================================
-- Source: V5__return_disposition.sql"
-- ============================================================================
create table inv_return_disposition (
  id bigint primary key auto_increment,
  disposition_no varchar(64) not null,
  source_event_id varchar(128) not null,
  after_sale_no varchar(64) not null,
  owner_id bigint not null,
  warehouse_id bigint not null,
  sku_code varchar(64) not null,
  batch_no varchar(64),
  received_qty decimal(18,4) not null,
  sellable_qty decimal(18,4) not null default 0,
  defective_qty decimal(18,4) not null default 0,
  frozen_qty decimal(18,4) not null default 0,
  scrapped_qty decimal(18,4) not null default 0,
  unmatched_qty decimal(18,4) not null default 0,
  created_at datetime(3) not null,
  unique key uk_inv_return_disposition_no(disposition_no),
  unique key uk_inv_return_source_event(source_event_id),
  key idx_inv_return_after_sale(after_sale_no),
  key idx_inv_return_stock(owner_id,warehouse_id,sku_code)
);

-- ============================================================================
-- Source: V6__inventory_freeze_adjustment_aggregates.sql"
-- ============================================================================
create table inv_freeze (
    freeze_id bigint not null primary key,
    freeze_no varchar(64) not null,
    stock_id bigint not null,
    owner_id bigint not null,
    warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(128) null,
    freeze_qty decimal(18,4) not null,
    unfrozen_qty decimal(18,4) not null default 0,
    freeze_reason varchar(64) not null,
    source_system varchar(32) not null,
    source_order_no varchar(64) not null,
    freeze_status tinyint not null comment '1草稿 2待审批 3已冻结 4部分解冻 5已解冻 6已取消',
    approval_status tinyint not null comment '1草稿 2待审批 3已批准 4已驳回',
    approval_no varchar(64) null,
    created_by bigint not null,
    approved_by bigint null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_freeze_no(freeze_no),
    key idx_inv_freeze_status_time(freeze_status, updated_at),
    key idx_inv_freeze_source(source_system, source_order_no),
    key idx_inv_freeze_account(stock_id)
) comment '库存冻结单聚合';

create table inv_stock_adjustment (
    stock_adjustment_id bigint not null primary key,
    adjustment_no varchar(64) not null,
    stock_id bigint not null,
    owner_id bigint not null,
    warehouse_id bigint not null,
    sku_code varchar(64) not null,
    batch_no varchar(128) null,
    adjust_qty decimal(18,4) not null,
    adjustment_type varchar(32) not null,
    adjustment_reason varchar(512) not null,
    source_system varchar(32) not null,
    source_order_no varchar(64) not null,
    adjustment_status tinyint not null comment '1草稿 2待审批 3已批准 4已执行 5已驳回 6已取消',
    approval_status tinyint not null comment '1草稿 2待审批 3已批准 4已驳回',
    approval_no varchar(64) null,
    created_by bigint not null,
    approved_by bigint null,
    executed_by bigint null,
    executed_at datetime(3) null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_adjustment_no(adjustment_no),
    key idx_inv_adjustment_status_time(adjustment_status, updated_at),
    key idx_inv_adjustment_source(source_system, source_order_no),
    key idx_inv_adjustment_account(stock_id)
) comment '库存调整单聚合';

create table inv_inventory_command_receipt (
    idempotency_key varchar(128) not null primary key,
    command_type varchar(64) not null,
    request_fingerprint varchar(1024) not null,
    aggregate_no varchar(64) not null,
    created_at datetime(3) not null,
    key idx_inv_command_aggregate(aggregate_no)
) comment '冻结调整命令持久化幂等回执';

create table inv_operation_audit_log (
    operation_log_id bigint not null primary key,
    operator_id bigint not null,
    operation_type varchar(64) not null,
    operation_reason varchar(512) null,
    target_type varchar(64) not null,
    target_id bigint not null,
    target_no varchar(64) not null,
    before_snapshot json not null,
    after_snapshot json not null,
    result tinyint not null comment '1成功 2失败',
    request_id varchar(128) null,
    idempotency_key varchar(128) not null,
    operation_at datetime(3) not null,
    created_at datetime(3) not null,
    key idx_inv_audit_target(target_type, target_no, operation_at),
    key idx_inv_audit_operator(operator_id, operation_at),
    key idx_inv_audit_idempotency(idempotency_key)
) comment '库存操作审计日志';

-- ============================================================================
-- Source: V7__inventory_reliable_event_governance.sql"
-- ============================================================================
alter table inv_outbox_event
    add column event_version varchar(16) not null default '1.0' after event_type,
    add column last_error varchar(1024) null after retry_count,
    add column next_retry_at datetime(3) null after last_error,
    add column published_at datetime(3) null after next_retry_at;

alter table inv_inbox_event
    drop index uk_inv_inbox,
    add column event_version varchar(16) not null default '1.0' after event_type,
    add column aggregate_type varchar(64) null after event_version,
    add column aggregate_id varchar(128) null after aggregate_type,
    add column aggregate_version bigint not null default 0 after aggregate_id,
    add column consumer_name varchar(128) not null default 'inventory-domain-event'
        after aggregate_version,
    add column envelope_json json null after payload_json,
    add column ignored_reason varchar(512) null after last_error,
    add unique key uk_inv_inbox_consumer(source_system, event_code, consumer_name);

create table inv_event_aggregate_cursor (
    source_system varchar(64) not null,
    aggregate_type varchar(64) not null,
    aggregate_id varchar(128) not null,
    consumer_name varchar(128) not null,
    aggregate_version bigint not null,
    event_code varchar(128) not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    primary key(source_system, aggregate_type, aggregate_id, consumer_name)
) comment '库存入站事件聚合顺序游标';

create table inv_event_replay_log (
    replay_id bigint not null auto_increment primary key,
    idempotency_key varchar(128) not null,
    direction varchar(16) not null comment 'INBOUND或OUTBOUND',
    event_code varchar(128) not null,
    replay_reason varchar(512) not null,
    operator_id bigint not null,
    replay_status tinyint not null comment '1处理中 2成功 3失败',
    replay_error varchar(1024) null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_event_replay_idempotency(idempotency_key),
    key idx_inv_event_replay_event(direction, event_code, created_at)
) comment '库存事件人工重放审计';

-- ============================================================================
-- Source: V8__inventory_operations_export.sql"
-- ============================================================================
create table inv_inventory_batch_fact (
    stock_id bigint not null primary key,
    expiry_date date null,
    expiry_source_event varchar(128) not null,
    expiry_fact_at datetime(3) not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    key idx_inv_batch_expiry(expiry_date, stock_id)
) comment 'WMS批次效期事实投影';

create table inv_export_task (
    export_task_id bigint not null auto_increment primary key,
    task_no varchar(64) not null,
    export_type varchar(32) not null,
    query_json json not null,
    owner_scope_json json not null,
    warehouse_scope_json json not null,
    created_by bigint not null,
    idempotency_key varchar(128) not null,
    request_fingerprint varchar(1024) not null,
    task_status tinyint not null comment '1待执行 2处理中 3已完成 4失败',
    retry_count int not null default 0,
    next_retry_at datetime(3) null,
    started_at datetime(3) null,
    completed_at datetime(3) null,
    object_key varchar(512) null,
    file_name varchar(255) null,
    content_type varchar(128) null,
    file_size bigint null,
    last_error varchar(1024) null,
    version int not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_inv_export_task_no(task_no),
    unique key uk_inv_export_idempotency(created_by, idempotency_key),
    key idx_inv_export_dispatch(task_status, next_retry_at, updated_at),
    key idx_inv_export_creator(created_by, created_at)
) comment '库存异步导出任务';

alter table inv_reservation
    add key idx_inv_reservation_scope(stock_id, reservation_status, updated_at);

alter table inv_freeze
    add key idx_inv_freeze_scope(owner_id, warehouse_id, freeze_status, updated_at);

alter table inv_stock_adjustment
    add key idx_inv_adjustment_scope(owner_id, warehouse_id, adjustment_status, updated_at);

-- ============================================================================
-- Source: V9__stock_transfer_difference_evidence.sql"
-- ============================================================================
alter table inv_stock_transfer
    add column difference_reason varchar(500) null after difference_qty,
    add column responsible_party varchar(64) null after difference_reason,
    add column evidence_ref varchar(255) null after responsible_party;

-- ============================================================================
-- Source: V10__inventory_dubbo_supplier_return_lock.sql"
-- ============================================================================
CREATE TABLE inventory_supplier_return_lock (
    return_id BIGINT NOT NULL,
    lock_no VARCHAR(64) NOT NULL,
    return_no VARCHAR(64) NOT NULL,
    supplier_id BIGINT NOT NULL,
    warehouse_id BIGINT NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    lock_status TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (return_id),
    UNIQUE KEY uk_inventory_return_lock_no (lock_no)
);

CREATE TABLE inventory_supplier_return_lock_line (
    return_id BIGINT NOT NULL,
    source_line_id BIGINT NOT NULL,
    freeze_no VARCHAR(64) NOT NULL,
    locked_quantity DECIMAL(18,6) NOT NULL,
    freeze_version INT NOT NULL,
    PRIMARY KEY (return_id, source_line_id),
    UNIQUE KEY uk_inventory_return_freeze (freeze_no)
);

CREATE TABLE inventory_dubbo_receipt (
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    reference_no VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (idempotency_key)
);

SET FOREIGN_KEY_CHECKS = 1;

