create table bms_external_task (
    id bigint primary key auto_increment,
    task_no varchar(64) not null,
    task_type varchar(32) not null,
    business_no varchar(64) not null,
    idempotency_key varchar(128) not null,
    status tinyint not null,
    attempt_count int not null default 0,
    max_attempts int not null,
    next_retry_at datetime(3) null,
    last_error varchar(500) null,
    external_ref varchar(128) null,
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_bms_external_task_no (task_no),
    unique key uk_bms_external_task_idem (idempotency_key),
    key idx_bms_external_task_dispatch (status,next_retry_at,id),
    key idx_bms_external_task_business (task_type,business_no)
);
