-- IAM service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__iam_core.sql"
-- ============================================================================
create table iam_user (
    user_id bigint not null primary key,
    username varchar(64) not null,
    password_hash varchar(128) not null,
    user_status tinyint not null comment '1启用 2停用 3锁定',
    failed_attempts int not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_user_username(username)
) comment 'IAM用户';

create table iam_session (
    session_id bigint not null primary key,
    user_id bigint not null,
    access_token varchar(128) not null,
    refresh_token varchar(128) not null,
    session_status tinyint not null comment '1有效 2失效',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_session_access(access_token),
    unique key uk_iam_session_refresh(refresh_token)
) comment 'IAM会话';

create table iam_role (
    role_id bigint not null primary key,
    role_code varchar(64) not null,
    role_name varchar(128) not null,
    role_status tinyint not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_role_code(role_code)
) comment 'IAM角色';

create table iam_user_role (
    user_id bigint not null,
    role_id bigint not null,
    created_at datetime(3) not null,
    unique key uk_iam_user_role(user_id, role_id)
) comment 'IAM用户角色';

create table iam_permission (
    permission_id bigint not null primary key,
    app_code varchar(64) not null,
    permission_code varchar(128) not null,
    permission_name varchar(128) not null,
    created_at datetime(3) not null,
    unique key uk_iam_permission_code(permission_code)
) comment 'IAM权限点';

create table iam_role_permission (
    role_id bigint not null,
    permission_code varchar(128) not null,
    created_at datetime(3) not null,
    unique key uk_iam_role_permission(role_id, permission_code)
) comment 'IAM角色权限';

create table iam_data_scope (
    scope_id bigint not null primary key,
    role_id bigint not null,
    scope_type varchar(32) not null,
    scope_value varchar(128) not null,
    created_at datetime(3) not null,
    key idx_iam_data_scope_role(role_id)
) comment 'IAM数据权限';

create table iam_approval (
    approval_id bigint not null primary key,
    approval_no varchar(64) not null,
    business_type varchar(64) not null,
    business_no varchar(64) not null,
    approval_status tinyint not null comment '1待审批 2已通过 3已驳回',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_approval_no(approval_no)
) comment 'IAM审批实例';

create table iam_operation_log (
    log_id bigint not null primary key,
    operation varchar(128) not null,
    target_no varchar(128) not null,
    created_at datetime(3) not null,
    key idx_iam_operation_target(target_no, created_at)
) comment 'IAM操作日志';

create table iam_security_policy (
    policy_id bigint not null primary key,
    policy_code varchar(64) not null,
    policy_value varchar(512) not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_policy_code(policy_code)
) comment 'IAM安全策略';

-- ============================================================================
-- Source: V2__iam_jwt_permission_snapshot.sql"
-- ============================================================================
alter table iam_session modify access_token varchar(768) not null;
alter table iam_session modify refresh_token varchar(768) not null;

create table iam_permission_snapshot (
    user_id bigint not null,
    app_code varchar(64) not null,
    role_payload text not null,
    permission_payload text not null,
    data_scope_payload text not null,
    snapshot_status tinyint not null comment '1有效 2失效',
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    primary key(user_id, app_code)
) comment 'IAM权限快照缓存';

create table iam_outbox_event (
    event_id bigint not null primary key,
    event_type varchar(128) not null,
    business_no varchar(128) not null,
    payload text not null,
    event_status tinyint not null comment '1待投递 2已投递 3失败',
    occurred_at datetime(3) not null,
    created_at datetime(3) not null,
    key idx_iam_outbox_status(event_status, event_id)
) comment 'IAM出站事件';

-- ============================================================================
-- Source: V3__iam_app_menu_sso_inbox.sql"
-- ============================================================================
create table iam_app (
    id bigint primary key auto_increment,
    app_code varchar(64) not null,
    app_name varchar(128) not null,
    home_url varchar(512),
    app_status tinyint not null comment '1启用 2停用',
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_app_code(app_code)
) comment 'IAM应用';

create table iam_menu (
    id bigint primary key auto_increment,
    menu_code varchar(128) not null,
    app_code varchar(64) not null,
    parent_code varchar(128),
    menu_name varchar(128) not null,
    route_path varchar(512),
    sort_no int not null,
    menu_status tinyint not null comment '1启用 2停用',
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_menu_code(menu_code),
    key idx_iam_menu_app(app_code, sort_no)
) comment 'IAM菜单';

create table iam_sso_client (
    id bigint primary key auto_increment,
    sso_code varchar(64) not null,
    app_code varchar(64) not null,
    redirect_url varchar(512) not null,
    secret_hash varchar(256) not null,
    sso_status tinyint not null comment '1启用 2停用',
    version bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_sso_code(sso_code),
    key idx_iam_sso_app(app_code)
) comment 'IAM SSO客户端';

create table iam_event_inbox (
    event_id varchar(128) primary key,
    event_type varchar(128) not null,
    business_no varchar(128) not null,
    payload text not null,
    event_status tinyint not null comment '1处理中 2成功 3失败 4忽略',
    error_message varchar(512),
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    key idx_iam_inbox_business(business_no)
) comment 'IAM入站事件';

-- ============================================================================
-- Source: V4__iam_redis_session_rotation.sql"
-- ============================================================================
alter table iam_session
    add column access_jti varchar(128) null after refresh_token,
    add column refresh_jti varchar(128) null after access_jti,
    add column refresh_generation bigint not null default 0 after refresh_jti,
    add column access_expires_at datetime(3) null after refresh_generation,
    add column refresh_expires_at datetime(3) null after access_expires_at,
    add column revoked_at datetime(3) null after refresh_expires_at,
    add column revocation_reason varchar(256) null after revoked_at;

update iam_session
set access_jti = concat('LEGACY-AT-', session_id),
    refresh_jti = concat('LEGACY-RT-', session_id),
    access_expires_at = date_add(updated_at, interval 1 hour),
    refresh_expires_at = date_add(updated_at, interval 1 day)
where access_jti is null;

alter table iam_session
    modify access_jti varchar(128) not null,
    modify refresh_jti varchar(128) not null,
    modify access_expires_at datetime(3) not null,
    modify refresh_expires_at datetime(3) not null,
    add unique key uk_iam_session_access_jti(access_jti),
    add unique key uk_iam_session_refresh_jti(refresh_jti),
    add key idx_iam_session_online(user_id, session_status, refresh_expires_at);

-- ============================================================================
-- Source: V6__iam_mfa_challenge.sql"
-- ============================================================================
create table iam_mfa_challenge (
    challenge_id bigint not null primary key,
    challenge_no varchar(64) not null,
    user_id bigint not null,
    app_code varchar(64) not null,
    factor_type varchar(32) not null comment 'TOTP',
    secret_ciphertext varchar(1024) not null comment 'AES-GCM ciphertext; never plaintext',
    challenge_status varchar(32) not null comment 'PENDING/VERIFIED/LOCKED/EXPIRED',
    failed_attempts int not null,
    max_attempts int not null,
    expires_at datetime(3) not null,
    verified_at datetime(3) null,
    idempotency_key varchar(128) not null,
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_mfa_challenge_no(challenge_no),
    unique key uk_iam_mfa_idempotency(idempotency_key),
    key idx_iam_mfa_user_status(user_id, challenge_status, expires_at)
) comment 'IAM MFA challenge and audit state';

create table iam_mfa_recovery_code (
    recovery_code_id bigint not null primary key,
    user_id bigint not null,
    code_hash varchar(128) not null comment 'SHA-256 hash; never plaintext',
    consumed_at datetime(3) null,
    consumed_challenge_no varchar(64) null,
    created_at datetime(3) not null,
    unique key uk_iam_mfa_recovery_hash(user_id, code_hash),
    key idx_iam_mfa_recovery_unused(user_id, consumed_at)
) comment 'One-time MFA recovery codes';

-- ============================================================================
-- Source: V7__iam_oauth_authorization.sql"
-- ============================================================================
create table iam_oauth_client (
    client_id varchar(128) not null primary key,
    app_code varchar(64) not null,
    client_type varchar(32) not null comment 'PUBLIC or CONFIDENTIAL',
    secret_hash varchar(128),
    redirect_uris text not null comment 'exact-match URI values separated by whitespace',
    grant_types varchar(256) not null,
    allowed_scopes text not null,
    access_ttl_seconds int not null,
    id_token_ttl_seconds int not null,
    client_status tinyint not null comment '1 enabled 2 disabled',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    key idx_iam_oauth_client_app(app_code, client_status)
) comment 'OAuth registered client';

create table iam_oauth_authorization_code (
    code_hash varchar(64) not null primary key,
    client_id varchar(128) not null,
    user_id bigint not null,
    redirect_uri varchar(1024) not null,
    scopes text not null,
    code_challenge varchar(128) not null,
    nonce varchar(256),
    request_id varchar(128) not null,
    issued_at datetime(3) not null,
    expires_at datetime(3) not null,
    consumed_at datetime(3),
    created_at datetime(3) not null,
    unique key uk_iam_oauth_code_request(request_id),
    key idx_iam_oauth_code_expiry(client_id, expires_at, consumed_at)
) comment 'hashed one-time OAuth authorization code';

create table iam_oauth_audit (
    audit_id bigint not null primary key,
    action varchar(128) not null,
    client_id varchar(128) not null,
    user_id bigint,
    request_id varchar(128) not null,
    detail varchar(1024) not null,
    occurred_at datetime(3) not null,
    key idx_iam_oauth_audit_request(request_id, occurred_at),
    key idx_iam_oauth_audit_client(client_id, occurred_at)
) comment 'OAuth security audit trail';

create table iam_oauth_grant (
    grant_id varchar(64) not null primary key,
    client_id varchar(128) not null,
    user_id bigint not null,
    scopes text not null,
    grant_status tinyint not null comment '1 active 2 revoked',
    revoked_at datetime(3),
    created_at datetime(3) not null,
    key idx_iam_oauth_grant_subject(client_id, user_id, grant_status)
) comment 'OAuth durable authorization chain';

create table iam_oauth_refresh_token (
    token_hash varchar(64) not null primary key,
    grant_id varchar(64) not null,
    generation int not null,
    expires_at datetime(3) not null,
    consumed_at datetime(3),
    created_at datetime(3) not null,
    key idx_iam_oauth_refresh_grant(grant_id, generation),
    key idx_iam_oauth_refresh_expiry(expires_at, consumed_at)
) comment 'hashed rotating OAuth refresh token';

-- ============================================================================
-- Source: V8__iam_mfa_governance.sql"
-- ============================================================================
create table iam_mfa_configuration (
    config_id bigint not null primary key,
    user_id bigint not null,
    secret_ciphertext varchar(1024) not null,
    config_status tinyint not null comment '0 pending 1 active 2 disabled',
    version int not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_iam_mfa_configuration_user(user_id)
) comment 'encrypted user MFA configuration';

alter table iam_mfa_challenge
    add column session_id bigint not null after app_code,
    add column purpose varchar(64) not null after session_id,
    add column device_digest varchar(128) not null after purpose;

create table iam_mfa_audit (
    audit_id bigint not null primary key,
    user_id bigint not null,
    action varchar(64) not null,
    challenge_no varchar(64),
    operator_id bigint,
    reason varchar(512) not null,
    occurred_at datetime(3) not null,
    key idx_iam_mfa_audit_user(user_id, occurred_at),
    key idx_iam_mfa_audit_challenge(challenge_no)
) comment 'append-only MFA security audit';

-- ============================================================================
-- Source: V9__iam_rocketmq_delivery.sql"
-- ============================================================================
alter table iam_outbox_event
    add column retry_count int not null default 0 after event_status,
    add column last_error varchar(1000) null after retry_count,
    add column next_retry_at datetime(3) null after last_error,
    add column published_at datetime(3) null after next_retry_at,
    add column updated_at datetime(3) null after created_at,
    add key idx_iam_outbox_retry (event_status, next_retry_at, event_id);

update iam_outbox_event set updated_at=created_at where updated_at is null;

-- ============================================================================
-- Source: V10__iam_dubbo_supplier_scope.sql"
-- ============================================================================
CREATE TABLE iam_user_supplier_scope (
    user_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (user_id, supplier_id),
    KEY idx_iam_user_supplier_scope_supplier (supplier_id)
);

CREATE TABLE iam_dubbo_receipt (
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    reference_no VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (idempotency_key)
);

-- ============================================================================
-- Source: V11__iam_inbound_event_business_projection.sql"
-- ============================================================================
CREATE TABLE iam_inbound_business_projection (
    id BIGINT NOT NULL AUTO_INCREMENT,
    projection_type VARCHAR(64) NOT NULL,
    object_code VARCHAR(128) NOT NULL,
    source_system VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    projection_status VARCHAR(32) NOT NULL,
    payload JSON NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_iam_inbound_projection (projection_type, object_code),
    UNIQUE KEY uk_iam_inbound_projection_event (event_id),
    KEY idx_iam_inbound_projection_status (projection_type, projection_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IAM入站事件授权快照与处置待办';

SET FOREIGN_KEY_CHECKS = 1;

