-- SUPPLIER service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__supplier_asn_vertical_slice.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS `sup_asn` (
  `asn_id` bigint NOT NULL COMMENT 'ASN聚合根ID',
  `asn_no` varchar(64) NOT NULL COMMENT 'ASN单号',
  `purchase_order_id` bigint NOT NULL COMMENT '采购订单事实快照ID',
  `supplier_id` bigint NOT NULL COMMENT '发货供应商ID',
  `warehouse_id` bigint NOT NULL COMMENT '目的仓ID',
  `eta` datetime(3) NOT NULL COMMENT '预计到仓时间',
  `ship_at` datetime(3) NULL COMMENT '发货时间',
  `carrier_name` varchar(128) NULL COMMENT '承运商快照',
  `tracking_no` varchar(128) NULL COMMENT '运单号快照',
  `asn_status` smallint NOT NULL COMMENT '1草稿 2已提交 3已预约 4已发货 5已到仓 6已收货 7已取消 8已关闭',
  `cancel_reason` varchar(512) NULL COMMENT '取消原因',
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`asn_id`),
  UNIQUE KEY `uk_sup_asn_no` (`asn_no`),
  KEY `idx_sup_asn_supplier_status` (`supplier_id`, `asn_status`, `updated_at`),
  KEY `idx_sup_asn_purchase_order` (`purchase_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ASN聚合根';

CREATE TABLE IF NOT EXISTS `sup_asn_line` (
  `asn_line_id` bigint NOT NULL,
  `asn_id` bigint NOT NULL COMMENT '所属ASN聚合根ID',
  `sku_code` varchar(64) NOT NULL,
  `planned_qty` decimal(18,4) NOT NULL,
  `received_qty` decimal(18,4) NOT NULL DEFAULT 0,
  `batch_no` varchar(128) NULL,
  `production_date` date NULL,
  `expire_date` date NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`asn_line_id`),
  KEY `idx_sup_asn_line_asn` (`asn_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ASN聚合内部行';

CREATE TABLE IF NOT EXISTS `sup_domain_event` (
  `event_id` bigint NOT NULL,
  `event_code` varchar(128) NOT NULL,
  `event_name` varchar(128) NOT NULL,
  `event_type` varchar(128) NOT NULL,
  `aggregate_type` varchar(128) NOT NULL,
  `aggregate_id` bigint NOT NULL,
  `aggregate_no` varchar(128) NULL,
  `source_system` varchar(64) NOT NULL,
  `payload_json` json NOT NULL,
  `event_status` smallint NOT NULL DEFAULT 1 COMMENT '1待发布 2发布中 3已发布 4发布失败 5已取消',
  `retry_count` int NOT NULL DEFAULT 0,
  `fail_reason` varchar(1024) NULL,
  `occurred_at` datetime(3) NOT NULL,
  `published_at` datetime(3) NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `uk_sup_domain_event_code` (`event_code`),
  KEY `idx_sup_domain_event_status` (`event_status`, `created_at`),
  KEY `idx_sup_domain_event_aggregate` (`aggregate_type`, `aggregate_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='领域事件发布表';

CREATE TABLE IF NOT EXISTS `sup_operation_audit_log` (
  `operation_log_id` bigint NOT NULL,
  `operator_id` bigint NOT NULL,
  `operator_name` varchar(128) NULL,
  `operation_type` varchar(64) NOT NULL,
  `target_type` varchar(128) NOT NULL,
  `target_id` bigint NULL,
  `target_no` varchar(128) NULL,
  `before_snapshot` json NULL,
  `after_snapshot` json NULL,
  `result` smallint NOT NULL DEFAULT 1,
  `fail_reason` varchar(1024) NULL,
  `request_id` varchar(128) NULL,
  `operation_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`operation_log_id`),
  KEY `idx_sup_operation_audit_target` (`target_type`, `target_id`),
  KEY `idx_sup_operation_audit_operator` (`operator_id`, `operation_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作审计日志';

-- ============================================================================
-- Source: V2__supplier_profile_item_and_po_confirm.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS `sup_supplier_profile_snapshot` (
  `supplier_id` bigint NOT NULL,
  `supplier_code` varchar(64) NOT NULL,
  `supplier_name` varchar(256) NOT NULL,
  `lifecycle_status` smallint NOT NULL,
  `risk_level` smallint NOT NULL DEFAULT 1,
  `profile_json` json NOT NULL COMMENT '主数据系统供应商档案本地快照',
  `source_version` bigint NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  PRIMARY KEY (`supplier_id`),
  UNIQUE KEY `uk_sup_profile_code` (`supplier_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商主数据本地快照';

CREATE TABLE IF NOT EXISTS `sup_supplier_profile_change` (
  `change_id` bigint NOT NULL,
  `change_no` varchar(64) NOT NULL,
  `supplier_id` bigint NOT NULL,
  `profile_version` int NOT NULL COMMENT '申请时档案版本',
  `change_reason` varchar(512) NOT NULL,
  `changed_fields_json` json NOT NULL,
  `change_status` smallint NOT NULL COMMENT '1待审批 2已撤回 3已通过 4已驳回',
  `withdraw_reason` varchar(512) NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`change_id`),
  UNIQUE KEY `uk_sup_profile_change_no` (`change_no`),
  KEY `idx_sup_profile_change_supplier` (`supplier_id`,`change_status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商资料变更申请';

CREATE TABLE IF NOT EXISTS `sup_supplier_item` (
  `supplier_item_id` bigint NOT NULL,
  `supplier_id` bigint NOT NULL,
  `sku_code` varchar(64) NOT NULL,
  `supplier_sku_code` varchar(128) NULL,
  `moq` decimal(18,4) NOT NULL,
  `mpq` decimal(18,4) NOT NULL,
  `lead_time_days` int NOT NULL,
  `purchase_unit` varchar(32) NOT NULL,
  `supply_status` smallint NOT NULL COMMENT '1可供 2暂停 3停供',
  `pause_reason` varchar(512) NULL,
  `effective_from` date NULL,
  `effective_to` date NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`supplier_item_id`),
  UNIQUE KEY `uk_sup_item_supplier_sku` (`supplier_id`,`sku_code`),
  KEY `idx_sup_item_status` (`supplier_id`,`supply_status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商商品供货关系';

CREATE TABLE IF NOT EXISTS `sup_order` (
  `order_id` bigint NOT NULL,
  `confirm_no` varchar(64) NOT NULL,
  `purchase_order_id` bigint NOT NULL,
  `purchase_order_no` varchar(64) NOT NULL,
  `supplier_id` bigint NOT NULL,
  `confirm_status` smallint NOT NULL COMMENT '1待确认 2已确认 3差异待处理 4已拒绝 5已关闭',
  `confirm_deadline` datetime(3) NULL,
  `confirmed_at` datetime(3) NULL,
  `diff_type` smallint NULL,
  `reason_code` smallint NULL,
  `remark` varchar(512) NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `uk_sup_order_confirm_no` (`confirm_no`),
  UNIQUE KEY `uk_sup_order_purchase_id` (`purchase_order_id`),
  KEY `idx_sup_order_supplier_status` (`supplier_id`,`confirm_status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购订单确认协同聚合';

CREATE TABLE IF NOT EXISTS `sup_order_line` (
  `order_line_id` bigint NOT NULL,
  `order_id` bigint NOT NULL,
  `sku_code` varchar(64) NOT NULL,
  `order_qty` decimal(18,4) NOT NULL,
  `confirmed_qty` decimal(18,4) NULL,
  `requested_delivery_date` date NULL,
  `confirmed_delivery_date` date NULL,
  `line_status` smallint NOT NULL COMMENT '1待确认 2已确认 3有差异 4已拒绝',
  `diff_reason` varchar(512) NULL,
  `created_by` bigint NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` bigint NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `version` int NOT NULL DEFAULT 0,
  `deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_line_id`),
  KEY `idx_sup_order_line_order` (`order_id`,`line_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='采购订单确认协同行';

-- ============================================================================
-- Source: V3__master_data_snapshots_and_consume_log.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS `sup_sku_availability_snapshot` (
  `sku_code` varchar(64) NOT NULL,
  `sku_name` varchar(256) NOT NULL,
  `sku_status` smallint NOT NULL COMMENT '1已启用 2已停用',
  `base_unit` varchar(32) NULL,
  `category_id` bigint NULL,
  `snapshot_json` json NOT NULL COMMENT '主数据系统SKU本地快照',
  `source_version` bigint NOT NULL DEFAULT 0,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`sku_code`),
  KEY `idx_sup_sku_available` (`sku_status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SKU可用性本地快照';

CREATE TABLE IF NOT EXISTS `sup_event_consume_log` (
  `consume_log_id` bigint NOT NULL AUTO_INCREMENT,
  `source_system` varchar(64) NOT NULL,
  `event_code` varchar(128) NOT NULL,
  `event_type` varchar(128) NOT NULL,
  `consumer_name` varchar(128) NOT NULL,
  `idempotent_key` varchar(256) NOT NULL,
  `consume_status` smallint NOT NULL COMMENT '1处理中 2成功 3失败 4忽略',
  `retry_count` int NOT NULL DEFAULT 0,
  `fail_reason` varchar(1000) NULL,
  `consumed_at` datetime(3) NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`consume_log_id`),
  UNIQUE KEY `uk_sup_consume_event` (`source_system`,`event_code`,`consumer_name`),
  UNIQUE KEY `uk_sup_consume_idempotent` (`consumer_name`,`idempotent_key`),
  KEY `idx_sup_consume_status` (`consume_status`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='外部事件消费收件箱';

-- ============================================================================
-- Source: V4__supplier_quote.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_supplier_quote (
  quote_id bigint NOT NULL, quote_no varchar(64) NOT NULL, supplier_id bigint NOT NULL,
  rfq_id bigint NULL, rfq_no varchar(64) NULL, currency varchar(8) NOT NULL,
  valid_from date NOT NULL, valid_to date NOT NULL, quote_status smallint NOT NULL COMMENT '1草稿 2已提交 3已确认 4已采纳 5已拒绝 6已作废 7已过期',
  rejection_reason varchar(512) NULL, price_agreement_ref varchar(64) NULL, attachment_url varchar(512) NULL,
  created_by bigint NOT NULL, created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_by bigint NULL,
  updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version int NOT NULL DEFAULT 0, deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (quote_id), UNIQUE KEY uk_sup_quote_no (quote_no), KEY idx_sup_quote_supplier_status (supplier_id,quote_status,updated_at), KEY idx_sup_quote_rfq (rfq_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商报价聚合';
CREATE TABLE IF NOT EXISTS sup_supplier_quote_line (
  quote_line_id bigint NOT NULL, quote_id bigint NOT NULL, sku_code varchar(64) NOT NULL, quote_qty decimal(18,4) NOT NULL,
  unit_price decimal(18,6) NOT NULL, tax_rate decimal(5,2) NOT NULL, delivery_days int NOT NULL, moq decimal(18,4) NOT NULL,
  created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version int NOT NULL DEFAULT 0, deleted tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (quote_line_id), UNIQUE KEY uk_sup_quote_line_sku (quote_id,sku_code), KEY idx_sup_quote_line_quote (quote_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商报价行';

-- ============================================================================
-- Source: V5__supplier_contract.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_supplier_contract (
 contract_id bigint NOT NULL,contract_no varchar(64) NOT NULL,supplier_id bigint NOT NULL,quote_id bigint NULL,price_agreement_ref varchar(64) NULL,contract_type varchar(32) NOT NULL,contract_status smallint NOT NULL COMMENT '1草稿 2审批中 3已生效 4已终止 5已到期',effective_from date NOT NULL,effective_to date NOT NULL,terms_json json NOT NULL,attachment_url varchar(512) NULL,termination_reason varchar(512) NULL,created_by bigint NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_by bigint NULL,updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,deleted tinyint NOT NULL DEFAULT 0,
 PRIMARY KEY(contract_id),UNIQUE KEY uk_sup_contract_no(contract_no),KEY idx_sup_contract_supplier_status(supplier_id,contract_status,effective_to),KEY idx_sup_contract_quote(quote_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商合同聚合';

-- ============================================================================
-- Source: V6__price_agreement_projection.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_price_agreement (
 agreement_id bigint NOT NULL AUTO_INCREMENT,agreement_ref varchar(64) NOT NULL,contract_id bigint NOT NULL,quote_id bigint NOT NULL,supplier_id bigint NOT NULL,currency varchar(8) NOT NULL,effective_from date NOT NULL,effective_to date NOT NULL,agreement_status smallint NOT NULL COMMENT '1生效 2终止',source_contract_version int NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(agreement_id),UNIQUE KEY uk_sup_agreement_ref(agreement_ref),UNIQUE KEY uk_sup_agreement_contract(contract_id),KEY idx_sup_agreement_lookup(supplier_id,agreement_status,effective_from,effective_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='合同生效价格协议读模型';
CREATE TABLE IF NOT EXISTS sup_price_agreement_line (
 agreement_line_id bigint NOT NULL AUTO_INCREMENT,agreement_id bigint NOT NULL,sku_code varchar(64) NOT NULL,unit_price decimal(18,6) NOT NULL,tax_rate decimal(5,2) NOT NULL,moq decimal(18,4) NOT NULL,delivery_days int NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(agreement_line_id),UNIQUE KEY uk_sup_agreement_line(agreement_id,sku_code),KEY idx_sup_agreement_sku(sku_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='价格协议SKU行读模型';

-- ============================================================================
-- Source: V7__supplier_qualification_contact_account.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_supplier_qualification (
 qualification_id bigint NOT NULL,supplier_id bigint NOT NULL,qualification_type varchar(32) NOT NULL,qualification_no varchar(128) NOT NULL,valid_from date NOT NULL,valid_to date NOT NULL,attachment_url varchar(512) NOT NULL,qualification_status smallint NOT NULL COMMENT '1待审核 2有效 3已驳回 4已失效',review_remark varchar(512) NULL,created_by bigint NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_by bigint NULL,updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,deleted tinyint NOT NULL DEFAULT 0,PRIMARY KEY(qualification_id),UNIQUE KEY uk_sup_qualification(supplier_id,qualification_type,qualification_no),KEY idx_sup_qualification_expiry(supplier_id,qualification_status,valid_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商资质';
CREATE TABLE IF NOT EXISTS sup_supplier_contact (
 contact_id bigint NOT NULL,supplier_id bigint NOT NULL,contact_name varchar(128) NOT NULL,mobile varchar(32) NOT NULL,email varchar(128) NULL,contact_role varchar(32) NOT NULL,is_primary tinyint NOT NULL DEFAULT 0,status smallint NOT NULL DEFAULT 1,created_by bigint NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_by bigint NULL,updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,deleted tinyint NOT NULL DEFAULT 0,PRIMARY KEY(contact_id),KEY idx_sup_contact_supplier(supplier_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商联系人';
CREATE TABLE IF NOT EXISTS sup_supplier_user_binding (
 supplier_user_id bigint NOT NULL,supplier_id bigint NOT NULL,user_id bigint NOT NULL,binding_role varchar(32) NOT NULL,is_primary tinyint NOT NULL DEFAULT 0,status smallint NOT NULL DEFAULT 1,bound_by bigint NOT NULL,bound_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),unbound_at datetime(3) NULL,version int NOT NULL DEFAULT 0,PRIMARY KEY(supplier_user_id),UNIQUE KEY uk_sup_user_binding(supplier_id,user_id),KEY idx_sup_user_lookup(user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商用户绑定';

-- ============================================================================
-- Source: V8__supplier_admission.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_supplier_admission (
 admission_id bigint NOT NULL,admission_no varchar(64) NOT NULL,candidate_supplier_code varchar(64) NOT NULL,candidate_supplier_name varchar(256) NOT NULL,tax_no varchar(64) NOT NULL,supplier_type varchar(32) NOT NULL,admission_status smallint NOT NULL COMMENT '1潜在 2待审核 3已通过 4已驳回 5已撤回',contact_name varchar(128) NOT NULL,contact_mobile varchar(32) NOT NULL,settlement_json json NOT NULL,reject_reason varchar(512) NULL,created_by bigint NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_by bigint NULL,updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,deleted tinyint NOT NULL DEFAULT 0,PRIMARY KEY(admission_id),UNIQUE KEY uk_sup_admission_no(admission_no),UNIQUE KEY uk_sup_admission_tax(tax_no),KEY idx_sup_admission_status(admission_status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商准入协同单';

-- ============================================================================
-- Source: V9__supplier_quote_todo.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_supplier_quote_todo (
 todo_id bigint NOT NULL,rfq_id bigint NOT NULL,rfq_no varchar(64) NOT NULL,supplier_id bigint NOT NULL,quote_deadline datetime(3) NULL,todo_status smallint NOT NULL COMMENT '1待报价 2已提交 3已关闭',rfq_snapshot_json json NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,PRIMARY KEY(todo_id),UNIQUE KEY uk_sup_quote_todo(rfq_id,supplier_id),KEY idx_sup_quote_todo_status(supplier_id,todo_status,quote_deadline)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商报价待办';

-- ============================================================================
-- Source: V10__asn_transport_fact.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_asn_transport_fact (
 transport_fact_id bigint NOT NULL AUTO_INCREMENT,asn_id bigint NOT NULL,shipment_id bigint NULL,waybill_no varchar(64) NULL,carrier_code varchar(64) NULL,transport_status smallint NOT NULL COMMENT '1待发运 2运输中 3已到达 4异常',last_node varchar(256) NULL,last_track_at datetime(3) NULL,exception_code varchar(64) NULL,exception_reason varchar(512) NULL,source_version bigint NOT NULL DEFAULT 0,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),PRIMARY KEY(transport_fact_id),UNIQUE KEY uk_sup_asn_transport(asn_id),KEY idx_sup_transport_waybill(waybill_no,transport_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ASN运输事实快照';

-- ============================================================================
-- Source: V11__supplier_quality_issue.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_quality_issue (
 quality_issue_id bigint NOT NULL,issue_no varchar(64) NOT NULL,supplier_id bigint NOT NULL,source_type varchar(32) NOT NULL,source_no varchar(64) NULL,issue_type varchar(32) NOT NULL,severity smallint NOT NULL,issue_description varchar(1024) NOT NULL,issue_status smallint NOT NULL COMMENT '1待处理 2整改中 3待审核 4已关闭 5已逾期',rectification_deadline datetime(3) NULL,rectification_plan text NULL,verification_comment varchar(512) NULL,created_by bigint NOT NULL,created_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),updated_by bigint NULL,updated_at datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),version int NOT NULL DEFAULT 0,deleted tinyint NOT NULL DEFAULT 0,PRIMARY KEY(quality_issue_id),UNIQUE KEY uk_sup_quality_issue_no(issue_no),KEY idx_sup_quality_supplier_status(supplier_id,issue_status,rectification_deadline),KEY idx_sup_quality_source(source_type,source_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商质量问题聚合';

-- ============================================================================
-- Source: V12__supplier_return.sql"
-- ============================================================================
CREATE TABLE sup_supplier_return (
  return_id BIGINT PRIMARY KEY,
  return_no VARCHAR(32) NOT NULL,
  supplier_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  source_quality_issue_id BIGINT NULL,
  return_reason VARCHAR(500) NOT NULL,
  return_status TINYINT NOT NULL,
  inventory_lock_no VARCHAR(64) NULL,
  supplier_confirmed_at DATETIME(3) NULL,
  outbound_no VARCHAR(64) NULL,
  shipment_id VARCHAR(64) NULL,
  waybill_no VARCHAR(64) NULL,
  carrier_code VARCHAR(32) NULL,
  settlement_completed TINYINT NOT NULL DEFAULT 0,
  settlement_ref VARCHAR(64) NULL,
  offset_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  claim_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  exception_reason VARCHAR(500) NULL,
  created_by BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_supplier_return_no(return_no),
  KEY idx_supplier_return_supplier_status(supplier_id, return_status),
  KEY idx_supplier_return_quality(source_quality_issue_id)
);

CREATE TABLE sup_supplier_return_line (
  return_line_id BIGINT PRIMARY KEY,
  return_id BIGINT NOT NULL,
  sku_code VARCHAR(64) NOT NULL,
  batch_no VARCHAR(64) NULL,
  inventory_status VARCHAR(32) NOT NULL,
  requested_qty DECIMAL(18,4) NOT NULL,
  locked_qty DECIMAL(18,4) NOT NULL DEFAULT 0,
  outbound_qty DECIMAL(18,4) NOT NULL DEFAULT 0,
  signed_qty DECIMAL(18,4) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_supplier_return_line(return_id, sku_code, batch_no, inventory_status),
  KEY idx_supplier_return_line_return(return_id)
);

-- ============================================================================
-- Source: V13__supplier_finance_and_score.sql"
-- ============================================================================
CREATE TABLE sup_reconciliation (
  reconciliation_id BIGINT PRIMARY KEY, statement_no VARCHAR(64) NOT NULL, supplier_id BIGINT NOT NULL,
  currency VARCHAR(3) NOT NULL, statement_amount DECIMAL(18,2) NOT NULL, confirmed_amount DECIMAL(18,2) NULL,
  status TINYINT NOT NULL COMMENT '1待确认 2已确认 3差异中 4已撤回 5已关闭', difference_reason VARCHAR(500) NULL,
  source_version INT NOT NULL DEFAULT 0, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0, deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sup_reconciliation_no(statement_no), KEY idx_sup_reconciliation_supplier(supplier_id,status)
);
CREATE TABLE sup_invoice_collaboration (
  invoice_id BIGINT PRIMARY KEY, invoice_no VARCHAR(64) NOT NULL, supplier_id BIGINT NOT NULL, reconciliation_id BIGINT NULL,
  invoice_type TINYINT NOT NULL COMMENT '1专票 2普票 3红字票', amount_excluding_tax DECIMAL(18,2) NOT NULL, tax_amount DECIMAL(18,2) NOT NULL, tax_rate DECIMAL(8,4) NOT NULL,
  attachment_url VARCHAR(500) NOT NULL, status TINYINT NOT NULL COMMENT '1待校验 2校验通过 3待补充 4已关闭', validation_message VARCHAR(500) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0, deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sup_invoice_no(invoice_no), KEY idx_sup_invoice_supplier(supplier_id,status)
);
CREATE TABLE sup_performance_fact (
  fact_id BIGINT PRIMARY KEY, event_code VARCHAR(64) NOT NULL, supplier_id BIGINT NOT NULL, dimension_code VARCHAR(32) NOT NULL,
  metric_code VARCHAR(64) NOT NULL, metric_value DECIMAL(18,6) NOT NULL, occurred_at DATETIME(3) NOT NULL, source_system VARCHAR(32) NOT NULL, source_no VARCHAR(64) NULL,
  payload_json JSON NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY uk_sup_performance_event(event_code), KEY idx_sup_performance_period(supplier_id,occurred_at,dimension_code)
);
CREATE TABLE sup_score_rule (
  rule_id BIGINT PRIMARY KEY, rule_name VARCHAR(128) NOT NULL, dimension_code VARCHAR(32) NOT NULL, metric_code VARCHAR(64) NOT NULL,
  weight DECIMAL(8,4) NOT NULL, target_value DECIMAL(18,6) NOT NULL, score_direction TINYINT NOT NULL COMMENT '1越大越好 2越小越好', status TINYINT NOT NULL COMMENT '1草稿 2已发布 3已停用',
  effective_from DATE NOT NULL, effective_to DATE NULL, created_by BIGINT NOT NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_by BIGINT NOT NULL, updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0
);
CREATE TABLE sup_score_result (
  score_result_id BIGINT PRIMARY KEY, supplier_id BIGINT NOT NULL, period_code VARCHAR(16) NOT NULL, total_score DECIMAL(8,2) NOT NULL,
  dimension_scores_json JSON NOT NULL, fact_summary_json JSON NOT NULL, manual_adjustment DECIMAL(8,2) NOT NULL DEFAULT 0, adjustment_reason VARCHAR(500) NULL,
  status TINYINT NOT NULL COMMENT '1待发布 2已发布', published_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sup_score_period(supplier_id,period_code)
);
CREATE TABLE sup_risk_recommendation (
  recommendation_id BIGINT PRIMARY KEY, supplier_id BIGINT NOT NULL, score_result_id BIGINT NOT NULL, risk_level TINYINT NOT NULL COMMENT '1提醒 2预警 3高风险',
  recommendation_type TINYINT NOT NULL COMMENT '1整改 2限制供货 3冻结建议', reason VARCHAR(500) NOT NULL, status TINYINT NOT NULL COMMENT '1待处理 2已接受 3已驳回 4已关闭',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0, KEY idx_sup_risk_supplier(supplier_id,status)
);

-- ============================================================================
-- Source: V14__supplier_operations.sql"
-- ============================================================================
CREATE TABLE sup_work_item (
  work_item_id BIGINT PRIMARY KEY, work_type VARCHAR(32) NOT NULL, supplier_id BIGINT NOT NULL, business_type VARCHAR(32) NOT NULL, business_id BIGINT NOT NULL, business_no VARCHAR(64) NULL,
  title VARCHAR(200) NOT NULL, assignee_type TINYINT NOT NULL COMMENT '1内部角色 2供应商', due_at DATETIME(3) NULL, status TINYINT NOT NULL COMMENT '1待处理 2处理中 3已完成 4已关闭', source_event_code VARCHAR(64) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sup_work_event(source_event_code,work_type), KEY idx_sup_work_supplier(supplier_id,status,due_at)
);
CREATE TABLE sup_warning (
  warning_id BIGINT PRIMARY KEY, warning_type VARCHAR(32) NOT NULL, supplier_id BIGINT NOT NULL, business_type VARCHAR(32) NOT NULL, business_id BIGINT NOT NULL,
  warning_level TINYINT NOT NULL COMMENT '1提醒 2预警 3严重', warning_message VARCHAR(500) NOT NULL, occurred_at DATETIME(3) NOT NULL, status TINYINT NOT NULL COMMENT '1待确认 2已确认 3已关闭', source_event_code VARCHAR(64) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sup_warning_event(source_event_code,warning_type), KEY idx_sup_warning_supplier(supplier_id,status,warning_level)
);
CREATE TABLE sup_data_reconciliation (
  reconciliation_job_id BIGINT PRIMARY KEY, reconciliation_type VARCHAR(32) NOT NULL, target_system VARCHAR(32) NOT NULL, business_date DATE NOT NULL,
  local_count BIGINT NOT NULL, remote_count BIGINT NOT NULL, local_amount DECIMAL(18,2) NULL, remote_amount DECIMAL(18,2) NULL,
  difference_detail VARCHAR(1000) NULL, status TINYINT NOT NULL COMMENT '1一致 2存在差异 3已处理', created_by BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sup_data_reconciliation(reconciliation_type,target_system,business_date)
);

-- ============================================================================
-- Source: V15__integration_command_outbox.sql"
-- ============================================================================
CREATE TABLE sup_integration_command (
  command_id BIGINT PRIMARY KEY, command_code VARCHAR(64) NOT NULL, command_type VARCHAR(64) NOT NULL,
  aggregate_type VARCHAR(32) NOT NULL, aggregate_id BIGINT NOT NULL, aggregate_version INT NOT NULL,
  target_system VARCHAR(32) NOT NULL, payload_json JSON NOT NULL,
  command_status TINYINT NOT NULL COMMENT '1待执行 2执行中 3成功 4失败 5待人工处理 6已取消',
  retry_count INT NOT NULL DEFAULT 0, next_retry_at DATETIME(3) NULL, remote_reference VARCHAR(128) NULL,
  fail_reason VARCHAR(1000) NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), completed_at DATETIME(3) NULL,
  UNIQUE KEY uk_sup_integration_command_code(command_code),
  UNIQUE KEY uk_sup_integration_business(command_type,aggregate_id,aggregate_version),
  KEY idx_sup_integration_dispatch(command_status,next_retry_at,created_at)
);

-- ============================================================================
-- Source: V16__purchase_order_lifecycle.sql"
-- ============================================================================
ALTER TABLE sup_order ADD COLUMN source_version INT NOT NULL DEFAULT 1 AFTER remark;
CREATE INDEX idx_sup_order_source_version ON sup_order(purchase_order_id,source_version);

-- ============================================================================
-- Source: V17__inbox_replay_payload.sql"
-- ============================================================================
ALTER TABLE sup_event_consume_log
  ADD COLUMN payload_json JSON NULL AFTER idempotent_key,
  ADD COLUMN replay_count INT NOT NULL DEFAULT 0 AFTER retry_count,
  ADD COLUMN last_replayed_by BIGINT NULL AFTER fail_reason,
  ADD COLUMN last_replayed_at DATETIME(3) NULL AFTER last_replayed_by;

-- ============================================================================
-- Source: V18__admission_registration_projection.sql"
-- ============================================================================
CREATE TABLE sup_admission_registration (
  admission_id BIGINT PRIMARY KEY,
  supplier_id BIGINT NOT NULL,
  supplier_code VARCHAR(64) NOT NULL,
  registration_status TINYINT NOT NULL COMMENT '1已建档 2建档失败',
  source_event_code VARCHAR(128) NOT NULL,
  source_version BIGINT NOT NULL,
  failure_reason VARCHAR(500) NULL,
  registered_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_sup_admission_registration_supplier(supplier_id),
  UNIQUE KEY uk_sup_admission_registration_event(source_event_code)
);

-- ============================================================================
-- Source: V19__qualification_requirement.sql"
-- ============================================================================
CREATE TABLE sup_qualification_requirement (
  requirement_id BIGINT PRIMARY KEY,
  supplier_type VARCHAR(32) NULL,
  category_id BIGINT NULL,
  qualification_type VARCHAR(32) NOT NULL,
  mandatory TINYINT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by BIGINT NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_sup_qualification_requirement(supplier_type,category_id,qualification_type),
  KEY idx_sup_qualification_requirement_scope(status,category_id)
);

-- ============================================================================
-- Source: V20__supplier_item_history.sql"
-- ============================================================================
CREATE TABLE sup_supplier_item_condition_history (
  history_id BIGINT PRIMARY KEY,
  supplier_item_id BIGINT NOT NULL,
  supplier_id BIGINT NOT NULL,
  sku_code VARCHAR(64) NOT NULL,
  supplier_sku_code VARCHAR(64) NULL,
  moq DECIMAL(18,4) NOT NULL,
  mpq DECIMAL(18,4) NOT NULL,
  lead_time_days INT NOT NULL,
  purchase_unit VARCHAR(32) NOT NULL,
  effective_from DATE NULL,
  effective_to DATE NULL,
  condition_version INT NOT NULL,
  change_type VARCHAR(32) NOT NULL,
  changed_by BIGINT NOT NULL,
  changed_at DATETIME(3) NOT NULL,
  KEY idx_sup_item_condition_history(supplier_item_id,changed_at)
);
CREATE TABLE sup_supplier_item_price_snapshot (
  snapshot_id BIGINT PRIMARY KEY,
  supplier_id BIGINT NOT NULL,
  sku_code VARCHAR(64) NOT NULL,
  agreement_ref VARCHAR(64) NOT NULL,
  currency VARCHAR(8) NOT NULL,
  unit_price DECIMAL(18,6) NOT NULL,
  tax_rate DECIMAL(5,2) NOT NULL,
  effective_from DATE NOT NULL,
  effective_to DATE NOT NULL,
  source_contract_id BIGINT NOT NULL,
  source_quote_id BIGINT NOT NULL,
  source_version INT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uk_sup_item_price_snapshot(agreement_ref,sku_code,source_version),
  KEY idx_sup_item_price_lookup(supplier_id,sku_code,effective_from,effective_to)
);

-- ============================================================================
-- Source: V21__supplier_quality_evidence.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_quality_issue_evidence (
 evidence_id BIGINT NOT NULL, quality_issue_id BIGINT NOT NULL, evidence_type VARCHAR(32) NOT NULL COMMENT '1检验报告 2图片视频 3整改附件 4验证附件 5责任认定',
 attachment_url VARCHAR(512) NULL, content VARCHAR(1000) NULL, created_by BIGINT NOT NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(evidence_id), KEY idx_sup_quality_evidence_issue(quality_issue_id,evidence_type,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商质量问题证据与处理附件';

-- ============================================================================
-- Source: V22__asn_receipt_line.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_asn_receipt_line (
 receipt_line_id BIGINT NOT NULL, asn_id BIGINT NOT NULL, asn_line_id BIGINT NOT NULL, received_qty DECIMAL(18,4) NOT NULL, rejected_qty DECIMAL(18,4) NOT NULL,
 quality_status TINYINT NOT NULL COMMENT '1待检 2合格 3不合格', quality_reason VARCHAR(512) NULL, source_event_code VARCHAR(128) NOT NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(receipt_line_id), UNIQUE KEY uk_sup_asn_receipt_source(source_event_code,asn_line_id), KEY idx_sup_asn_receipt_asn(asn_id,asn_line_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ASN行级收货与质检事实';

-- ============================================================================
-- Source: V23__supplier_contract_version_history.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_supplier_contract_version_history (
 history_id BIGINT NOT NULL AUTO_INCREMENT, contract_id BIGINT NOT NULL, contract_version INT NOT NULL, effective_to DATE NOT NULL, terms_json JSON NOT NULL, attachment_url VARCHAR(512) NULL, contract_status TINYINT NOT NULL, changed_by BIGINT NOT NULL, changed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY(history_id), UNIQUE KEY uk_sup_contract_version_history(contract_id,contract_version), KEY idx_sup_contract_history(contract_id,changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='供应商合同版本历史快照';

-- ============================================================================
-- Source: V24__asn_transport_trail.sql"
-- ============================================================================
CREATE TABLE IF NOT EXISTS sup_asn_transport_trail (trail_id BIGINT NOT NULL AUTO_INCREMENT,asn_id BIGINT NOT NULL,shipment_id BIGINT NULL,waybill_no VARCHAR(64) NULL,transport_status TINYINT NOT NULL,track_node VARCHAR(256) NULL,occurred_at DATETIME(3) NOT NULL,exception_code VARCHAR(64) NULL,exception_reason VARCHAR(512) NULL,source_version BIGINT NOT NULL,source_event_code VARCHAR(128) NOT NULL,PRIMARY KEY(trail_id),UNIQUE KEY uk_sup_asn_trail_event(source_event_code),KEY idx_sup_asn_trail(asn_id,occurred_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ASN运输轨迹不可变事实';

-- ============================================================================
-- Source: V25__supplier_workbench_export.sql"
-- ============================================================================
CREATE TABLE sup_export_task (
  export_task_id BIGINT PRIMARY KEY,
  export_type VARCHAR(32) NOT NULL,
  supplier_id BIGINT NULL,
  query_json JSON NOT NULL,
  status TINYINT NOT NULL COMMENT '1处理中 2已完成 3失败',
  file_url VARCHAR(500) NULL,
  fail_reason VARCHAR(500) NULL,
  created_by BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0,
  KEY idx_sup_export_supplier_status (supplier_id, status, created_at),
  KEY idx_sup_export_type_status (export_type, status)
) COMMENT '供应商运营导出任务';

-- ============================================================================
-- Source: V26__supplier_export_runtime.sql"
-- ============================================================================
UPDATE sup_export_task
SET status = CASE status
  WHEN 1 THEN 1
  WHEN 2 THEN 3
  WHEN 3 THEN 4
  ELSE status
END;

ALTER TABLE sup_export_task
  MODIFY COLUMN status TINYINT NOT NULL COMMENT '1待处理 2处理中 3已完成 4失败',
  ADD COLUMN object_key VARCHAR(500) NULL AFTER file_url,
  ADD COLUMN file_name VARCHAR(255) NULL AFTER object_key,
  ADD COLUMN content_type VARCHAR(128) NULL AFTER file_name,
  ADD COLUMN file_size BIGINT NULL AFTER content_type,
  ADD COLUMN retry_count INT NOT NULL DEFAULT 0 AFTER fail_reason,
  ADD COLUMN next_retry_at DATETIME(3) NULL AFTER retry_count,
  ADD COLUMN started_at DATETIME(3) NULL AFTER next_retry_at,
  ADD COLUMN completed_at DATETIME(3) NULL AFTER started_at,
  ADD COLUMN idempotency_key VARCHAR(128) NULL AFTER created_by,
  ADD UNIQUE KEY uk_sup_export_creator_idem (created_by, idempotency_key),
  ADD KEY idx_sup_export_dispatch (status, next_retry_at, started_at, created_at);

SET FOREIGN_KEY_CHECKS = 1;

