package com.chaobo.scm.supplier.application.quote;
import com.chaobo.scm.common.error.*;import com.chaobo.scm.supplier.application.masterdata.MasterDataSnapshotPort;import com.chaobo.scm.supplier.application.shared.*;import com.chaobo.scm.supplier.domain.quote.*;import com.chaobo.scm.supplier.domain.shared.*;import com.chaobo.scm.supplier.infrastructure.persistence.rfq.SupplierQuoteTodoMapper;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class SupplierQuoteApplicationService {private final SupplierQuoteRepository repo;private final SupplierQuoteReadModelPort read;private final MasterDataSnapshotPort master;private final SupplierQuoteTodoMapper todos;private final OutboxRepository outbox;private final AuditLogRepository audit;private final IdentifierGenerator ids;private final TransactionalCommandExecutor executor;public SupplierQuoteApplicationService(SupplierQuoteRepository repo,SupplierQuoteReadModelPort read,MasterDataSnapshotPort master,SupplierQuoteTodoMapper todos,OutboxRepository outbox,AuditLogRepository audit,IdentifierGenerator ids,TransactionalCommandExecutor executor){this.repo=repo;this.read=read;this.master=master;this.todos=todos;this.outbox=outbox;this.audit=audit;this.ids=ids;this.executor=executor;}
 @Transactional(readOnly=true)public com.chaobo.scm.common.api.PageResult<SupplierQuoteView> page(Long supplierId,Long scope,Integer status,String keyword,int page,int size){if(page<1||size<1||size>100)throw new BusinessException(ErrorCode.VALIDATION_FAILED,"分页参数不合法");return read.page(scope==null?supplierId:scope,status,keyword,page,size);}@Transactional(readOnly=true)public SupplierQuoteView detail(long id,Long scope){var value=read.detail(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"报价不存在"));if(scope!=null&&scope!=value.supplierId())throw new BusinessException(ErrorCode.NOT_FOUND,"报价不存在");return value;}
 @Transactional public CommandResult create(long supplierId,Long rfqId,String rfqNo,String currency,LocalDate from,LocalDate to,List<QuoteLine> lines,CommandContext c){c.requirePermission("supplier:quote:create");c.requireSupplierScope(supplierId);return executor.execute("supplier:quote",c,new Create(supplierId,rfqId,rfqNo,currency,from,to,lines),()->{var normalized=normalizeNewLineIds(lines);eligible(supplierId,normalized);return save(SupplierQuoteAggregate.create(supplierId,rfqId,rfqNo,currency,from,to,normalized,c.operatorId(),ids),c,"CREATE_SUPPLIER_QUOTE",null);});}
 @Transactional public CommandResult modifyDraft(long id,int version,LocalDate from,LocalDate to,List<QuoteLine> lines,CommandContext c){c.requirePermission("supplier:quote:update");return act(id,version,"MODIFY_SUPPLIER_QUOTE_DRAFT",c,a->{eligible(a.supplierId(),lines);a.modifyDraft(from,to,normalizeLineIds(a,lines),c.operatorId(),ids);});}
 @Transactional public CommandResult submit(long id,int version,CommandContext c){c.requirePermission("supplier:quote:submit");return act(id,version,"SUBMIT_SUPPLIER_QUOTE",c,a->{eligible(a.supplierId(),a.lines());assertRfqOpen(a);a.submit(c.operatorId(),ids);if(a.rfqId()!=null&&todos.markSubmitted(a.rfqId(),a.supplierId())!=1)throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"询价已截标或报价待办不可提交");});}
 @Transactional public CommandResult confirm(long id,int version,CommandContext c){c.requirePermission("supplier:quote:confirm");return act(id,version,"CONFIRM_SUPPLIER_QUOTE",c,a->a.confirm(c.operatorId(),ids));}
 @Transactional public CommandResult adopt(long id,int version,String ref,CommandContext c){c.requirePermission("supplier:quote:adopt");return act(id,version,"ADOPT_SUPPLIER_QUOTE",c,a->a.adopt(ref,c.operatorId(),ids));}
 @Transactional public CommandResult reject(long id,int version,String reason,CommandContext c){c.requirePermission("supplier:quote:reject");return act(id,version,"REJECT_SUPPLIER_QUOTE",c,a->a.reject(reason,c.operatorId(),ids));}
 @Transactional public CommandResult voidQuote(long id,int version,String reason,CommandContext c){c.requirePermission("supplier:quote:void");return act(id,version,"VOID_SUPPLIER_QUOTE",c,a->a.voidQuote(reason,c.operatorId(),ids));}
 @Transactional public void expireQuotes(){for(long id:repo.expiredIds()){var a=repo.findById(id).orElse(null);if(a==null)continue;String before=snapshot(a);a.expire(0,ids);if(a.status()==QuoteStatus.EXPIRED){var c=new CommandContext(0,"系统",0,null,"quote-expire-"+id,null,"quote-expire-"+id,Set.of());save(a,c,"EXPIRE_SUPPLIER_QUOTE",before);}}}
 private CommandResult act(long id,int version,String op,CommandContext c,java.util.function.Consumer<SupplierQuoteAggregate> f){return executor.execute("supplier:quote",c,new Change(id,version,op),()->{var a=repo.findById(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"供应商报价不存在"));c.requireSupplierScope(a.supplierId());if(a.version()!=version)throw new BusinessException(ErrorCode.VERSION_CONFLICT,"报价已被更新");String before=snapshot(a);f.accept(a);return save(a,c,op,before);});}private List<QuoteLine> normalizeNewLineIds(List<QuoteLine> lines){return lines.stream().map(line->new QuoteLine(ids.nextId(),line.skuCode(),line.quoteQty(),line.unitPrice(),line.taxRate(),line.deliveryDays(),line.moq())).toList();}private List<QuoteLine> normalizeLineIds(SupplierQuoteAggregate a,List<QuoteLine> lines){var existing=a.lines().stream().collect(java.util.stream.Collectors.toMap(QuoteLine::lineId,java.util.function.Function.identity()));var result=new ArrayList<QuoteLine>();for(var line:lines){long lineId=line.lineId();if(lineId<=0)lineId=ids.nextId();else if(!existing.containsKey(lineId))throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"报价行不属于当前报价，新增行请勿传入行ID");result.add(new QuoteLine(lineId,line.skuCode(),line.quoteQty(),line.unitPrice(),line.taxRate(),line.deliveryDays(),line.moq()));}return result;}private void assertRfqOpen(SupplierQuoteAggregate a){if(a.rfqId()==null)return;var todo=todos.state(a.rfqId(),a.supplierId());if(todo==null||todo.status()!=1||todo.deadline()!=null&&todo.deadline().isBefore(OffsetDateTime.now()))throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"询价已截标或报价待办不可提交");}
 private void eligible(long supplierId,List<QuoteLine> lines){var supplier=master.findSupplier(supplierId).orElseThrow(()->new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"供应商主数据快照不存在"));if(!supplier.enabled())throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"供应商未启用，不能报价");for(var line:lines){var sku=master.findSku(line.skuCode()).orElseThrow(()->new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"SKU主数据快照不存在: "+line.skuCode()));if(!sku.enabled())throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"SKU已停用，不能报价: "+line.skuCode());}}
 private CommandResult save(SupplierQuoteAggregate a,CommandContext c,String op,String before){repo.save(a,c.operatorId());var events=a.pullEvents();outbox.saveAll(events);audit.save(c,op,"SUPPLIER_QUOTE",a.id(),a.no(),before,snapshot(a));String e=events.isEmpty()?null:events.getLast().eventCode();return new CommandResult(a.id(),a.no(),a.status().code(),a.status().label(),a.version(),e,false);}private String snapshot(SupplierQuoteAggregate a){return "{\"quoteNo\":\"%s\",\"status\":%d,\"version\":%d}".formatted(a.no(),a.status().code(),a.version());}private record Create(long supplierId,Long rfqId,String rfqNo,String currency,LocalDate from,LocalDate to,List<QuoteLine> lines){}private record Change(long id,int version,String op){}
}
