package com.chaobo.scm.supplier.domain.quality;

import com.chaobo.scm.common.error.*;
import com.chaobo.scm.supplier.domain.shared.*;
import java.time.OffsetDateTime;
import java.util.*;

public final class SupplierQualityIssueAggregate {
    private final long id; private final String no; private final long supplierId;
    private final String sourceType, sourceNo, issueType, description; private final int severity;
    private QualityIssueStatus status; private OffsetDateTime deadline; private String plan, verification; private int version;
    private final List<DomainEvent> events = new ArrayList<>();
    private SupplierQualityIssueAggregate(long id,String no,long supplierId,String sourceType,String sourceNo,String issueType,int severity,String description,QualityIssueStatus status,OffsetDateTime deadline,String plan,String verification,int version){this.id=id;this.no=no;this.supplierId=supplierId;this.sourceType=sourceType;this.sourceNo=sourceNo;this.issueType=issueType;this.severity=severity;this.description=description;this.status=status;this.deadline=deadline;this.plan=plan;this.verification=verification;this.version=version;validate();}
    public static SupplierQualityIssueAggregate create(long supplierId,String sourceType,String sourceNo,String issueType,int severity,String description,long operator,IdentifierGenerator ids){var result=new SupplierQualityIssueAggregate(ids.nextId(),ids.nextBusinessNo("QI"),supplierId,sourceType,sourceNo,issueType,severity,description,QualityIssueStatus.OPEN,null,null,null,0);result.raise(ids,"SupplierQualityIssueCreated","供应商质量问题已创建",operator);return result;}
    public static SupplierQualityIssueAggregate rehydrate(long id,String no,long supplierId,String sourceType,String sourceNo,String issueType,int severity,String description,int status,OffsetDateTime deadline,String plan,String verification,int version){return new SupplierQualityIssueAggregate(id,no,supplierId,sourceType,sourceNo,issueType,severity,description,QualityIssueStatus.fromCode(status),deadline,plan,verification,version);}
    public void requestRectification(OffsetDateTime deadline,long operator,IdentifierGenerator ids){if(status!=QualityIssueStatus.OPEN&&status!=QualityIssueStatus.OVERDUE)throw state("当前状态不能发起整改");if(deadline==null||!deadline.isAfter(OffsetDateTime.now()))throw rule("整改截止时间必须晚于当前时间");this.deadline=deadline;status=QualityIssueStatus.RECTIFYING;version++;raise(ids,"SupplierRectificationRequested","供应商整改已发起",operator);}
    public void submitPlan(String plan,long operator,IdentifierGenerator ids){if(status!=QualityIssueStatus.RECTIFYING&&status!=QualityIssueStatus.OVERDUE)throw state("当前状态不能提交整改");if(plan==null||plan.isBlank())throw rule("整改方案不能为空");this.plan=plan.trim();status=QualityIssueStatus.PENDING_VERIFICATION;version++;raise(ids,"SupplierRectificationSubmitted","供应商整改已提交",operator);}
    public void verify(boolean passed,String comment,long operator,IdentifierGenerator ids){if(status!=QualityIssueStatus.PENDING_VERIFICATION)throw state("当前状态不能验证整改");if(comment==null||comment.isBlank())throw rule("验证意见不能为空");verification=comment.trim();status=passed?QualityIssueStatus.CLOSED:QualityIssueStatus.RECTIFYING;version++;raise(ids,passed?"SupplierRectificationApproved":"SupplierRectificationRejected",passed?"供应商整改已通过":"供应商整改已驳回",operator);}
    public void markOverdue(long operator,IdentifierGenerator ids){if(status!=QualityIssueStatus.RECTIFYING||deadline==null||deadline.isAfter(OffsetDateTime.now()))return;status=QualityIssueStatus.OVERDUE;version++;raise(ids,"SupplierRectificationOverdue","供应商整改已逾期",operator);}
    private void validate(){if(supplierId<=0||sourceType==null||sourceType.isBlank()||issueType==null||issueType.isBlank()||severity<1||severity>4||description==null||description.isBlank())throw rule("质量问题信息不完整");}
    private void raise(IdentifierGenerator ids,String type,String name,long operator){long eventId=ids.nextId();events.add(new DomainEvent(eventId,"SUP-"+eventId,type,name,"SUPPLIER_QUALITY_ISSUE",id,no,version,operator,OffsetDateTime.now(),Map.of("supplierId",supplierId,"severity",severity,"issueType",issueType)));}
    private static BusinessException rule(String message){return new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,message);} private static BusinessException state(String message){return new BusinessException(ErrorCode.STATE_CONFLICT,message);}
    public List<DomainEvent> pullEvents(){var result=List.copyOf(events);events.clear();return result;} public long id(){return id;} public String no(){return no;} public long supplierId(){return supplierId;} public String sourceType(){return sourceType;} public String sourceNo(){return sourceNo;} public String issueType(){return issueType;} public int severity(){return severity;} public String description(){return description;} public QualityIssueStatus status(){return status;} public OffsetDateTime deadline(){return deadline;} public String plan(){return plan;} public String verification(){return verification;} public int version(){return version;}
}
