package com.chaobo.scm.supplier.application.item;

import com.chaobo.scm.common.api.PageResult;import com.chaobo.scm.common.error.*;
import com.chaobo.scm.supplier.application.shared.*;import com.chaobo.scm.supplier.domain.item.*;import com.chaobo.scm.supplier.domain.shared.*;
import com.chaobo.scm.supplier.application.masterdata.MasterDataSnapshotPort;import com.chaobo.scm.supplier.application.qualification.SupplierQualificationPolicyPort;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;import java.util.function.Consumer;

@Service
public class SupplierItemApplicationService {
    private final SupplierItemRepository repo;private final SupplierItemReadModelPort read;private final OutboxRepository outbox;private final AuditLogRepository audit;private final IdentifierGenerator ids;private final TransactionalCommandExecutor executor;private final MasterDataSnapshotPort masterData;private final SupplierQualificationPolicyPort qualifications;private final SupplierItemHistoryPort history;
    public SupplierItemApplicationService(SupplierItemRepository repo,SupplierItemReadModelPort read,OutboxRepository outbox,AuditLogRepository audit,IdentifierGenerator ids,TransactionalCommandExecutor executor,MasterDataSnapshotPort masterData,SupplierQualificationPolicyPort qualifications,SupplierItemHistoryPort history){this.repo=repo;this.read=read;this.outbox=outbox;this.audit=audit;this.ids=ids;this.executor=executor;this.masterData=masterData;this.qualifications=qualifications;this.history=history;}
    @Transactional(readOnly=true) public PageResult<SupplierItemView> page(Long supplierId,Long scope,Integer status,String keyword,int pageNo,int pageSize){validatePage(pageNo,pageSize);return read.page(scope==null?supplierId:scope,status,keyword,pageNo,pageSize);}
    @Transactional(readOnly=true) public SupplierItemView detail(long id,Long scope){var v=read.detail(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"供应商商品不存在"));if(scope!=null&&scope!=v.supplierId())throw new BusinessException(ErrorCode.NOT_FOUND,"供应商商品不存在");return v;}
    @Transactional public CommandResult enable(long supplierId,String sku,String supplierSku,SupplyCondition condition,CommandContext c){c.requirePermission("supplier:supplierproduct:create");c.requireSupplierScope(supplierId);record R(long supplierId,String sku,String supplierSku,SupplyCondition condition){}var r=new R(supplierId,sku,supplierSku,condition);return executor.execute("supplier:item",c,r,()->{ensureEligible(supplierId,sku);if(repo.exists(supplierId,sku))throw new BusinessException(ErrorCode.STATE_CONFLICT,"供应商SKU供货关系已存在");return persist(SupplierItemAggregate.enable(supplierId,sku,supplierSku,condition,c.operatorId(),ids),c,"ENABLE_SUPPLIER_ITEM",null);});}
    @Transactional public CommandResult change(long id,int version,String supplierSku,SupplyCondition condition,CommandContext c){c.requirePermission("supplier:supplierproduct:supplier_sku");return change(id,version,new ChangeRequest(id,version,supplierSku,condition),c,"CHANGE_SUPPLY_CONDITION",a->a.changeCondition(supplierSku,condition,c.operatorId(),ids));}
    @Transactional public CommandResult pause(long id,int version,String reason,CommandContext c){c.requirePermission("supplier:supplierproduct:pause");return change(id,version,new StateRequest(id,version,reason),c,"PAUSE_SUPPLY",a->a.pause(reason,c.operatorId(),ids));}
    @Transactional public CommandResult resume(long id,int version,CommandContext c){c.requirePermission("supplier:supplierproduct:resume");return change(id,version,new StateRequest(id,version,"resume"),c,"RESUME_SUPPLY",a->{ensureEligible(a.supplierId(),a.skuCode());a.resume(c.operatorId(),ids);});}
    @Transactional public CommandResult discontinue(long id,int version,String reason,CommandContext c){c.requirePermission("supplier:supplierproduct:discontinue");return change(id,version,new StateRequest(id,version,reason),c,"DISCONTINUE_SUPPLY",a->a.discontinue(reason,c.operatorId(),ids));}
    private CommandResult change(long id,int version,Object request,CommandContext c,String op,Consumer<SupplierItemAggregate> action){return executor.execute("supplier:item",c,request,()->{var a=repo.findById(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"供应商商品不存在"));c.requireSupplierScope(a.supplierId());if(a.version()!=version)throw new BusinessException(ErrorCode.VERSION_CONFLICT,"供应商商品版本已变化");String before=snapshot(a);action.accept(a);return persist(a,c,op,before);});}
    private CommandResult persist(SupplierItemAggregate a,CommandContext c,String op,String before){repo.save(a,c.operatorId());if(Set.of("ENABLE_SUPPLIER_ITEM","CHANGE_SUPPLY_CONDITION").contains(op))history.recordCondition(a,op,c.operatorId());List<DomainEvent> events=a.pullEvents();outbox.saveAll(events);audit.save(c,op,"SUPPLIER_ITEM",a.itemId(),Long.toString(a.itemId()),before,snapshot(a));String event=events.isEmpty()?null:events.get(events.size()-1).eventCode();return new CommandResult(a.itemId(),Long.toString(a.itemId()),a.status().code(),a.status().label(),a.version(),event,false);}
    private void ensureEligible(long supplierId,String skuCode){var supplier=masterData.findSupplier(supplierId).orElseThrow(()->new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"供应商主数据快照不存在或尚未同步"));if(!supplier.enabled())throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"供应商未启用，不能建立或恢复供货关系");var sku=masterData.findSku(skuCode).orElseThrow(()->new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"SKU主数据快照不存在或尚未同步"));if(!sku.enabled())throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"SKU已停用，不能建立或恢复供货关系");qualifications.assertEligible(supplierId,sku.categoryId());}
    private String snapshot(SupplierItemAggregate a){return "{\"itemId\":%d,\"status\":%d,\"version\":%d}".formatted(a.itemId(),a.status().code(),a.version());}
    private void validatePage(int pageNo,int pageSize){if(pageNo<1||pageSize<1||pageSize>100)throw new BusinessException(ErrorCode.VALIDATION_FAILED,"分页参数不合法");}
    private record ChangeRequest(long id,int version,String supplierSku,SupplyCondition condition){}private record StateRequest(long id,int version,String reason){}
}
