package com.chaobo.scm.supplier.infrastructure.persistence.finance;
import com.chaobo.scm.supplier.application.finance.FinanceViews;import org.apache.ibatis.annotations.*;import java.math.BigDecimal;import java.util.List;
@Mapper public interface SupplierFinanceMapper{
 @Insert("INSERT INTO sup_reconciliation(reconciliation_id,statement_no,supplier_id,currency,statement_amount,status,source_version) VALUES(#{id},#{no},#{supplierId},#{currency},#{amount},1,#{sourceVersion}) ON DUPLICATE KEY UPDATE currency=IF(source_version&lt;VALUES(source_version),VALUES(currency),currency),statement_amount=IF(source_version&lt;VALUES(source_version),VALUES(statement_amount),statement_amount),source_version=GREATEST(source_version,VALUES(source_version))")void upsertStatement(@Param("id")long id,@Param("no")String no,@Param("supplierId")long supplierId,@Param("currency")String currency,@Param("amount")BigDecimal amount,@Param("sourceVersion")int sourceVersion);
 @Select("SELECT reconciliation_id id,statement_no statementNo,supplier_id supplierId,currency,statement_amount statementAmount,confirmed_amount confirmedAmount,status,difference_reason differenceReason,source_version sourceVersion,version FROM sup_reconciliation WHERE reconciliation_id=#{id} AND deleted=0")FinanceViews.Reconciliation reconciliation(long id);
 @Select("<script>SELECT reconciliation_id id,statement_no statementNo,supplier_id supplierId,currency,statement_amount statementAmount,confirmed_amount confirmedAmount,status,difference_reason differenceReason,source_version sourceVersion,version FROM sup_reconciliation WHERE deleted=0 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND status=#{status}</if> ORDER BY updated_at DESC LIMIT #{offset},#{size}</script>")List<FinanceViews.Reconciliation> reconciliations(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("offset")int offset,@Param("size")int size);
 @Select("<script>SELECT COUNT(*) FROM sup_reconciliation WHERE deleted=0 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND status=#{status}</if></script>")long reconciliationCount(@Param("supplierId")Long supplierId,@Param("status")Integer status);
 @Update("UPDATE sup_reconciliation SET confirmed_amount=#{amount},status=#{status},difference_reason=#{reason},version=version+1 WHERE reconciliation_id=#{id} AND version=#{version} AND status=1 AND deleted=0")int respond(@Param("id")long id,@Param("version")int version,@Param("amount")BigDecimal amount,@Param("status")int status,@Param("reason")String reason);
 @Update("UPDATE sup_reconciliation SET status=#{status},version=version+1 WHERE reconciliation_id=#{id} AND version=#{version} AND status IN (2,3) AND deleted=0")int changeStatus(@Param("id")long id,@Param("version")int version,@Param("status")int status);
 @Insert("INSERT INTO sup_invoice_collaboration(invoice_id,invoice_no,supplier_id,reconciliation_id,invoice_type,amount_excluding_tax,tax_amount,tax_rate,attachment_url,status) VALUES(#{id},#{no},#{supplierId},#{reconciliationId},#{type},#{net},#{tax},#{rate},#{url},1)")void insertInvoice(@Param("id")long id,@Param("no")String no,@Param("supplierId")long supplierId,@Param("reconciliationId")Long reconciliationId,@Param("type")int type,@Param("net")BigDecimal net,@Param("tax")BigDecimal tax,@Param("rate")BigDecimal rate,@Param("url")String url);
 @Select("SELECT invoice_id id,invoice_no invoiceNo,supplier_id supplierId,reconciliation_id reconciliationId,invoice_type invoiceType,amount_excluding_tax amountExcludingTax,tax_amount taxAmount,tax_rate taxRate,attachment_url attachmentUrl,status,validation_message validationMessage,version FROM sup_invoice_collaboration WHERE invoice_id=#{id} AND deleted=0")FinanceViews.Invoice invoice(long id);
 @Select("<script>SELECT invoice_id id,invoice_no invoiceNo,supplier_id supplierId,reconciliation_id reconciliationId,invoice_type invoiceType,amount_excluding_tax amountExcludingTax,tax_amount taxAmount,tax_rate taxRate,attachment_url attachmentUrl,status,validation_message validationMessage,version FROM sup_invoice_collaboration WHERE deleted=0 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND status=#{status}</if> ORDER BY updated_at DESC LIMIT #{offset},#{size}</script>")List<FinanceViews.Invoice> invoices(@Param("supplierId")Long supplierId,@Param("status")Integer status,@Param("offset")int offset,@Param("size")int size);
 @Select("<script>SELECT COUNT(*) FROM sup_invoice_collaboration WHERE deleted=0 <if test='supplierId!=null'>AND supplier_id=#{supplierId}</if><if test='status!=null'>AND status=#{status}</if></script>")long invoiceCount(@Param("supplierId")Long supplierId,@Param("status")Integer status);
 @Update("UPDATE sup_invoice_collaboration SET status=#{status},validation_message=#{message},version=version+1 WHERE invoice_id=#{id} AND status IN (1,3) AND deleted=0")int validateInvoice(@Param("id")long id,@Param("status")int status,@Param("message")String message);
}
