package com.chaobo.scm.supplier.infrastructure.persistence.score;import com.chaobo.scm.supplier.application.score.ScoreViews;import org.apache.ibatis.annotations.*;import java.math.BigDecimal;import java.time.*;import java.util.List;
@Mapper public interface SupplierScoreMapper{
 @Insert("INSERT INTO sup_performance_fact(fact_id,event_code,supplier_id,dimension_code,metric_code,metric_value,occurred_at,source_system,source_no,payload_json) VALUES(#{id},#{eventCode},#{supplierId},#{dimension},#{metric},#{value},#{occurredAt},#{source},#{sourceNo},CAST(#{payload} AS JSON)) ON DUPLICATE KEY UPDATE event_code=event_code")int insertFact(@Param("id")long id,@Param("eventCode")String eventCode,@Param("supplierId")long supplierId,@Param("dimension")String dimension,@Param("metric")String metric,@Param("value")BigDecimal value,@Param("occurredAt")OffsetDateTime occurredAt,@Param("source")String source,@Param("sourceNo")String sourceNo,@Param("payload")String payload);
 @Select("SELECT fact_id id,event_code eventCode,supplier_id supplierId,dimension_code dimensionCode,metric_code metricCode,metric_value metricValue,occurred_at occurredAt,source_system sourceSystem,source_no sourceNo FROM sup_performance_fact WHERE supplier_id=#{supplierId} AND occurred_at&gt;=#{from} AND occurred_at&lt;#{to} ORDER BY occurred_at")List<ScoreViews.Fact> facts(@Param("supplierId")long supplierId,@Param("from")OffsetDateTime from,@Param("to")OffsetDateTime to);
 @Select("SELECT DISTINCT supplier_id FROM sup_performance_fact WHERE occurred_at&gt;=#{from} AND occurred_at&lt;#{to}")List<Long> suppliersWithFacts(@Param("from")OffsetDateTime from,@Param("to")OffsetDateTime to);
 @Insert("INSERT INTO sup_score_rule(rule_id,rule_name,dimension_code,metric_code,weight,target_value,score_direction,status,effective_from,effective_to,created_by,updated_by,version) VALUES(#{id},#{name},#{dimension},#{metric},#{weight},#{target},#{direction},1,#{from},#{to},#{operator},#{operator},0)")void insertRule(@Param("id")long id,@Param("name")String name,@Param("dimension")String dimension,@Param("metric")String metric,@Param("weight")BigDecimal weight,@Param("target")BigDecimal target,@Param("direction")int direction,@Param("from")LocalDate from,@Param("to")LocalDate to,@Param("operator")long operator);
 @Update("UPDATE sup_score_rule SET status=2,updated_by=#{operator},version=version+1 WHERE rule_id=#{id} AND version=#{version} AND status=1")int publishRule(@Param("id")long id,@Param("version")int version,@Param("operator")long operator);
 @Update("UPDATE sup_score_rule SET status=3,updated_by=#{operator},version=version+1 WHERE rule_id=#{id} AND version=#{version} AND status=2")int disableRule(@Param("id")long id,@Param("version")int version,@Param("operator")long operator);
 @Select("SELECT rule_id id,rule_name name,dimension_code dimensionCode,metric_code metricCode,weight,target_value targetValue,score_direction direction,status,effective_from effectiveFrom,effective_to effectiveTo,version FROM sup_score_rule WHERE status=2 AND effective_from&lt;=#{date} AND (effective_to IS NULL OR effective_to&gt;=#{date}) ORDER BY rule_id")List<ScoreViews.Rule> effectiveRules(LocalDate date);
 @Select("SELECT rule_id id,rule_name name,dimension_code dimensionCode,metric_code metricCode,weight,target_value targetValue,score_direction direction,status,effective_from effectiveFrom,effective_to effectiveTo,version FROM sup_score_rule ORDER BY updated_at DESC")List<ScoreViews.Rule> rules();
 @Insert("INSERT INTO sup_score_result(score_result_id,supplier_id,period_code,total_score,dimension_scores_json,fact_summary_json,manual_adjustment,adjustment_reason,status,version) VALUES(#{id},#{supplierId},#{period},#{total},CAST(#{dimensions} AS JSON),CAST(#{summary} AS JSON),#{adjustment},#{reason},1,0) ON DUPLICATE KEY UPDATE total_score=IF(status=1,VALUES(total_score),total_score),dimension_scores_json=IF(status=1,VALUES(dimension_scores_json),dimension_scores_json),fact_summary_json=IF(status=1,VALUES(fact_summary_json),fact_summary_json),manual_adjustment=IF(status=1,VALUES(manual_adjustment),manual_adjustment),adjustment_reason=IF(status=1,VALUES(adjustment_reason),adjustment_reason),version=IF(status=1,version+1,version)")void upsertResult(@Param("id")long id,@Param("supplierId")long supplierId,@Param("period")String period,@Param("total")BigDecimal total,@Param("dimensions")String dimensions,@Param("summary")String summary,@Param("adjustment")BigDecimal adjustment,@Param("reason")String reason);
 @Select("SELECT score_result_id id,supplier_id supplierId,period_code periodCode,total_score totalScore,dimension_scores_json dimensionScoresJson,fact_summary_json factSummaryJson,manual_adjustment manualAdjustment,adjustment_reason adjustmentReason,status,published_at publishedAt,version FROM sup_score_result WHERE supplier_id=#{supplierId} AND period_code=#{period}")ScoreViews.Result resultByPeriod(@Param("supplierId")long supplierId,@Param("period")String period);
 @Select("SELECT score_result_id id,supplier_id supplierId,period_code periodCode,total_score totalScore,dimension_scores_json dimensionScoresJson,fact_summary_json factSummaryJson,manual_adjustment manualAdjustment,adjustment_reason adjustmentReason,status,published_at publishedAt,version FROM sup_score_result WHERE score_result_id=#{id}")ScoreViews.Result result(long id);
 @Update("UPDATE sup_score_result SET status=2,published_at=NOW(3),version=version+1 WHERE score_result_id=#{id} AND version=#{version} AND status=1")int publishResult(@Param("id")long id,@Param("version")int version);
 @Insert("INSERT INTO sup_risk_recommendation(recommendation_id,supplier_id,score_result_id,risk_level,recommendation_type,reason,status,version) VALUES(#{id},#{supplierId},#{resultId},#{level},#{type},#{reason},1,0)")void insertRisk(@Param("id")long id,@Param("supplierId")long supplierId,@Param("resultId")long resultId,@Param("level")int level,@Param("type")int type,@Param("reason")String reason);
 @Select("SELECT recommendation_id id,supplier_id supplierId,score_result_id scoreResultId,risk_level riskLevel,recommendation_type recommendationType,reason,status,version FROM sup_risk_recommendation WHERE supplier_id=#{supplierId} ORDER BY created_at DESC")List<ScoreViews.Risk> risks(long supplierId);
 @Update("UPDATE sup_risk_recommendation SET status=#{status},version=version+1 WHERE recommendation_id=#{id} AND version=#{version} AND status=1")int processRisk(@Param("id")long id,@Param("version")int version,@Param("status")int status);
}
