package com.chaobo.scm.supplier.domain.quote;
import com.chaobo.scm.common.error.*;import com.chaobo.scm.supplier.domain.shared.*;import java.time.*;import java.util.*;
public final class SupplierQuoteAggregate{private final long id;private final String no;private final long supplierId;private final Long rfqId;private final String rfqNo;private final String currency;private LocalDate from,to;private QuoteStatus status;private String rejectionReason,agreementRef;private List<QuoteLine> lines;private int version;private final List<DomainEvent> events=new ArrayList<>();private SupplierQuoteAggregate(long id,String no,long supplierId,Long rfqId,String rfqNo,String currency,LocalDate from,LocalDate to,QuoteStatus status,String rejectionReason,String agreementRef,List<QuoteLine> lines,int version){this.id=id;this.no=no;this.supplierId=supplierId;this.rfqId=rfqId;this.rfqNo=rfqNo;this.currency=currency;this.from=from;this.to=to;this.status=status;this.rejectionReason=rejectionReason;this.agreementRef=agreementRef;this.lines=new ArrayList<>(lines);this.version=version;validate();}
 public static SupplierQuoteAggregate create(long supplierId,Long rfqId,String rfqNo,String currency,LocalDate from,LocalDate to,List<QuoteLine> lines,long operator,IdentifierGenerator ids){long id=ids.nextId();var quote=new SupplierQuoteAggregate(id,ids.nextBusinessNo("SQ"),supplierId,rfqId,rfqNo,currency,from,to,QuoteStatus.DRAFT,null,null,lines,0);quote.raise(ids,"SupplierQuoteCreated","供应商报价已创建",operator,Map.of("supplierId",supplierId,"quoteNo",quote.no,"lineCount",lines.size()));return quote;}
 public static SupplierQuoteAggregate rehydrate(long id,String no,long supplierId,Long rfqId,String rfqNo,String currency,LocalDate from,LocalDate to,int status,String rejectionReason,String agreementRef,List<QuoteLine> lines,int version){return new SupplierQuoteAggregate(id,no,supplierId,rfqId,rfqNo,currency,from,to,QuoteStatus.fromCode(status),rejectionReason,agreementRef,lines,version);}
 public void modifyDraft(LocalDate validFrom,LocalDate validTo,List<QuoteLine> newLines,long operator,IdentifierGenerator ids){require(QuoteStatus.DRAFT);if(validFrom==null||validTo==null||validTo.isBefore(validFrom)||newLines==null||newLines.isEmpty())throw rule("报价有效期或报价行不合法");if(newLines.stream().map(QuoteLine::skuCode).distinct().count()!=newLines.size())throw rule("同一报价不能重复SKU");from=validFrom;to=validTo;lines=new ArrayList<>(newLines);version++;raise(ids,"SupplierQuoteDraftModified","供应商报价草稿已修改",operator,Map.of("quoteNo",no,"lineCount",newLines.size()));}
 public void submit(long operator,IdentifierGenerator ids){require(QuoteStatus.DRAFT);if(to.isBefore(LocalDate.now()))throw rule("报价有效期已结束");status=QuoteStatus.SUBMITTED;version++;raise(ids,"SupplierQuoteSubmitted","供应商报价已提交",operator,Map.of("quoteNo",no,"supplierId",supplierId,"rfqId",rfqId==null?0:rfqId,"validTo",to.toString()));}
 public void confirm(long operator,IdentifierGenerator ids){require(QuoteStatus.SUBMITTED);status=QuoteStatus.CONFIRMED;version++;raise(ids,"SupplierQuoteConfirmed","供应商报价已确认",operator,Map.of("quoteNo",no,"supplierId",supplierId));}
 public void adopt(String ref,long operator,IdentifierGenerator ids){require(QuoteStatus.CONFIRMED);if(ref==null||ref.isBlank())throw rule("价格协议引用不能为空");agreementRef=ref;status=QuoteStatus.ADOPTED;version++;raise(ids,"SupplierQuoteAdopted","供应商报价已采纳",operator,Map.of("quoteNo",no,"supplierId",supplierId,"priceAgreementRef",ref));}
 public void reject(String reason,long operator,IdentifierGenerator ids){if(status!=QuoteStatus.SUBMITTED&&status!=QuoteStatus.CONFIRMED)throw state("当前状态不能拒绝报价");if(reason==null||reason.isBlank())throw rule("拒绝原因不能为空");rejectionReason=reason.trim();status=QuoteStatus.REJECTED;version++;raise(ids,"SupplierQuoteRejected","供应商报价已拒绝",operator,Map.of("quoteNo",no,"reason",rejectionReason));}
 public void voidQuote(String reason,long operator,IdentifierGenerator ids){if(status==QuoteStatus.ADOPTED||status==QuoteStatus.VOIDED)throw state("当前状态不能作废报价");if(reason==null||reason.isBlank())throw rule("作废原因不能为空");rejectionReason=reason.trim();status=QuoteStatus.VOIDED;version++;raise(ids,"SupplierQuoteVoided","供应商报价已作废",operator,Map.of("quoteNo",no,"reason",rejectionReason));}
 public void expire(long operator,IdentifierGenerator ids){if(status==QuoteStatus.ADOPTED||status==QuoteStatus.VOIDED||status==QuoteStatus.EXPIRED||to.isAfter(LocalDate.now()))return;status=QuoteStatus.EXPIRED;version++;raise(ids,"SupplierQuoteExpired","供应商报价已过期",operator,Map.of("quoteNo",no,"validTo",to.toString()));}
 private void validate(){if(supplierId<=0||currency==null||currency.isBlank()||from==null||to==null||to.isBefore(from)||lines==null||lines.isEmpty())throw rule("报价供应商、币种、有效期或报价行不合法");if(lines.stream().map(QuoteLine::skuCode).distinct().count()!=lines.size())throw rule("同一报价不能重复SKU");}private void require(QuoteStatus expected){if(status!=expected)throw state("报价状态不允许当前操作");}private void raise(IdentifierGenerator ids,String type,String name,long operator,Map<String,Object> payload){long event=ids.nextId();events.add(new DomainEvent(event,"SUP-"+event,type,name,"SUPPLIER_QUOTE",id,no,version,operator,OffsetDateTime.now(),payload));}private static BusinessException rule(String message){return new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,message);}private static BusinessException state(String message){return new BusinessException(ErrorCode.STATE_CONFLICT,message);}public List<DomainEvent> pullEvents(){var result=List.copyOf(events);events.clear();return result;}public long id(){return id;}public String no(){return no;}public long supplierId(){return supplierId;}public Long rfqId(){return rfqId;}public String rfqNo(){return rfqNo;}public String currency(){return currency;}public LocalDate validFrom(){return from;}public LocalDate validTo(){return to;}public QuoteStatus status(){return status;}public String rejectionReason(){return rejectionReason;}public String agreementRef(){return agreementRef;}public List<QuoteLine> lines(){return List.copyOf(lines);}public int version(){return version;}}
