package com.chaobo.scm.supplier.application.integration;
import com.chaobo.scm.common.error.*;import com.chaobo.scm.common.integration.*;import com.chaobo.scm.supplier.infrastructure.integration.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.PlatformTransactionManager;import org.springframework.transaction.support.TransactionTemplate;import tools.jackson.core.JacksonException;import tools.jackson.databind.ObjectMapper;import java.time.*;import java.util.*;
@Service public class IntegrationCommandDispatcher{
 private final IntegrationCommandRepository repo;private final DubboReferenceFactory dubbo;private final RemoteCallCircuitBreaker circuit;private final ObjectMapper json;private final TransactionTemplate tx;private final int batchSize,maxRetries;
 public IntegrationCommandDispatcher(IntegrationCommandRepository repo,DubboReferenceFactory dubbo,RemoteCallCircuitBreaker circuit,ObjectMapper json,PlatformTransactionManager manager,@Value("${scm.integration.batch-size:50}")int batchSize,@Value("${scm.integration.max-retries:8}")int maxRetries){this.repo=repo;this.dubbo=dubbo;this.circuit=circuit;this.json=json;this.tx=new TransactionTemplate(manager);this.batchSize=batchSize;this.maxRetries=maxRetries;}
 @Scheduled(fixedDelayString="${scm.integration.fixed-delay:1000}")public void dispatch(){List<IntegrationCommand> commands=tx.execute(status->{var rows=repo.lockDispatchable(batchSize);return rows.stream().filter(command->repo.markExecuting(command.id())).toList();});if(commands!=null)commands.forEach(this::execute);}
 private void execute(IntegrationCommand command){try{String reference=switch(command.type()){case "WMS_CREATE_APPOINTMENT"->wmsAppointment(read(command,WmsCollaborationApi.InboundAppointmentCommand.class));case "WMS_CANCEL_APPOINTMENT"->wmsCancel(read(command,WmsCollaborationApi.CancelAppointmentCommand.class));case "WMS_CREATE_RETURN_OUTBOUND"->wmsOutbound(read(command,WmsCollaborationApi.ReturnOutboundCommand.class));case "TMS_CREATE_INBOUND_TRANSPORT"->tmsInbound(read(command,TmsCollaborationApi.InboundTransportCommand.class));case "TMS_CREATE_RETURN_TRANSPORT"->tmsReturn(read(command,TmsCollaborationApi.ReturnTransportCommand.class));case "TMS_CANCEL_TRANSPORT"->tmsCancel(read(command,TmsCollaborationApi.CancelTransportCommand.class));case "INVENTORY_LOCK_RETURN"->inventoryLock(read(command,InventoryCollaborationApi.ReturnLockCommand.class));case "INVENTORY_RELEASE_RETURN"->inventoryRelease(read(command,InventoryCollaborationApi.ReturnReleaseCommand.class));case "BMS_CREATE_RETURN_SETTLEMENT"->bmsSettlement(read(command,BmsCollaborationApi.ReturnSettlementCommand.class));case "MDM_CREATE_SUPPLIER"->mdmCreate(read(command,MasterDataCollaborationApi.CreateSupplierCommand.class));case "MDM_CHANGE_SUPPLIER_STATUS"->mdmStatus(read(command,MasterDataCollaborationApi.ChangeSupplierStatusCommand.class));case "IAM_UPDATE_SUPPLIER_SCOPE"->iamScope(read(command,IamCollaborationApi.UpdateSupplierScopeCommand.class));default->throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"不支持的集成命令: "+command.type());};tx.executeWithoutResult(status->repo.markSucceeded(command.id(),reference));}catch(RuntimeException exception){String reason=exception.getMessage()==null?exception.getClass().getSimpleName():exception.getMessage();OffsetDateTime next=OffsetDateTime.now().plusSeconds(Math.min(300L,1L<<Math.min(command.retryCount(),8)));tx.executeWithoutResult(status->repo.markRetry(command.id(),command.retryCount(),next,reason.substring(0,Math.min(1000,reason.length())),maxRetries));}}
 private String wmsAppointment(WmsCollaborationApi.InboundAppointmentCommand command){var result=circuit.execute("WMS",()->dubbo.client(WmsCollaborationApi.class).createOrAdjustInboundAppointment(command));accepted(result.accepted(),result.reason());return result.appointmentNo();}
 private String wmsCancel(WmsCollaborationApi.CancelAppointmentCommand command){circuit.execute("WMS",()->{dubbo.client(WmsCollaborationApi.class).cancelInboundAppointment(command);return true;});return String.valueOf(command.asnId());}
 private String wmsOutbound(WmsCollaborationApi.ReturnOutboundCommand command){var result=circuit.execute("WMS",()->dubbo.client(WmsCollaborationApi.class).createSupplierReturnOutbound(command));accepted(result.accepted(),result.reason());return result.outboundNo();}
 private String tmsInbound(TmsCollaborationApi.InboundTransportCommand command){var result=circuit.execute("TMS",()->dubbo.client(TmsCollaborationApi.class).createInboundTransport(command));accepted(result.accepted(),result.reason());return result.shipmentId();}
 private String tmsReturn(TmsCollaborationApi.ReturnTransportCommand command){var result=circuit.execute("TMS",()->dubbo.client(TmsCollaborationApi.class).createSupplierReturnTransport(command));accepted(result.accepted(),result.reason());return result.shipmentId();}
 private String tmsCancel(TmsCollaborationApi.CancelTransportCommand command){circuit.execute("TMS",()->{dubbo.client(TmsCollaborationApi.class).cancelTransport(command);return true;});return String.valueOf(command.businessId());}
 private String inventoryLock(InventoryCollaborationApi.ReturnLockCommand command){var result=circuit.execute("INVENTORY",()->dubbo.client(InventoryCollaborationApi.class).lockSupplierReturn(command));accepted(result.accepted(),result.reason());return result.lockNo();}
 private String inventoryRelease(InventoryCollaborationApi.ReturnReleaseCommand command){circuit.execute("INVENTORY",()->{dubbo.client(InventoryCollaborationApi.class).releaseSupplierReturn(command);return true;});return command.lockNo();}
 private String bmsSettlement(BmsCollaborationApi.ReturnSettlementCommand command){var result=circuit.execute("BMS",()->dubbo.client(BmsCollaborationApi.class).createSupplierReturnSettlement(command));accepted(result.accepted(),result.reason());return result.settlementRef();}
 private String mdmCreate(MasterDataCollaborationApi.CreateSupplierCommand command){var result=circuit.execute("MDM",()->dubbo.client(MasterDataCollaborationApi.class).createSupplier(command));accepted(result.accepted(),result.reason());return String.valueOf(result.supplierId());}private String mdmStatus(MasterDataCollaborationApi.ChangeSupplierStatusCommand command){circuit.execute("MDM",()->{dubbo.client(MasterDataCollaborationApi.class).changeSupplierStatus(command);return true;});return String.valueOf(command.supplierId());}private String iamScope(IamCollaborationApi.UpdateSupplierScopeCommand command){circuit.execute("IAM",()->{dubbo.client(IamCollaborationApi.class).updateSupplierDataScope(command);return true;});return String.valueOf(command.userId());}
 private static void accepted(boolean accepted,String reason){if(!accepted)throw new BusinessException(ErrorCode.EXTERNAL_CALL_FAILED,reason==null?"远程系统拒绝命令":reason);}private<T>T read(IntegrationCommand command,Class<T> type){try{return json.readValue(command.payloadJson(),type);}catch(JacksonException exception){throw new IllegalStateException("集成命令反序列化失败",exception);}}
}
