create table purchase_bid_comparison (
    id bigint not null primary key,
    compare_no varchar(64) not null,
    rfq_no varchar(64) not null,
    purchase_org_id bigint not null,
    currency varchar(16) not null,
    status tinyint not null comment '1已生成 2已定标 3已驳回',
    awarded_candidate_id bigint null,
    decision_reason varchar(512) null,
    decided_by bigint null,
    decided_at datetime(3) null,
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_bid_comparison_no (compare_no),
    key idx_purchase_bid_comparison_rfq (rfq_no),
    key idx_purchase_bid_comparison_org_status (purchase_org_id, status, updated_at)
) comment '采购比价结果';

create table purchase_bid_candidate (
    candidate_id bigint not null primary key,
    comparison_id bigint not null,
    supplier_id bigint not null,
    supplier_name varchar(128) null,
    quote_no varchar(64) not null,
    sku_code varchar(64) not null,
    quote_qty decimal(18, 6) not null,
    unit_price decimal(18, 6) not null,
    tax_rate decimal(8, 6) not null,
    delivery_days int not null,
    supplier_score decimal(10, 4) not null,
    transport_score decimal(10, 4) not null,
    estimated_freight_cost decimal(18, 6) not null,
    total_cost decimal(18, 6) not null,
    composite_score decimal(18, 6) not null,
    awarded tinyint not null default 0,
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    key idx_purchase_bid_candidate_comparison (comparison_id, composite_score),
    key idx_purchase_bid_candidate_supplier (supplier_id, sku_code)
) comment '采购比价候选报价快照';

create table purchase_price (
    id bigint not null primary key,
    price_no varchar(64) not null,
    supplier_id bigint not null,
    sku_code varchar(64) not null,
    purchase_org_id bigint not null,
    price_type tinyint not null comment '1标准价 2协议价 3临时价',
    currency varchar(16) not null,
    unit_price decimal(18, 6) not null,
    tax_rate decimal(8, 6) not null,
    tax_included_price decimal(18, 6) not null,
    effective_from date not null,
    effective_to date null,
    source_type varchar(64) null,
    source_no varchar(64) null,
    status tinyint not null comment '1启用 2停用',
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_price_no (price_no),
    key idx_purchase_price_scope (purchase_org_id, supplier_id, sku_code, currency, status),
    key idx_purchase_price_effective (effective_from, effective_to)
) comment '采购价格';
