create table purchase_order (
    id bigint not null primary key,
    order_no varchar(64) not null,
    purchase_type tinyint not null,
    supplier_id bigint not null,
    supplier_code varchar(64) not null,
    supplier_name varchar(256) not null,
    purchase_org_id bigint not null,
    warehouse_code varchar(64) null,
    currency varchar(16) not null,
    total_amount decimal(18, 6) not null,
    tax_amount decimal(18, 6) not null,
    tax_included_amount decimal(18, 6) not null,
    status tinyint not null comment '1草稿 2待审批 3已审批 4待供应商确认 5供应商已确认 6供应商差异 7部分入库 8已完成 9已取消 10已关闭 11已驳回',
    version_no int not null,
    version int not null,
    released_at datetime(3) null,
    cancel_reason varchar(512) null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_order_no (order_no),
    key idx_purchase_order_org_status (purchase_org_id, status, updated_at),
    key idx_purchase_order_supplier (supplier_id, status)
) comment '采购订单';

create table purchase_order_line (
    line_id bigint not null primary key,
    order_id bigint not null,
    sku_code varchar(64) not null,
    sku_name varchar(256) null,
    order_qty decimal(18, 6) not null,
    unit_price decimal(18, 6) not null,
    tax_rate decimal(8, 6) not null,
    tax_included_price decimal(18, 6) not null,
    required_delivery_date date null,
    received_qty decimal(18, 6) not null default 0,
    deleted tinyint not null default 0,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_order_line_sku (order_id, sku_code),
    key idx_purchase_order_line_sku (sku_code)
) comment '采购订单行';

create table purchase_order_change (
    id bigint not null primary key,
    change_no varchar(64) not null,
    order_no varchar(64) not null,
    change_type tinyint not null comment '1数量 2价格 3交期 4取消 5关闭',
    before_snapshot json not null,
    after_snapshot json not null,
    change_reason varchar(512) not null,
    status tinyint not null comment '1待审批 2已生效 3已驳回',
    version int not null,
    deleted tinyint not null default 0,
    created_by bigint not null,
    updated_by bigint not null,
    created_at datetime(3) not null,
    updated_at datetime(3) not null,
    unique key uk_purchase_order_change_no (change_no),
    key idx_purchase_order_change_order (order_no, status)
) comment '采购订单变更单';
