-- MDM service complete schema
-- Generated by consolidating the historical DDL in version order.
-- Import this file into an empty MySQL 8 database before starting the service.
-- This file is the sole schema baseline; the application never changes database structure.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================================
-- Source: V1__mdm_type_template_code_rule.sql"
-- ============================================================================
create table mdm_master_data_type (
  id bigint primary key auto_increment,
  type_code varchar(64) not null,
  type_name varchar(128) not null,
  domain_code varchar(64) not null,
  type_status tinyint not null,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_type_code (type_code)
);

create table mdm_field_template (
  id bigint primary key auto_increment,
  template_code varchar(64) not null,
  type_code varchar(64) not null,
  field_payload text not null,
  template_status tinyint not null,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_template_code (template_code),
  key idx_mdm_template_type (type_code)
);

create table mdm_code_rule (
  id bigint primary key auto_increment,
  rule_code varchar(64) not null,
  type_code varchar(64) not null,
  prefix varchar(32) not null,
  serial_length int not null,
  rule_status tinyint not null,
  current_serial bigint not null,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_rule_code (rule_code),
  key idx_mdm_rule_type (type_code)
);

create table mdm_outbox_event (
  id bigint primary key auto_increment,
  event_type varchar(128) not null,
  business_no varchar(128) not null,
  payload text not null,
  event_status tinyint not null,
  occurred_at datetime not null,
  created_at datetime not null,
  key idx_mdm_outbox_status (event_status, id)
);

create table mdm_operation_log (
  id bigint primary key auto_increment,
  operation_type varchar(64) not null,
  business_no varchar(128) not null,
  operator_id bigint,
  idempotency_key varchar(128),
  created_at datetime not null,
  key idx_mdm_operation_business (business_no)
);

-- ============================================================================
-- Source: V2__mdm_record_version.sql"
-- ============================================================================
create table mdm_master_data_record (
  id bigint primary key auto_increment,
  record_no varchar(64) not null,
  type_code varchar(64) not null,
  data_code varchar(128) not null,
  data_name varchar(256) not null,
  data_payload text not null,
  record_status tinyint not null,
  current_version_no int not null,
  reason varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_record_no (record_no),
  unique key uk_mdm_record_type_code (type_code, data_code),
  key idx_mdm_record_status (record_status, id)
);

create table mdm_master_data_version (
  id bigint primary key auto_increment,
  version_no varchar(64) not null,
  record_no varchar(64) not null,
  type_code varchar(64) not null,
  data_code varchar(128) not null,
  version_number int not null,
  snapshot_payload text not null,
  change_summary varchar(512),
  created_at datetime not null,
  unique key uk_mdm_version_no (version_no),
  unique key uk_mdm_version_record_number (record_no, version_number),
  key idx_mdm_version_type_code (type_code, data_code)
);

-- ============================================================================
-- Source: V3__mdm_publication_subscription.sql"
-- ============================================================================
create table mdm_publication_subscription (
  id bigint primary key auto_increment,
  subscription_no varchar(64) not null,
  type_code varchar(64) not null,
  target_system varchar(64) not null,
  event_topic varchar(128) not null,
  filter_rule text,
  subscription_status tinyint not null,
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_subscription_no (subscription_no),
  key idx_mdm_subscription_active (type_code, subscription_status)
);

create table mdm_publication_log (
  id bigint primary key auto_increment,
  publication_no varchar(64) not null,
  version_no varchar(64) not null,
  type_code varchar(64) not null,
  data_code varchar(128) not null,
  target_system varchar(64) not null,
  event_topic varchar(128) not null,
  publish_status tinyint not null,
  retry_count int not null,
  failure_reason varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_publication_no (publication_no),
  key idx_mdm_publication_version (version_no),
  key idx_mdm_publication_status (publish_status, id)
);

create table mdm_event_inbox (
  event_id varchar(128) primary key,
  event_type varchar(128) not null,
  business_no varchar(128) not null,
  payload text,
  event_status tinyint not null,
  error_message varchar(512),
  created_at datetime not null,
  updated_at datetime not null,
  key idx_mdm_inbox_business (business_no)
);

-- ============================================================================
-- Source: V4__mdm_import_quality.sql"
-- ============================================================================
create table mdm_import_task (
  id bigint primary key auto_increment,
  import_task_no varchar(64) not null,
  type_code varchar(64) not null,
  file_name varchar(256) not null,
  file_url varchar(512) not null,
  file_hash varchar(128) not null,
  import_mode varchar(32) not null,
  validate_only bit not null,
  duplicate_policy varchar(32) not null,
  task_status tinyint not null,
  total_count int not null,
  success_count int not null,
  failed_count int not null,
  error_file_url varchar(512),
  reason varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_import_task_no (import_task_no),
  unique key uk_mdm_import_idempotent (type_code, file_hash, import_mode),
  key idx_mdm_import_status (task_status, id)
);

create table mdm_import_error (
  id bigint primary key auto_increment,
  import_task_no varchar(64) not null,
  row_no int not null,
  field_code varchar(128),
  error_code varchar(64) not null,
  error_message varchar(512) not null,
  raw_payload text,
  created_at datetime not null,
  key idx_mdm_import_error_task (import_task_no, row_no)
);

create table mdm_export_task (
  id bigint primary key auto_increment,
  export_task_no varchar(64) not null,
  type_code varchar(64) not null,
  filter_payload text,
  field_payload text,
  mask_sensitive_fields bit not null,
  export_status tinyint not null,
  file_url varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_export_task_no (export_task_no),
  key idx_mdm_export_type (type_code, id)
);

create table mdm_data_quality_issue (
  id bigint primary key auto_increment,
  issue_no varchar(64) not null,
  type_code varchar(64) not null,
  data_code varchar(128) not null,
  issue_type varchar(64) not null,
  issue_description varchar(512) not null,
  issue_status tinyint not null,
  assignee_id bigint,
  resolution varchar(512),
  version bigint not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_quality_issue_no (issue_no),
  key idx_mdm_quality_type_status (type_code, issue_status)
);

-- ============================================================================
-- Source: V5__mdm_real_file_tasks.sql"
-- ============================================================================
alter table mdm_import_task
  add column processing_started_at datetime null after reason,
  add column attempt_count int not null default 0 after processing_started_at,
  add column next_retry_at datetime null after attempt_count,
  add key idx_mdm_import_dispatch (task_status, next_retry_at, processing_started_at);

create table mdm_import_staging (
  id bigint primary key auto_increment,
  import_task_no varchar(64) not null,
  row_no int not null,
  data_code varchar(128) not null,
  data_name varchar(256) not null,
  data_payload text not null,
  created_at datetime not null,
  unique key uk_mdm_import_staging_row (import_task_no, row_no),
  key idx_mdm_import_staging_task (import_task_no)
);

alter table mdm_export_task
  add column failure_reason varchar(512) null after file_url,
  add column retry_count int not null default 0 after failure_reason,
  add column processing_started_at datetime null after retry_count,
  add column next_retry_at datetime null after processing_started_at,
  add key idx_mdm_export_dispatch (export_status, next_retry_at, processing_started_at);

-- ============================================================================
-- Source: V6__mdm_openapi_boundary.sql"
-- ============================================================================
create table mdm_openapi_client (
  id bigint primary key auto_increment,
  app_code varchar(64) not null,
  secret_value varchar(256) not null,
  type_scope text not null,
  data_code_prefixes text,
  field_allowlist text not null,
  enabled bit not null,
  created_at datetime not null,
  updated_at datetime not null,
  unique key uk_mdm_openapi_client_app (app_code)
);

create table mdm_openapi_snapshot (
  id bigint primary key auto_increment,
  record_no varchar(64) not null,
  type_code varchar(64) not null,
  data_code varchar(128) not null,
  data_name varchar(256) not null,
  data_payload text not null,
  record_status tinyint not null,
  current_version_no int not null,
  record_version bigint not null,
  projected_at datetime not null,
  unique key uk_mdm_openapi_snapshot_code (type_code, data_code),
  key idx_mdm_openapi_snapshot_version (type_code, record_version)
);

-- ============================================================================
-- Source: V7__mdm_rocketmq_delivery.sql"
-- ============================================================================
alter table mdm_outbox_event
    add column retry_count int not null default 0 after event_status,
    add column last_error varchar(1000) null after retry_count,
    add column next_retry_at datetime null after last_error,
    add column published_at datetime null after next_retry_at,
    add column updated_at datetime null after created_at,
    add key idx_mdm_outbox_retry (event_status, next_retry_at, id);

update mdm_outbox_event set updated_at=created_at where updated_at is null;

-- ============================================================================
-- Source: V8__mdm_dubbo_supplier_collaboration.sql"
-- ============================================================================
CREATE TABLE mdm_supplier_rpc_mapping (
    supplier_id BIGINT NOT NULL,
    admission_id BIGINT NOT NULL,
    supplier_code VARCHAR(64) NOT NULL,
    record_no VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (supplier_id),
    UNIQUE KEY uk_mdm_supplier_rpc_admission (admission_id),
    UNIQUE KEY uk_mdm_supplier_rpc_code (supplier_code),
    UNIQUE KEY uk_mdm_supplier_rpc_record (record_no)
);

CREATE TABLE mdm_dubbo_receipt (
    idempotency_key VARCHAR(128) NOT NULL,
    command_type VARCHAR(64) NOT NULL,
    request_fingerprint VARCHAR(1000) NOT NULL,
    reference_no VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (idempotency_key)
);

-- ============================================================================
-- Source: V9__mdm_inbound_event_business_projection.sql"
-- ============================================================================
CREATE TABLE mdm_inbound_business_projection (
    id BIGINT NOT NULL AUTO_INCREMENT,
    projection_type VARCHAR(64) NOT NULL,
    object_key VARCHAR(192) NOT NULL,
    source_system VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(128) NOT NULL,
    projection_status VARCHAR(32) NOT NULL,
    payload JSON NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_mdm_inbound_projection (projection_type, source_system, object_key),
    UNIQUE KEY uk_mdm_inbound_projection_event (event_id),
    KEY idx_mdm_inbound_projection_status (projection_type, projection_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='MDM入站外部编码、引用关系与权限范围投影';

SET FOREIGN_KEY_CHECKS = 1;

