package com.chaobo.scm.supplier.application.contract;

import com.chaobo.scm.common.api.PageResult;
import com.chaobo.scm.common.error.*;
import com.chaobo.scm.supplier.application.masterdata.MasterDataSnapshotPort;
import com.chaobo.scm.supplier.application.qualification.SupplierQualificationPolicyPort;
import com.chaobo.scm.supplier.application.shared.*;
import com.chaobo.scm.supplier.domain.contract.*;
import com.chaobo.scm.supplier.domain.quote.*;
import com.chaobo.scm.supplier.domain.shared.IdentifierGenerator;
import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;import java.util.function.Consumer;

@Service public class SupplierContractApplicationService {
 private final SupplierContractRepository contracts;private final SupplierContractReadModelPort read;private final SupplierQuoteRepository quotes;private final PriceAgreementProjectionPort agreements;private final MasterDataSnapshotPort masterData;private final SupplierQualificationPolicyPort qualifications;private final OutboxRepository outbox;private final AuditLogRepository audit;private final IdentifierGenerator ids;private final TransactionalCommandExecutor executor;
 public SupplierContractApplicationService(SupplierContractRepository contracts,SupplierContractReadModelPort read,SupplierQuoteRepository quotes,PriceAgreementProjectionPort agreements,MasterDataSnapshotPort masterData,SupplierQualificationPolicyPort qualifications,OutboxRepository outbox,AuditLogRepository audit,IdentifierGenerator ids,TransactionalCommandExecutor executor){this.contracts=contracts;this.read=read;this.quotes=quotes;this.agreements=agreements;this.masterData=masterData;this.qualifications=qualifications;this.outbox=outbox;this.audit=audit;this.ids=ids;this.executor=executor;}
 @Transactional(readOnly=true) public PageResult<SupplierContractView> page(Long supplierId,Long scope,Integer status,String keyword,int pageNo,int pageSize){validatePage(pageNo,pageSize);return read.page(scope==null?supplierId:scope,status,keyword,pageNo,pageSize);}
 @Transactional(readOnly=true) public SupplierContractView detail(long id,Long scope){var value=read.detail(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"合同不存在"));if(scope!=null&&scope!=value.supplierId())throw new BusinessException(ErrorCode.NOT_FOUND,"合同不存在");return value;}
 @Transactional public CommandResult create(long supplierId,Long quoteId,String agreement,String type,LocalDate from,LocalDate to,String terms,String attachment,CommandContext context){context.requirePermission("supplier:contract:create");context.requireSupplierScope(supplierId);return executor.execute("supplier:contract",context,new Create(supplierId,quoteId,agreement,type,from,to),()->{ensureSupplierEligible(supplierId);return persist(SupplierContractAggregate.create(supplierId,quoteId,agreement,type,from,to,terms,attachment,context.operatorId(),ids),context,"CREATE_CONTRACT",null);});}
 @Transactional public CommandResult modifyDraft(long id,int version,LocalDate until,String terms,String attachment,CommandContext context){context.requirePermission("supplier:contract:update");return change(id,version,"MODIFY_CONTRACT_DRAFT",context,a->a.modifyDraft(until,terms,attachment,context.operatorId(),ids));}
 @Transactional public CommandResult submit(long id,int version,CommandContext context){context.requirePermission("supplier:contract:submit");return change(id,version,"SUBMIT_CONTRACT",context,a->{ensureSupplierEligible(a.supplierId());a.submit(context.operatorId(),ids);});}
 @Transactional public CommandResult approve(long id,int version,CommandContext context){context.requirePermission("supplier:contract:approve");return change(id,version,"APPROVE_CONTRACT",context,a->{ensureSupplierEligible(a.supplierId());var quote=adoptedQuote(a);a.approve(context.operatorId(),ids);if(quote!=null)agreements.activate(a,quote);});}
 @Transactional public CommandResult activate(long id,int version,CommandContext context){return approve(id,version,context);}
 @Transactional public CommandResult rejectApproval(long id,int version,String comment,CommandContext context){context.requirePermission("supplier:contract:approve");return change(id,version,"REJECT_CONTRACT_APPROVAL",context,a->a.rejectApproval(comment,context.operatorId(),ids));}
 @Transactional public CommandResult renew(long id,int version,LocalDate until,CommandContext context){context.requirePermission("supplier:contract:renew");return change(id,version,"RENEW_CONTRACT",context,a->{a.renew(until,context.operatorId(),ids);if(a.quoteId()!=null)agreements.renew(a);});}
 @Transactional public CommandResult terminate(long id,int version,String reason,CommandContext context){context.requirePermission("supplier:contract:terminate");return change(id,version,"TERMINATE_CONTRACT",context,a->{a.terminate(reason,context.operatorId(),ids);if(a.quoteId()!=null)agreements.terminate(a);});}
 private CommandResult change(long id,int version,String operation,CommandContext context,Consumer<SupplierContractAggregate> action){return executor.execute("supplier:contract",context,new Change(id,version,operation),()->{var aggregate=contracts.find(id).orElseThrow(()->new BusinessException(ErrorCode.NOT_FOUND,"合同不存在"));context.requireSupplierScope(aggregate.supplierId());if(aggregate.version()!=version)throw new BusinessException(ErrorCode.VERSION_CONFLICT,"合同已更新");String before=snapshot(aggregate);action.accept(aggregate);return persist(aggregate,context,operation,before);});}
 private SupplierQuoteAggregate adoptedQuote(SupplierContractAggregate contract){if(contract.quoteId()==null)return null;if(contract.agreement()==null||contract.agreement().isBlank())throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"价格协议编号不能为空");var quote=quotes.findById(contract.quoteId()).orElseThrow(()->new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"关联报价不存在"));if(quote.status()!=QuoteStatus.ADOPTED)throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"只有已采纳报价可以生成价格协议");return quote;}
 private void ensureSupplierEligible(long supplierId){var supplier=masterData.findSupplier(supplierId).orElseThrow(()->new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"供应商主数据快照不存在"));if(!supplier.enabled())throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"供应商未启用，不能处理合同");if(!qualifications.hasValidQualification(supplierId))throw new BusinessException(ErrorCode.BUSINESS_RULE_FAILED,"供应商不存在有效资质，不能处理合同");}
 private CommandResult persist(SupplierContractAggregate aggregate,CommandContext context,String operation,String before){contracts.save(aggregate,context.operatorId());var events=aggregate.pullEvents();outbox.saveAll(events);audit.save(context,operation,"SUPPLIER_CONTRACT",aggregate.id(),aggregate.no(),before,snapshot(aggregate));return new CommandResult(aggregate.id(),aggregate.no(),aggregate.status().code(),aggregate.status().label(),aggregate.version(),events.isEmpty()?null:events.getLast().eventCode(),false);}
 private void validatePage(int pageNo,int pageSize){if(pageNo<1||pageSize<1||pageSize>100)throw new BusinessException(ErrorCode.VALIDATION_FAILED,"分页参数不合法");}private String snapshot(SupplierContractAggregate a){return "{\"contractNo\":\"%s\",\"status\":%d,\"version\":%d}".formatted(a.no(),a.status().code(),a.version());}private record Create(long supplierId,Long quoteId,String agreement,String type,LocalDate from,LocalDate to){}private record Change(long id,int version,String operation){}
}
