CREATE TABLE ecomm_order (
                             id BIGINT NOT NULL AUTO_INCREMENT COMMENT '电商平台订单ID',
                             platform_order_no VARCHAR(50) NOT NULL COMMENT '平台订单号',
                             customer_name VARCHAR(50) NOT NULL COMMENT '客户姓名',
                             customer_nickname VARCHAR(50) COMMENT '客户昵称',
                             customer_phone VARCHAR(20) COMMENT '联系电话',
                             address_detail VARCHAR(200) COMMENT '收货地址详细信息',
                             total_product_amount DECIMAL(10,2) COMMENT '订单商品总金额',
                             freight DECIMAL(10,2) COMMENT '运费',
                             actual_payment DECIMAL(10,2) COMMENT '实付款',
                             create_time DATETIME NOT NULL COMMENT '订单创建时间',
                             pay_time DATETIME COMMENT '付款时间',
                             complete_time DATETIME COMMENT '成交时间',
                             payment_method VARCHAR(20) COMMENT '支付方式',
                             payment_trade_no VARCHAR(50) COMMENT '支付交易号',
                             order_status TINYINT NOT NULL COMMENT '订单状态，如1-待发货,2-已发货,3-完成,4-关闭',
                             remark TEXT COMMENT '备注',
                             created_by BIGINT COMMENT '创建人（员工ID）',
                             created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                             updated_by BIGINT COMMENT '修改人（员工ID）',
                             updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                             is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除,1-已删除',
                             PRIMARY KEY (id),
                             UNIQUE KEY uk_platform_order_no (platform_order_no),
                             KEY idx_create_time (create_time),
                             KEY idx_pay_time (pay_time),
                             KEY idx_complete_time (complete_time),
                             KEY idx_order_status (order_status)
) COMMENT='电商平台订单';


CREATE TABLE ecomm_order_item (
                                  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '电商平台订单明细ID',
                                  platform_order_no VARCHAR(50) NOT NULL COMMENT '平台订单号，对应 ecomm_order.platform_order_no',
                                  sku VARCHAR(50) NOT NULL COMMENT '商品SKU',
                                  price DECIMAL(10,2) NOT NULL COMMENT '价格',
                                  quantity INT NOT NULL COMMENT '数量',
                                  created_by BIGINT COMMENT '创建人（员工ID）',
                                  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                  updated_by BIGINT COMMENT '修改人（员工ID）',
                                  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                  PRIMARY KEY (id),
                                  KEY idx_platform_order_no (platform_order_no),
                                  KEY idx_sku (sku)
) COMMENT='电商平台订单明细';

CREATE TABLE oms_order (
                           id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'OMS订单ID',
                           oms_order_no VARCHAR(50) NOT NULL COMMENT 'OMS订单号',
                           platform VARCHAR(20) NOT NULL COMMENT '平台名称，如淘宝、天猫、京东等',
                           platform_order_no VARCHAR(50) NOT NULL COMMENT '平台订单号',
                           customer_name VARCHAR(50) NOT NULL COMMENT '客户姓名',
                           customer_nickname VARCHAR(50) COMMENT '客户昵称',
                           customer_phone VARCHAR(20) COMMENT '联系电话',
                           address_detail VARCHAR(200) COMMENT '收货地址信息',
                           order_total DECIMAL(10,2) COMMENT '订单商品总价',
                           freight DECIMAL(10,2) COMMENT '运费',
                           actual_payment DECIMAL(10,2) COMMENT '实付款',
                           receive_time DATETIME COMMENT '接收订单时间',
                           create_time DATETIME NOT NULL COMMENT '订单创建时间',
                           pay_time DATETIME COMMENT '付款时间',
                           complete_time DATETIME COMMENT '成交时间',
                           payment_way VARCHAR(20) COMMENT '支付方式',
                           payment_trade_no VARCHAR(50) COMMENT '支付交易号',
                           platform_order_status TINYINT NOT NULL COMMENT '平台订单状态，如待发货',
                           order_status TINYINT NOT NULL COMMENT 'OMS订单状态，如1-待审核,2-审核通过,3-分仓,4-已拆单,5-待发货,6-已发货',
                           remark TEXT COMMENT '备注',
                           created_by BIGINT COMMENT '创建人（员工ID）',
                           created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                           updated_by BIGINT COMMENT '修改人（员工ID）',
                           updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                           is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                           PRIMARY KEY (id),
                           UNIQUE KEY uk_oms_order_no (oms_order_no),
                           KEY idx_platform_order_no (platform_order_no),
                           KEY idx_create_time (create_time),
                           KEY idx_order_status (order_status),
                           KEY idx_receive_time (receive_time)
) COMMENT='OMS订单';

CREATE TABLE oms_order_item (
                                id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'OMS订单明细ID',
                                oms_order_no VARCHAR(50) NOT NULL COMMENT 'OMS订单号，对应 oms_order.oms_order_no',
                                sku VARCHAR(50) NOT NULL COMMENT '商品SKU',
                                price DECIMAL(10,2) NOT NULL COMMENT '价格',
                                quantity INT NOT NULL COMMENT '数量',
                                created_by BIGINT COMMENT '创建人（员工ID）',
                                created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                updated_by BIGINT COMMENT '修改人（员工ID）',
                                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                PRIMARY KEY (id),
                                KEY idx_oms_order_no (oms_order_no),
                                KEY idx_sku (sku)
) COMMENT='OMS订单明细';

CREATE TABLE delivery_order (
                                id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发货单ID',
                                delivery_no VARCHAR(50) NOT NULL COMMENT '发货单号',
                                warehouse_id BIGINT NOT NULL COMMENT '仓库ID',
                                oms_order_no VARCHAR(50) NOT NULL COMMENT 'OMS订单号',
                                expected_delivery_time DATETIME COMMENT '预计发货时间',
                                delivery_time DATETIME COMMENT '发货时间',
                                logistic_channel_id BIGINT COMMENT '物流渠道ID',
                                logistic_no VARCHAR(50) COMMENT '物流单号',
                                logistic_cost DECIMAL(10,2) COMMENT '物流费用',
                                delivery_status INT NOT NULL COMMENT '状态：1-待分波,2-待分拣,3-待复核,4-待打包,5-待称重,6-待分配物流,7-待出库,8-待揽收,9-发货成功',
    -- 新增目的地地址字段：
                                dest_name VARCHAR(50) COMMENT '收货人姓名',
                                dest_phone VARCHAR(20) COMMENT '收货联系电话',
                                dest_address VARCHAR(200) COMMENT '收货地址',
                                dest_postcode VARCHAR(10) COMMENT '邮编',
                                remark TEXT COMMENT '备注',
                                created_by BIGINT COMMENT '创建人（员工ID）',
                                created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                updated_by BIGINT COMMENT '修改人（员工ID）',
                                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                PRIMARY KEY (id),
                                UNIQUE KEY uk_delivery_no (delivery_no),
                                KEY idx_warehouse_id (warehouse_id),
                                KEY idx_oms_order_no (oms_order_no),
                                KEY idx_expected_delivery_time (expected_delivery_time),
                                KEY idx_delivery_time (delivery_time),
                                KEY idx_delivery_status (delivery_status),
                                KEY idx_logistic_no (logistic_no)
) COMMENT='发货单';


CREATE TABLE delivery_order_item (
                                     id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发货单明细ID',
                                     delivery_no VARCHAR(50) NOT NULL COMMENT '发货单号，对应 delivery_order.delivery_no',
                                     sku VARCHAR(50) NOT NULL COMMENT '商品SKU',
                                     product_name VARCHAR(100) COMMENT '商品名称',
                                     order_quantity INT NOT NULL COMMENT '订单商品数量',
                                     shipped_quantity INT COMMENT '实际发货数量',
                                     unit_id INT NOT NULL COMMENT '计量单位ID',  -- 新增计量单位字段
                                     created_by BIGINT COMMENT '创建人（员工ID）',
                                     created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                     updated_by BIGINT COMMENT '修改人（员工ID）',
                                     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                     is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                     PRIMARY KEY (id),
                                     KEY idx_delivery_no (delivery_no),
                                     KEY idx_sku (sku)
) COMMENT='发货单明细';

CREATE TABLE return_apply (
                              id BIGINT NOT NULL AUTO_INCREMENT COMMENT '退货申请ID',
                              order_no VARCHAR(50) NOT NULL COMMENT '关联订单号（电商平台或OMS订单号）',
                              return_apply_no VARCHAR(50) NOT NULL COMMENT '退货申请单号',
                              apply_type TINYINT NOT NULL COMMENT '退货申请类型：1-全部退货, 2-部分退货, 3-仅退款, 4-仅部分退款',
                              refund_total_amount DECIMAL(10,2) COMMENT '应退款总金额',
                              refund_amount DECIMAL(10,2) COMMENT '实际退款金额',
                              refund_reason VARCHAR(200) COMMENT '退款/退货原因',
                              remark TEXT COMMENT '备注',
                              return_type TINYINT NOT NULL COMMENT '退货方式：1-上门取件, 2-自行邮寄',
                              apply_time DATETIME NOT NULL COMMENT '申请时间',
                              audit_emp_id BIGINT COMMENT '审核人（员工ID）',
                              audit_time DATETIME COMMENT '审核时间',
                              created_by BIGINT COMMENT '创建人（员工ID）',
                              created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                              updated_by BIGINT COMMENT '修改人（员工ID）',
                              updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                              is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除,1-已删除',
                              PRIMARY KEY (id),
                              UNIQUE KEY uk_return_apply_no (return_apply_no),
                              KEY idx_order_no (order_no),
                              KEY idx_apply_time (apply_time),
                              KEY idx_apply_type (apply_type),
                              KEY idx_return_type (return_type),
                              KEY idx_audit_time (audit_time)
) COMMENT='退货申请表（apply）';

CREATE TABLE return_apply_item (
                                   id BIGINT NOT NULL AUTO_INCREMENT COMMENT '退货申请明细ID',
                                   return_apply_no VARCHAR(50) NOT NULL COMMENT '退货申请单号，对应 return_apply.return_apply_no',
                                   sku VARCHAR(50) NOT NULL COMMENT '商品SKU',
                                   quantity INT NOT NULL COMMENT '申请退货数量',
                                   price DECIMAL(10,2) NOT NULL COMMENT '商品价格',
                                   unit_id INT NOT NULL COMMENT '计量单位ID',
                                   created_by BIGINT COMMENT '创建人（员工ID）',
                                   created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   updated_by BIGINT COMMENT '修改人（员工ID）',
                                   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                   is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                   PRIMARY KEY (id),
                                   KEY idx_return_apply_no (return_apply_no),
                                   KEY idx_sku (sku)
) COMMENT='退货申请明细表（apply_item）';

CREATE TABLE sales_return_order (
                                    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '销售退货单ID',
                                    sales_return_no VARCHAR(50) NOT NULL COMMENT '销售退货单单号',
                                    order_no VARCHAR(50) NOT NULL COMMENT '关联原订单号',
                                    return_apply_no VARCHAR(50) NOT NULL COMMENT '关联退货申请单号，对应 return_apply.return_apply_no',
                                    apply_type TINYINT NOT NULL COMMENT '退货申请类型：1-全部退货, 2-部分退货, 3-仅退款, 4-仅部分退款',
                                    refund_requested_amount DECIMAL(10,2) COMMENT '申请退款金额',
                                    actual_refund_amount DECIMAL(10,2) COMMENT '实际退款金额',
                                    refund_reason VARCHAR(200) COMMENT '退款原因',
                                    remark TEXT COMMENT '备注',
                                    return_type TINYINT NOT NULL COMMENT '退货方式：1-上门取件, 2-自行邮寄',
                                    apply_time DATETIME NOT NULL COMMENT '申请时间',
                                    logistics_no VARCHAR(50) COMMENT '客户提供的退货物流单号',
    -- 取件信息
                                    pickup_contact VARCHAR(50) COMMENT '取件联系人',
                                    pickup_phone VARCHAR(20) COMMENT '取件联系电话',
                                    pickup_address VARCHAR(200) COMMENT '取件详细地址',
                                    pickup_postcode VARCHAR(10) COMMENT '取件邮编',
                                    pickup_longitude DECIMAL(10,6) COMMENT '取件地址经度',
                                    pickup_latitude DECIMAL(10,6) COMMENT '取件地址纬度',
    -- 收货信息（仓库填写）
                                    receipt_contact VARCHAR(50) COMMENT '收货联系人',
                                    receipt_phone VARCHAR(20) COMMENT '收货联系电话',
                                    receipt_address VARCHAR(200) COMMENT '收货详细地址',
                                    receipt_postcode VARCHAR(10) COMMENT '收货邮编',
                                    receipt_longitude DECIMAL(10,6) COMMENT '收货地址经度',
                                    receipt_latitude DECIMAL(10,6) COMMENT '收货地址纬度',
                                    return_status TINYINT NOT NULL COMMENT '退货单状态，如待审核、已审核、待收货、已收货、拒收等',
                                    created_by BIGINT COMMENT '创建人（员工ID）',
                                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                    updated_by BIGINT COMMENT '修改人（员工ID）',
                                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                    is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                    PRIMARY KEY (id),
                                    UNIQUE KEY uk_sales_return_no (sales_return_no),
                                    KEY idx_order_no (order_no),
                                    KEY idx_return_apply_no (return_apply_no),
                                    KEY idx_apply_time (apply_time),
                                    KEY idx_return_status (return_status)
) COMMENT='销售退货单';


CREATE TABLE sales_return_order_item (
                                         id BIGINT NOT NULL AUTO_INCREMENT COMMENT '销售退货单明细ID',
                                         sales_return_no VARCHAR(50) NOT NULL COMMENT '销售退货单单号，对应 sales_return_order.sales_return_no',
                                         sku VARCHAR(50) NOT NULL COMMENT '商品SKU',
                                         product_name VARCHAR(100) COMMENT '商品名称',
                                         quantity INT NOT NULL COMMENT '退货数量',
                                         price DECIMAL(10,2) NOT NULL COMMENT '商品价格',
                                         unit_id INT NOT NULL COMMENT '计量单位ID',
                                         batch_no VARCHAR(50) COMMENT '批次号',  -- 批次号重命名
                                         location_id BIGINT COMMENT '库位ID',       -- 如需记录具体仓储位置
                                         created_by BIGINT COMMENT '创建人（员工ID）',
                                         created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         updated_by BIGINT COMMENT '修改人（员工ID）',
                                         updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                         is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                         PRIMARY KEY (id),
                                         KEY idx_sales_return_no (sales_return_no),
                                         KEY idx_sku (sku),
                                         KEY idx_batch_no (batch_no)
) COMMENT='销售退货单明细表';
