CREATE TABLE supplier_delivery_order (
                                         id BIGINT NOT NULL AUTO_INCREMENT COMMENT '供应商发货单ID',
                                         delivery_no VARCHAR(50) NOT NULL COMMENT '发货单单号',
                                         delivery_time DATETIME NOT NULL COMMENT '发货时间',
                                         arrival_time DATETIME COMMENT '到货时间',
                                         order_no VARCHAR(50) NOT NULL COMMENT '采购单单号，对应 purchase_order.order_no',
                                         apply_no VARCHAR(50) NOT NULL COMMENT '采购申请单号，对应 purchase_apply.apply_no',
                                         purchaser_emp_id BIGINT NOT NULL COMMENT '采购人ID',
                                         supplier_id BIGINT NOT NULL COMMENT '供应商ID',
                                         total_amount DECIMAL(10,2) COMMENT '货品总金额',
                                         logistics_number VARCHAR(50) COMMENT '物流单号',
                                         warehouse_id BIGINT COMMENT '仓库ID',
                                         remark TEXT COMMENT '备注',
                                         status INT NOT NULL COMMENT '状态：1-待发货，2-运输中，3-已完成',
                                         created_by BIGINT COMMENT '创建人（员工ID）',
                                         created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         updated_by BIGINT COMMENT '修改人（员工ID）',
                                         updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                         is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
                                         PRIMARY KEY (id),
                                         UNIQUE KEY uk_delivery_no (delivery_no),
                                         KEY idx_delivery_time (delivery_time),
                                         KEY idx_arrival_time (arrival_time),
                                         KEY idx_order_no (order_no),
                                         KEY idx_apply_no (apply_no),
                                         KEY idx_status (status),
                                         KEY idx_purchaser_emp_id (purchaser_emp_id),
                                         KEY idx_supplier_id (supplier_id),
                                         KEY idx_warehouse_id (warehouse_id)
) COMMENT = '供应商发货单表';

CREATE TABLE supplier_delivery_order_item (
                                              id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发货单详情ID',
                                              delivery_no VARCHAR(50) NOT NULL COMMENT '发货单单号，对应 supplier_delivery_order.delivery_no',
                                              sku VARCHAR(50) NOT NULL COMMENT '商品SKU',
                                              production_time DATETIME COMMENT '生产时间',
                                              expiration_time DATETIME COMMENT '保质期',
                                              quantity INT NOT NULL COMMENT '数量',
                                              unit_id INT NOT NULL COMMENT '计量单位ID',
                                              unit_price DECIMAL(10,2) COMMENT '单价',
                                              total_price DECIMAL(10,2) COMMENT '总价',
                                              remark TEXT COMMENT '备注',
                                              created_by BIGINT COMMENT '创建人（员工ID）',
                                              created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                              updated_by BIGINT COMMENT '修改人（员工ID）',
                                              updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                              is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
                                              PRIMARY KEY (id),
                                              KEY idx_delivery_no (delivery_no),
                                              KEY idx_sku (sku),
                                              KEY idx_production_time (production_time),
                                              KEY idx_expiration_time (expiration_time)
) COMMENT = '供应商发货单详情表';