CREATE TABLE logistics_order (
                                 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '物流单ID',
                                 logistics_no VARCHAR(50) NOT NULL COMMENT '物流单号',
                                 related_customer_id BIGINT COMMENT '关联客户ID',
    -- 发货信息
                                 sender_name VARCHAR(50) COMMENT '发货人',
                                 sender_phone VARCHAR(20) COMMENT '发货联系电话',
                                 sender_address VARCHAR(200) COMMENT '发货地址',
                                 sender_postcode VARCHAR(10) COMMENT '邮编',
                                 sender_longitude DECIMAL(10,6) COMMENT '经度',
                                 sender_latitude DECIMAL(10,6) COMMENT '纬度',
    -- 收货地址信息
                                 receiver_name VARCHAR(50) COMMENT '收货人',
                                 receiver_phone VARCHAR(20) COMMENT '收货联系电话',
                                 receiver_address VARCHAR(200) COMMENT '收货地址',
                                 receiver_postcode VARCHAR(10) COMMENT '邮编',
                                 receiver_longitude DECIMAL(10,6) COMMENT '经度',
                                 receiver_latitude DECIMAL(10,6) COMMENT '纬度',
    -- 货物信息
                                 goods_name VARCHAR(100) COMMENT '货物名称',
                                 goods_type VARCHAR(50) COMMENT '货物类型',
                                 goods_quantity INT COMMENT '货物件数',
                                 goods_weight DECIMAL(10,2) COMMENT '货物重量',
                                 logistic_cost DECIMAL(10,2) COMMENT '物流费用',
                                 logistic_status INT NOT NULL COMMENT '物流状态，如1-待揽收,2-运输中,3-已签收,4-异常',
                                 logistic_type INT NOT NULL COMMENT '物流类型，1-次日达,2-隔日达,3-闪送,4-冷链,5-快运,6-普运',
                                 pickup_time DATETIME COMMENT '揽收时间',
                                 send_time DATETIME COMMENT '发货时间',
                                 delivery_time DATETIME COMMENT '送达时间',
                                 delivery_details TEXT COMMENT '送货详情，如地点、时间、经度、纬度',
                                 remark TEXT COMMENT '备注',
                                 created_by BIGINT COMMENT '创建人（员工ID）',
                                 created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                 updated_by BIGINT COMMENT '修改人（员工ID）',
                                 updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                 is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除',
                                 PRIMARY KEY (id),
                                 UNIQUE KEY uk_logistics_no (logistics_no),
                                 KEY idx_pickup_time (pickup_time),
                                 KEY idx_send_time (send_time),
                                 KEY idx_delivery_time (delivery_time),
                                 KEY idx_logistic_status (logistic_status)
) COMMENT='物流单';
